version: '3.8'

services:
  unicatcher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unicatcher-app
    # 使用 .env 文件来管理环境变量
    env_file:
      - .env
    environment:
      - PLAYWRIGHT_BROWSERS_PATH=/app/data/playwright
    ports:
      - "3067:3067"
    volumes:
      # 数据持久化
      - unicatcher-data:/app/data
      # 数据库持久化
      - unicatcher-db:/app/prisma
    restart: unless-stopped
    # 添加健康检查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3067/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  unicatcher-data:
    driver: local
  unicatcher-db:
    driver: local 