(function(g){var window=this;'use strict';var r3d=function(k,a){a<k.startTime&&(k.endTime=a+k.endTime-k.startTime,k.startTime=a);k.progress=(a-k.startTime)/(k.endTime-k.startTime);k.progress>1&&(k.progress=1);k.N=1E3/(a-k.L);k.L=a;Y5d(k,k.progress);k.progress==1?(k.K=0,bP(k),k.onFinish(),k.LN()):k.isPlaying()&&k.Yi()},iBr=function(){gt||(gt=new g.gD(function(){jOr()},20));
var k=gt;k.isActive()||k.start()},bP=function(k){k=g.v7(k);
delete sE[k];g.SV(sE)&&gt&&gt.stop()},TDK=function(k,a,y){y.stopPropagation();
W89(k);mdT(k,a);k.K.focus()},S5a=function(k,a,y){function q(Zl){if(!Zl)return null;
var fG=Zl.simpleText;return fG?fG:Zl.runs?g.Bh(Zl.runs,function(r4){return r4.text}).join(""):null}
function e(Zl){var fG=Zl.hovercardButton;if(!fG)return null;fG=fG.subscribeButtonRenderer;if(!fG)return null;var r4=q(fG.unsubscribedButtonText),a3=q(fG.subscribedButtonText);if(fG.subscribed){var OZ=q(fG.subscriberCountWithUnsubscribeText);var I3=q(fG.subscriberCountText)}else OZ=q(fG.subscriberCountText),I3=q(fG.subscriberCountWithSubscribeText);var ka=null;if(Zl.signinEndpoint){ka=Ae(Zl,"signinEndpoint","webNavigationEndpointData","url");if(!ka){var Ya,CG;ka=(CG=g.v((Ya=fG.signInEndpoint)==null?
void 0:Ya.commandMetadata,g.Uw))==null?void 0:CG.url}if(!ka)return null}return r4&&(a3||ka)?{subscribed:fG.subscribed,subscribeText:r4,subscribeCount:OZ,unsubscribeText:a3,unsubscribeCount:I3,enabled:fG.enabled,signinUrl:ka,classic:Zl.useClassicSubscribeButton}:null}
function f(Zl){if(Zl){var fG=[],r4=Zl.videoId;r4&&fG.push("v="+r4);(r4=Zl.playlistId)&&fG.push("list="+r4);(Zl=Zl.startTimeSeconds)&&fG.push("t="+Zl);return"/watch?"+fG.join("&")}}
a=a.endscreenElementRenderer;if(!a)return null;var H=a.style,B=a.endpoint||{},Z=null,z=null,Y=!1,r=null,W=null,m=null,T=null,O=!1,x=null,V=null,l=null,P=null,N=null,F=null;if(H==="VIDEO")g.v(B,g.vm)?Z=g.v(B,g.vm).url:(F=g.v(B,g.GW),Z=f(F)),z=!1,r=k,a.thumbnailOverlays?(Y=a.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,W=q(Y.text),Y=Y.style==="LIVE"):W=q(a.videoDuration);else if(H==="PLAYLIST")g.v(B,g.vm)?Z=g.v(B,g.vm).url:(F=g.v(B,g.GW),Z=f(F)),z=!1,r=k,m=q(a.playlistLength);else if(H===
"CHANNEL"){if(O=Ae(B,"browseEndpoint","browseId"))T=O,Z="/channel/"+T;z=!1;r="new";(O=!!a.isSubscribe)?x=e(a):V=q(a.subscribersText)}else H==="WEBSITE"?((l=Ae(B,"urlEndpoint","url"))&&(Z=l),z=!0,r="new",l=a.icon.thumbnails[0].url):H==="CREATOR_MERCHANDISE"&&(a.productPrice&&(P=q(a.productPrice)),a.additionalFeesText&&(N=q(a.additionalFeesText)),(z=Ae(B,"urlEndpoint","url"))&&(Z=z),z=!0,r="new");k=Ae(a,"title","accessibility","accessibilityData","label");var t=a.endpoint?a.endpoint.clickTrackingParams:
null,M="";if(a.metadata){var ea=q(a.metadata);ea&&(M=ea)}return{id:"element-"+y,type:H,title:q(a.title),metadata:M,callToAction:q(a.callToAction),rV:a.image,iconUrl:l,left:Number(a.left),width:Number(a.width),top:Number(a.top),aspectRatio:Number(a.aspectRatio),startMs:Math.floor(Number(a.startMs)),endMs:Math.floor(Number(a.endMs)),videoDuration:W,eP:Y,playlistLength:m,channelId:T,subscribeButton:x,subscribersText:V,isSubscribe:O,targetUrl:Z||null,Pj3:z,sessionData:t?{itct:t}:null,PIj:r,Rh:k?k:null,
isPlaceholder:a.isPlaceholder,impressionUrls:p_(a.impressionUrls||[],P_),kK:p_(a.hovercardShowUrls||[],P_),clickUrls:p_(B.loggingUrls||[],P_),visualElement:g.Kr(a.trackingParams),productPrice:P,additionalFeesText:N,watchEndpoint:F||null}},P_=function(k){return k.baseUrl||null},n_=function(k){k.publish("cardstatechange",k.Lv()&&k.tN()?1:0)},UdV=function(k){var a=g.gP(k);
k=g.J1(k);return new g.jA(a.x,a.y,k.width,k.height)},wsr=function(k){g.pF.call(this,k);
var a=this;this.Kw=this.V=!1;this.loadNumber=0;this.N={};this.logger=new Ddr(this.player);this.L=new g.e9(this);this.X=this.G=null;this.events=new g.e9(this);this.F0=this.aj=this.K=null;this.vz=[];g.U(this,this.L);this.L.Y(this.player,"onVideoAreaChange",function(){a.publish("onVideoAreaChange")});
this.L.Y(this.player,"onHideControls",function(){a.publish("onHideControls")});
this.L.Y(this.player,"onShowControls",function(){a.publish("onShowControls")});
this.L.Y(this.player,"resize",function(f){a.publish("resize",f)});
this.L.Y(this.player,"presentingplayerstatechange",function(f){a.publish("presentingplayerstatechange",f)});
this.subscribe("presentingplayerstatechange",this.ue,this);this.subscribe("resize",this.xl,this);this.player.Z().Ij.subscribe("vast_info_card_add",this.If,this);g.U(this,this.events);this.Lw=this.createElement({C:"div",T:"video-custom-annotations"});this.D=new g.u({C:"div",nw:["ytp-player-content","ytp-iv-player-content"]});g.U(this,this.D);g.ED(this.player,this.D.element,4);this.D.hide();this.j=new g.u({C:"div",nw:["ytp-iv-video-content"]});g.U(this,this.j);k=this.createElement({C:"div",T:"video-annotations"});
k.appendChild(this.Lw);this.j.element.appendChild(k);this.EF()&&this.load();var y=this.createElement({C:"style"});(g.Cy("HEAD")[0]||document.body).appendChild(y);this.addOnDisposeCallback(function(){g.JM(y)});
if(k=y.sheet){for(var q=g.A(OBG),e=q.next();!e.done;e=q.next())k.insertRule(e.value,0);q=g.A(QO9);for(e=q.next();!e.done;e=q.next())k.insertRule(e.value,0)}},Je=function(k){return k.K&&k.K.tV?k.K.tV:k.cards[0]&&k.cards[0].tV?k.cards[0].tV:null},xdX=function(k,a,y){a&&(y?Nq(k,a.map(function(q){return g.ba(q,y)})):Nq(k,a))},uP=function(k,a,y,q){g.LK.call(this);
if(!Array.isArray(k)||!Array.isArray(a))throw Error("Start and end parameters must be arrays");if(k.length!=a.length)throw Error("Start and end points must be the same length");this.D=k;this.G=a;this.duration=y;this.X=q;this.coords=[];this.progress=this.N=0;this.L=null},Rs9=function(k,a){var y={startMs:Math.floor(Number(k.startMs)),
impressionUrls:p_(k.impressionUrls||[],P_),elements:p_(k.elements||[],function(q,e){return S5a(a,q,e)})};
k.trackingParams&&(y.visualElement=g.Kr(k.trackingParams));return y},Ga9=function(k,a,y){var q=q===void 0?{}:q;
var e;return e=g.oA(k,a,function(){g.ew(e);y.apply(k,arguments)},q)},v_=function(k,a,y){for(var q=-1,e=-1,f=0;f<k.length;f++){if(k[f].height===a||k[f].width===y)return k[f];
((k[f].height||0)<a||(k[f].width||0)<y)&&(q<0||(k[q].height||0)<(k[f].height||0)||(k[q].width||0)<(k[f].width||0))?q=f:((k[f].height||0)>=a||(k[f].width||0)>=y)&&(e<0||(k[e].height||0)>(k[f].height||0)||(k[e].width||0)>(k[f].width||0))&&(e=f)}return k[e>=0?e:q]},Vt9=function(k,a){var y=k.player.getVideoData().clientPlaybackNonce;
k=k.player.getCurrentTime().toFixed(2);y={CPN:y,AD_CPN:y,MT:k};k=[];for(var q=0;q<a.length;q++)k.push(lq1(a[q],y));return k},bB9=function(k){var a=k.annotation.data;
if(k.annotation.style==="cta")var y=6;else if(k.annotation.style==="video"||k.annotation.style==="playlist")y=7;k.N=a.collapsedelay_ms||k.N;var q=["iv-promo","iv-promo-inactive"];k.XR().setAttribute("aria-hidden","true");k.XR().setAttribute("aria-label","Promotion");k.XR().tabIndex=0;var e=k.annotation.oY(),f=a.image_url;if(f){var H=k.createElement({C:"div",nw:["iv-promo-img","iv-click-target"]});f=k.createElement({C:"img",U:{src:f,"aria-hidden":"true"}});H.appendChild(f);a.video_duration&&!a.is_live?
(f=k.createElement({C:"span",T:"iv-promo-video-duration",Dq:a.video_duration}),H.appendChild(f)):a.playlist_length&&(f=k.createElement({C:"span",T:"iv-promo-playlist-length",Dq:a.playlist_length.toString()}),H.appendChild(f));e&&Fo(k,H,e,k.annotation.id,a.session_data,void 0,y)}e?(f=k.createElement({C:"a",T:"iv-promo-txt"}),g.Ei(f,ok(e)),k.K=f):k.K=k.createElement({C:"div",T:"iv-promo-txt"});switch(k.annotation.style){case "cta":case "website":var B=k.createElement({C:"p",S:[{C:"strong",Dq:a.text_line_1}]});
var Z=k.createElement({C:"p",S:[{C:"span",T:"iv-promo-link",Dq:a.text_line_2}]});if(f=a.text_line_3){q.push("iv-promo-website-card-cta-redesign");var z=k.createElement({C:"button",nw:["iv-promo-round-expand-icon","ytp-button"]});f=k.createElement({C:"button",nw:["iv-button","iv-promo-button"],S:[{C:"span",T:"iv-button-content",Dq:f}]});var Y=k.createElement({C:"div",T:"iv-promo-button-container"});Y.appendChild(f);e&&Fo(k,k.XR(),e,k.annotation.id,a.session_data,void 0,y)}g.C7(k.K,"iv-click-target");
e&&Fo(k,k.K,e,k.annotation.id,a.session_data,void 0,y);break;case "playlist":case "video":B=k.createElement({C:"p",S:[{C:"span",Dq:a.text_line_1}]}),Z=k.createElement({C:"p",S:[{C:"strong",Dq:a.text_line_2}]}),a.is_live&&(B=Z,Z=k.createElement({C:"span",nw:["yt-badge","iv-promo-badge-live"],Dq:"LIVE NOW"})),g.C7(k.K,"iv-click-target"),e&&Fo(k,k.K,e,k.annotation.id,a.session_data,void 0,y),q.push("iv-promo-video")}B&&k.K.appendChild(B);Z&&k.K.appendChild(Z);k.G.appendChild(k.K);Y&&k.G.appendChild(Y);
y=k.createElement({C:"div",T:"iv-promo-actions"});k.D=k.createElement({C:"button",nw:["iv-promo-expand","ytp-button"]});k.D.title="Expand";k.context.K.listen(k.D,"click",function(r){TDK(k,5E3,r)});
y.appendChild(k.D);g.aa(k.D,!1);k.context.K.listen(k.XR(),"mouseover",k.wp,k);k.context.K.listen(k.XR(),"mouseout",k.iy,k);k.context.K.listen(k.XR(),"touchend",function(r){TDK(k,5E3,r)});
k.j=k.createElement({C:"button",nw:["iv-promo-close","ytp-button"]});k.j.title="Close";k.context.K.listen(k.j,"click",k.annotation.style==="cta"&&a.text_line_3?k.Dy:k.vE,k);y.appendChild(k.j);g.LA(k.XR(),q);H&&(g.P1(k.XR(),H),z&&H.appendChild(z));g.P1(k.XR(),k.G);g.P1(k.XR(),y)},C_=function(k){g.iM(k.J.getRootNode(),"ytp-cards-shopping-active",gA9(k))},CsV=function(k,a){var y=!1,q=a.getElementsByTagName("annotations");
if(q&&!(q.length<1)&&(q=q[0].getAttribute("itct"))){var e=g.Yv();if(e){var f=g.JI();f&&g.w4(g.PE)(void 0,e,f,[g.Kr(q)])}}a=a.getElementsByTagName("annotation");for(q=0;q<a.length;q++){f=sOG(k,a[q]);e=null;try{if(f){var H=f.id,B=/.+/;var Z=typeof H==="string"&&B!=null&&H!=null&&H.match(B)?H:"";var z=he(f.type,A30),Y=he(f.style,ps9),r=PsG(f.data),W=r.length!==0?JSON.parse(r):{};var m=f.action;f=nA9;if(m==null)var T=null;else if(g.Bs(m)){B=[];for(var O=g.A(m),x=O.next();!x.done;x=O.next()){var V=f(x.value);
V&&B.push(V)}T=B}else{var l=f(m);T=l?[l]:[]}e=Z&&z?new J3r(Z,z,Y,T,W):null}else e=null}catch(ea){}if(e)if(e.type==="branding"||e.type==="promotion"){f=k;B=e;var P=NDr(f),N=null;switch(B.type){case "branding":if(f.player.Z().rJ)break;f.player.W("web_player_overlay_positioned_layout")?(P.setAttribute("data-overlay-order","11"),f.player.xH(P,4,!0)):f.D.element.appendChild(P);N=new Mq(P,Xo(f),B);break;case "promotion":g.ED(f.player,P,4),N=new uLa(P,Xo(f),B)}N&&N.xC();if(f=N)g.U(k,f),k.N[e.id]=f}else if(e.type===
"card"||e.type==="drawer"){k.K||(k.K=vA0(k),g.U(k,k.K));if(e.type==="card"){P=k.K;var F=(y=e)&&y.data&&y.data.card_type;e=y.data;if(F)switch(f=e.tracking||{},f={w3:f.impression,click:f.click,close:f.close,vZ:f.teaser_impression,Qm:f.teaser_click},B=e.tracking_params||{},N=null,F){case "collaborator":y={id:y.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||
!1,XY:f,Ra:B.card?g.Kr(B.card):null,SQ:B.teaser?g.Kr(B.teaser):null,Ei:B.icon?g.Kr(B.icon):null,channelId:e.channel_id,customMessage:e.custom_message?e.custom_message:null,profileImageUrl:e.image_url,title:e.title,metaInfo:e.meta_info,url:c_({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};L_(P,y);break;case "playlist":y={id:y.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,
autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,XY:f,Ra:B.card?g.Kr(B.card):null,SQ:B.teaser?g.Kr(B.teaser):null,Ei:B.icon?g.Kr(B.icon):null,Zw:e.image_url,playlistVideoCount:e.playlist_video_count,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,url:c_({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};L_(P,y);break;case "productListing":e.signin_url&&(N=c_({target:"current",
value:e.signin_url}));F=[];for(var t=e.offers||[],M=0;M<t.length;M++)F.push(new F89(g.v6(t[M].merchant),g.v6(t[M].price)));y={id:y.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,XY:f,Ra:B.card?g.Kr(B.card):null,SQ:B.teaser?g.Kr(B.teaser):null,Ei:B.icon?g.Kr(B.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:
null,showLinkIcon:!!e.show_link_icon,f6:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:c_({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),DXs:N,vFZ:e.signin_title?e.signin_title:void 0,lC3:e.signin_message?e.signin_message:void 0,offers:F,onClickCommand:null};L_(P,y);break;case "simple":y={id:y.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,
startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,XY:f,Ra:B.card?g.Kr(B.card):null,SQ:B.teaser?g.Kr(B.teaser):null,Ei:B.icon?g.Kr(B.icon):null,imageUrl:e.image_url,displayDomain:e.display_domain?e.display_domain:null,showLinkIcon:!!e.show_link_icon,f6:e.button_icon_url?e.button_icon_url:null,title:e.title,customMessage:e.custom_message?e.custom_message:null,url:c_({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null};
L_(P,y);break;case "video":y={id:y.id,timestamp:e.timestamp||0,type:e.card_type,teaserText:e.teaser_text,teaserDurationMs:e.teaser_duration_ms,startMs:e.start_ms,autoOpen:e.auto_open||!1,sessionData:e.session_data||{},sponsored:e.sponsored||!1,XY:f,Ra:B.card?g.Kr(B.card):null,SQ:B.teaser?g.Kr(B.teaser):null,Ei:B.icon?g.Kr(B.icon):null,Zw:e.image_url,videoDuration:e.video_duration||null,customMessage:e.custom_message?e.custom_message:null,title:e.title,metaInfo:e.meta_info,isLiveNow:!!e.is_live_now,
url:c_({pause_on_navigation:e.pause_on_navigation,target:e.target||"new",value:e.url}),onClickCommand:null},L_(P,y)}}else oA1(k.K,e);y=!0}}y&&(n_(k.player),k.xl())},c_=function(k){if(!k)return null;
var a=g.sd(PsG(k.value));a=g.OT(a);if(!a)return null;var y=he(k.target,hsT,"current");if(y==null)k=null;else{var q=k.show_link_icon;k=new MtK(a,y,q==="true"||q==="false"?q==="true":!0,k.pause_on_navigation!=null?k.pause_on_navigation:!0)}return k},Xs9=function(k){return k.customMessage?Ik("div","iv-card-message",k.customMessage):""},c3X=function(k){k.Kw.push(g.J7("iv-teaser-shown",k.Dx,k));
k.Kw.push(g.J7("iv-teaser-hidden",k.xEY,k));k.Kw.push(g.J7("iv-teaser-clicked",k.va,k));k.jw=!0},L8a=function(k){var a=k.annotation.data;
"start_ms"in a&&"end_ms"in a&&k.addCueRange(Number(a.start_ms),Number(a.end_ms),k.annotation.id,function(){k.show()},function(){k.hide()})},te=function(k,a,y){k.j&&(y?k.X.show():k.X.hide());
for(var q=g.A(Object.keys(k.D)),e=q.next();!e.done;e=q.next())e=e.value,e!==a&&g.iM(k.D[e].element,"ytp-ce-element-shadow-show",y)},Ik=function(k,a,y){a?typeof a==="string"?a={"class":a}:Array.isArray(a)&&(a={"class":a.join(" ")}):a={};
a.dir=g.eO(y);return{C:k,U:a,Dq:y}},jOr=function(){var k=g.nj();
g.IX(sE,function(a){r3d(a,k)});
g.SV(sE)||iBr()},EE=function(k,a){k=k.player.Z();
if(a){if(a.startsWith("//"))return k.protocol+":"+a;if(a.startsWith("/"))return g.Vw(k)+a}else return"";return a},Iq0=function(k,a,y){g.zO(a.element,"ytp-ce-element-hover")||(y.type==="VIDEO"||y.type==="PLAYLIST"?g.C7(a.element,"ytp-ce-element-hover"):k.player.Z().D?(new g.gD(function(){g.C7(a.element,"ytp-ce-element-hover")},200)).start():g.C7(a.element,"ytp-ce-element-hover"),K_(k,y.kK),te(k,y.id,!0))},EAV=function(k,a){return a?a:ttT(k)?"current":"new"},K8T=function(k,a,y){K_(k,a.clickUrls,y);
(k=g.Yv())&&a.Pj3&&g.vP(k,a.visualElement)},kt9=function(k,a){return g.mu(k.cards,function(y){return y.tV.id===a})},ajG=function(k,a,y){this.type=k;
this.trigger=a;this.url=y},qlX=function(k,a){if(!g.zO(k.J.getRootNode(),"ytp-cards-teaser-shown")){if(k.K!==a){var y=g.Yv(),q=k.K?k.K.tV.Ei:k.Ei;
y&&q&&g.Mp(y,[q]);k.K=a;C_(k)}(y=k.isInitialized&&k.XR().style.display=="none")||(y=k.context.J.getPlayerState(),q=y===0&&k.context.J.getCurrentTime()===0,y=!(y===1||y===3||q));if(!y&&a.tV.teaserDurationMs){var e;y={teaserText:a.tV.teaserText,durationMs:a.tV.teaserDurationMs,onClickCommand:a.tV.onClickCommand,qx:(e=a.tV.qx)!=null?e:null};k.J.FP(!0,y)}k.ME.isActive()||((!k.j||!k.JG.isActive()&&k.Ij)&&yZX(k,a),k.ME.start(910+a.tV.teaserDurationMs))}},eWT=function(k){return k?{style:"background-image: url("+
k+")"}:{}},fjX=function(k){if(!k.customMessage)return"";
var a=["iv-card-action","iv-card-primary-link"],y={};k.f6&&(a.push("iv-card-action-icon"),y.style="background-image: url("+k.f6+");");y.dir=g.eO(k.customMessage);var q=[{C:"span",Dq:k.customMessage}];k.showLinkIcon&&(q.push("\u00a0"),q.push({C:"span",T:"iv-card-link-icon"}));return{C:"div",nw:a,U:y,S:q}},$uX=function(k,a){g.YG.call(this,k);
this.coords=a.coords;this.x=a.coords[0];this.y=a.coords[1];this.z=a.coords[2];this.duration=a.duration;this.progress=a.progress;this.fps=a.N;this.state=a.K},k$=function(k,a,y){y=y===void 0?!0:y;
k.player.J_("creatorendscreen");k.j&&(k.j.dispose(),k.j=null,k.X.dispose(),k.X=null);for(var q=g.A(Object.values(k.D)),e=q.next();!e.done;e=q.next())e.value.dispose();k.D={};k.N={};k.V.length>0&&(k.V.forEach(function(B){B.dispose()}),k.V.length=0);
k.K&&(g.MF(k.K,"ytp-ce-element-show"),k.K.setAttribute("aria-hidden","true"));k.G=0;if((k.endscreen=a)&&a.elements){y&&Hn9(k);y=[];q=new g.Uc(a.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});y.push(q);k.player.Z().D||(k.j=new g.u({C:"div",T:"ytp-ce-shadow"}),g.ED(k.player,k.j.element,4),k.X=new g.Yi(k.j,200));for(q=0;q<a.elements.length;++q){e=a.elements[q];var f=du9(k,e);if(f){k.D[e.id]=f;k.N[e.id]=e;g.ED(k.player,f.element,4);var H=new g.Uc(e.startMs,e.endMs,{id:"ytp-ce-element-"+
e.id,namespace:"creatorendscreen"});y.push(H);Bi9(k,f,e)}else g.vn(new g.s_("buildEndscreenElement null",e))}k.player.RY(y);k.M0()}},Zn9=function(k,a){k.method="POST";
k.postParams=k.postParams||{};a.tP&&(k.postParams.ic_coll=a.tP);a.B3&&(k.postParams.ic_xml=a.B3);a.N9&&(k.postParams.ic_track=a.N9)},ttT=function(k){var a;
(a=k)&&!(a=k.length>1?k.charAt(0)==="/"&&k.charAt(1)!=="/":k==="/")&&(a=k.replace(/^(https?:)?\/\//,"").split("/",1),a=!a||a.length<1||!a[0]?[]:a[0].toLowerCase().split(".").reverse(),a=a[0]==="com"&&a[1]==="youtube"||a[0]==="be"&&a[1]==="youtu");return a?k.indexOf("/redirect?")===-1:!1},Mq=function(k,a,y){am.call(this,k,a,y);
this.D=null;this.G=!1;this.j=null;this.L=!1;this.K=this.N=this.X=null},Ae=function(k,a){var y=g.Bs(a),q=y?a:arguments;
for(y=y?0:1;y<q.length;y++){if(k==null)return;k=k[q[y]]}return k},zWK=function(k){return k==="annotation-editor"||k==="live-dashboard"},p_=function(k,a){return g.yv(g.Bh(k,a),function(y){return!!y})},PsG=function(k){return typeof k==="string"?k:""},Bi9=function(k,a,y){function q(Z){Z&&(a.listen("blur",function(){Z.style.display!="none"&&k.Kw&&Z.focus()}),a.Y(Z,"focus",f),a.Y(Z,"blur",e))}
function e(){H(-1)}
function f(){H(1)}
function H(Z){k.G+=Z;k.G>0?(g.C7(a.element,"ytp-ce-force-expand"),te(k,y.id,!0)):(g.MF(a.element,"ytp-ce-force-expand"),g.MF(a.element,"ytp-ce-element-hover"),te(k,y.id,!1))}
a.listen("mouseenter",function(){Iq0(k,a,y)});
a.listen("mouseleave",function(){YlT(k,a,y)});
k.player.Z().D||a.listen("click",function(){g.C7(a.element,"ytp-ce-element-hover")});
a.listen("click",function(Z){rZX(k,y,Z)});
a.listen("keypress",function(Z){rZX(k,y,Z)});
a.listen("focus",function(){Iq0(k,a,y)});
a.listen("blur",function(){YlT(k,a,y)});
a.listen("touchstart",function(){Iq0(k,a,y)});
var B=g.Pn("ytp-ce-expanding-overlay-hider",a.element);B&&a.Y(B,"touchstart",function(Z){Z.stopPropagation();g.MF(a.element,"ytp-ce-element-hover");g.MF(a.element,"ytp-ce-force-expand")});
a.listen("keydown",function(Z){k.Kw=Z.keyCode===9&&!Z.shiftKey});
q(g.Pn("ytp-sb-subscribe",a.element));q(g.Pn("ytp-sb-unsubscribe",a.element));a.listen("focus",f);a.listen("blur",e)},jqd=function(k,a){this.context=k;
this.K=a},YlT=function(k,a,y){g.MF(a.element,"ytp-ce-element-hover");
g.MF(a.element,"ytp-ce-force-expand");te(k,y.id,!1)},inT=function(k){return Math.pow(k,3)},am=function(k,a,y){yV.call(this,k,a);
this.annotation=y;this.isActive=!1},J3r=function(k,a,y,q,e){this.id=k;
this.type=a;this.style=y;this.data=e;this.action=q||[]},muV=function(k,a){var y=a.cardId?a.cardId:"cr:"+k.G,q=k.J.Z().experiments.OY("enable_error_corrections_infocard_web_client");
if(!a.content&&a.teaser.simpleCardTeaserRenderer&&q){var e=a.teaser.simpleCardTeaserRenderer,f=a.icon?a.icon.infoCardIconRenderer:null;if(e.channelAvatar&&e.channelAvatar.thumbnails&&e.channelAvatar.thumbnails.length>0)var H=v_(e.channelAvatar.thumbnails,22,22).url;a={id:y,timestamp:k.G,type:"simple",teaserText:g.Nz(e.message),teaserDurationMs:Number(a.cueRanges[0].teaserDurationMs),startMs:Number(a.cueRanges[0].startCardActiveMs),autoOpen:!!a.autoOpen,sessionData:{},sponsored:!1,XY:{},Ra:null,SQ:e.trackingParams?
g.Kr(e.trackingParams):null,Ei:f&&f.trackingParams?g.Kr(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,f6:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null,qx:H};L_(k,a)}else{var B;if((B=a.content)==null?0:B.simpleCardContentRenderer){if(!a.cueRanges.length)return;H=(e=a.content)==null?void 0:e.simpleCardContentRenderer;e=a.teaser.simpleCardTeaserRenderer;f=a.icon?a.icon.infoCardIconRenderer:null;a={id:y,timestamp:k.G,type:"simple",teaserText:g.Nz(e.message),
teaserDurationMs:Number(a.cueRanges[0].teaserDurationMs),startMs:Number(a.cueRanges[0].startCardActiveMs),autoOpen:!!a.autoOpen,sessionData:qA(k,y,a,H),sponsored:!1,XY:eE(H,e,H.command),Ra:H.trackingParams?g.Kr(H.trackingParams):null,SQ:e.trackingParams?g.Kr(e.trackingParams):null,Ei:f&&f.trackingParams?g.Kr(f.trackingParams):null,imageUrl:v_(H.image.thumbnails,290,290).url,displayDomain:H.displayDomain?g.Nz(H.displayDomain):null,showLinkIcon:!!H.showLinkIcon,f6:null,title:H.title?g.Nz(H.title):"",
customMessage:H.callToAction?g.Nz(H.callToAction):"",url:g.v(H.command,g.vm).url?c_({pause_on_navigation:!k.context.videoData.isLivePlayback,target:"new",value:g.v(H.command,g.vm).url}):null,onClickCommand:null};L_(k,a)}else{var Z;if((Z=a.content)==null?0:Z.collaboratorInfoCardContentRenderer){if(!a.cueRanges.length)return;H=(f=a.content)==null?void 0:f.collaboratorInfoCardContentRenderer;e=a.teaser.simpleCardTeaserRenderer;f=a.icon?a.icon.infoCardIconRenderer:null;a={id:y,timestamp:k.G,type:"collaborator",
teaserText:g.Nz(e.message),teaserDurationMs:Number(a.cueRanges[0].teaserDurationMs),startMs:Number(a.cueRanges[0].startCardActiveMs),autoOpen:!!a.autoOpen,sessionData:qA(k,y,a,H),sponsored:!1,XY:eE(H,e,H.endpoint),Ra:H.trackingParams?g.Kr(H.trackingParams):null,SQ:e.trackingParams?g.Kr(e.trackingParams):null,Ei:f&&f.trackingParams?g.Kr(f.trackingParams):null,channelId:g.v(H.endpoint,g.xn).browseId,customMessage:H.customText?g.Nz(H.customText):null,profileImageUrl:v_(H.channelAvatar.thumbnails,290,
290).url,title:H.channelName?g.Nz(H.channelName):"",metaInfo:[H.subscriberCountText?g.Nz(H.subscriberCountText):""],url:c_({pause_on_navigation:!k.context.videoData.isLivePlayback,target:"new",value:g.v(H.endpoint,g.xn).canonicalBaseUrl?g.v(H.endpoint,g.xn).canonicalBaseUrl:"/channel/"+g.v(H.endpoint,g.xn).browseId}),onClickCommand:null};L_(k,a)}else{var z;if((z=a.content)==null?0:z.playlistInfoCardContentRenderer){if(!a.cueRanges.length)return;var Y;H=(Y=a.content)==null?void 0:Y.playlistInfoCardContentRenderer;
e=a.teaser.simpleCardTeaserRenderer;f=a.icon?a.icon.infoCardIconRenderer:null;a={id:y,timestamp:k.G,type:"playlist",teaserText:g.Nz(e.message),teaserDurationMs:Number(a.cueRanges[0].teaserDurationMs),startMs:Number(a.cueRanges[0].startCardActiveMs),autoOpen:!!a.autoOpen,sessionData:qA(k,y,a,H),sponsored:!1,XY:eE(H,e,H.action),Ra:H.trackingParams?g.Kr(H.trackingParams):null,SQ:e.trackingParams?g.Kr(e.trackingParams):null,Ei:f&&f.trackingParams?g.Kr(f.trackingParams):null,Zw:v_(H.playlistThumbnail.thumbnails,
258,290).url,customMessage:H.customMessage?g.Nz(H.customMessage):null,playlistVideoCount:g.Nz(H.playlistVideoCount),title:H.playlistTitle?g.Nz(H.playlistTitle):"",metaInfo:[H.channelName?g.Nz(H.channelName):"",H.videoCountText?g.Nz(H.videoCountText):""],url:c_({pause_on_navigation:!k.context.videoData.isLivePlayback,target:"new",value:Wud(H.action)}),onClickCommand:null};L_(k,a)}else{var r;if((r=a.content)==null?0:r.videoInfoCardContentRenderer){if(!a.cueRanges.length)return;var W;H=(W=a.content)==
null?void 0:W.videoInfoCardContentRenderer;e=a.teaser.simpleCardTeaserRenderer;f=a.icon?a.icon.infoCardIconRenderer:null;a={id:y,timestamp:k.G,type:"video",teaserText:g.Nz(e.message),teaserDurationMs:Number(a.cueRanges[0].teaserDurationMs),startMs:Number(a.cueRanges[0].startCardActiveMs),autoOpen:!!a.autoOpen,sessionData:qA(k,y,a,H),sponsored:!1,XY:eE(H,e,H.action),Ra:H.trackingParams?g.Kr(H.trackingParams):null,SQ:e.trackingParams?g.Kr(e.trackingParams):null,Ei:f&&f.trackingParams?g.Kr(f.trackingParams):
null,Zw:v_(H.videoThumbnail.thumbnails,258,290).url,videoDuration:H.lengthString?g.Nz(H.lengthString):null,customMessage:H.customMessage?g.Nz(H.customMessage):null,title:H.videoTitle?g.Nz(H.videoTitle):"",metaInfo:[H.channelName?g.Nz(H.channelName):"",H.viewCountText?g.Nz(H.viewCountText):""],isLiveNow:!!H.badge,url:c_({pause_on_navigation:!k.context.videoData.isLivePlayback,target:"new",value:Wud(H.action)}),onClickCommand:null};L_(k,a)}}}}}k.G++},sOG=function(k,a){for(var y={},q=g.A(a.attributes),
e=q.next();!e.done;e=q.next())e=e.value,y[e.name]=e.nodeValue;
for(q=0;q<a.childNodes.length;q++)if(e=a.childNodes[q],g.nL(e)&&e.nodeType==1){if(y[e.tagName])var f=y[e.tagName];else if(e.tagName==="data"){e.childNodes.length>0&&(f=e.childNodes[0].nodeValue,y[e.tagName]=typeof f==="string"?f.trim():f);continue}else f=[],y[e.tagName]=f;e&&e.tagName==="TEXT"?e.childNodes.length===1&&e.childNodes[0].nodeType===3?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(sOG(k,e))}return y},Xo=function(k){if(!k.aj){var a=new Tia(k);
g.U(k,a);var y=new g.I5(k);g.U(k,y);k.aj=new SlG(a,y,k.player.Z(),k.player.getVideoData(),k.logger,k.player,k.wM)}return k.aj},Wud=function(k){var a;
return((a=g.v(k,g.vm))==null?0:a.url)?g.v(k,g.vm).url:(k=g.v(k,g.GW))&&k.videoId?(a="/watch?v="+k.videoId,k.playlistId&&(a+="&list="+k.playlistId),k.index&&(a+="&index="+k.index),k.startTimeSeconds&&(a+="&t="+k.startTimeSeconds),a):null},UuX=function(k,a,y){g.MF(k.XR(),"iv-branding-active");
k.N=new g.gD(function(){g.aa(a,!1);k.K||(y.style.width=g.bF(0,!0))},250);
k.N.start();k.L=!1},DuX=function(k){k.isCollapsed||k.V||k.L||(g.C7(k.XR(),"iv-promo-collapsed"),k.isCollapsed=!0,k.X.start())},Y5d=function(k,a){typeof k.X==="function"&&(a=k.X(a));
k.coords=Array(k.D.length);for(var y=0;y<k.D.length;y++)k.coords[y]=(k.G[y]-k.D[y])*a+k.D[y]},he=function(k,a,y){for(var q in a)if(a[q]===k)return k;
return y},K_=function(k,a,y){function q(){f||(e++,e===a.length&&(H.stop(),y&&y()))}
if(!a||a.length===0||fd(k))y&&y();else{a=Vt9(k,a);var e=0,f=!1,H=new g.gD(function(){f=!0;y&&y()},1E3,k);
H.start();for(k=0;k<a.length;k++)g.Jn(a[k],q)}},On1=function(k,a){k.vz=a;
var y=k.J.getVideoData();if(!y)return!1;y=g.jN(y);if(y==null?0:y.markersMap)for(var q,e=0;((q=y)==null?void 0:q.markersMap.length)>e;e++){var f=void 0,H=(f=y)==null?void 0:f.markersMap[e];if(H.key==="ERROR_CORRECTION_MARKERS"&&(f=void 0,(H=(f=H.value)==null?void 0:f.markers)&&H.length>0))return q=void 0,a.startMs=((q=g.v(H[0],g.lK4))==null?void 0:q.timeRangeStartMillis)||0,k.vz=null,!0}return!1},fd=function(k){return k.player.Z().playerStyle==="creator-endscreen-editor"},du9=function(k,a){var y=null;
switch(a.type){case "VIDEO":k={C:"div",nw:["ytp-ce-element","ytp-ce-video"],U:{tabindex:"0","aria-label":a.Rh||"","aria-hidden":"true"},S:[{C:"div",T:"ytp-ce-element-shadow"},{C:"div",T:"ytp-ce-covering-image",U:$$(a)},{C:"div",T:"ytp-ce-covering-shadow-top"},{C:"a",T:"ytp-ce-covering-overlay",U:{href:EE(k,a.targetUrl),tabindex:"-1"},S:[{C:"div",nw:["ytp-ce-video-title","ytp-webkit-ellipsis"],U:{dir:g.eO(a.title||"")},Dq:a.title},{C:"div",T:a.eP?"ytp-ce-live-video-duration":"ytp-ce-video-duration",
Dq:a.videoDuration||void 0}]}]};y=new g.u(k);break;case "PLAYLIST":k={C:"div",nw:["ytp-ce-element","ytp-ce-playlist"],U:{tabindex:"0","aria-label":a.Rh||"","aria-hidden":"true"},S:[{C:"div",T:"ytp-ce-element-shadow"},{C:"div",T:"ytp-ce-covering-image",U:$$(a)},{C:"div",T:"ytp-ce-covering-shadow-top"},{C:"a",T:"ytp-ce-covering-overlay",U:{href:EE(k,a.targetUrl),tabindex:"-1"},S:[{C:"div",nw:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],U:{dir:g.eO(a.title||"")},Dq:a.title},{C:"div",T:"ytp-ce-playlist-count",
S:[{C:"div",T:"ytp-ce-playlist-icon"},{C:"div",T:"ytp-ce-playlist-count-text",Dq:a.playlistLength||void 0}]}]}]};y=new g.u(k);break;case "CHANNEL":y={C:"div",nw:["ytp-ce-element","ytp-ce-channel",a.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],U:{tabindex:"0","aria-label":a.Rh||"","aria-hidden":"true"},S:[{C:"div",T:"ytp-ce-element-shadow"},{C:"div",T:"ytp-ce-expanding-overlay",S:[{C:"div",T:"ytp-ce-expanding-overlay-hider"},{C:"div",T:"ytp-ce-expanding-overlay-background"},{C:"div",T:"ytp-ce-expanding-overlay-content",
S:[{C:"div",T:"ytp-ce-expanding-overlay-body",S:[{C:"div",T:"ytp-ce-expanding-overlay-body-padding",S:[{C:"a",nw:["ytp-ce-channel-title","ytp-ce-link"],U:{href:EE(k,a.targetUrl),target:"_blank",tabindex:"-1",dir:g.eO(a.title||"")},Dq:a.title},a.subscribeButton?{C:"div",T:"ytp-ce-subscribe-container",S:[{C:"div",T:"ytp-ce-channel-subscribe"}]}:"",a.subscribersText?{C:"div",T:"ytp-ce-channel-subscribers-text",Dq:a.subscribersText}:"",a.metadata?{C:"div",nw:["ytp-ce-channel-metadata","yt-ui-ellipsis",
"yt-ui-ellipsis-3"],Dq:a.metadata}:""]}]}]}]},{C:"div",T:"ytp-ce-expanding-image",U:$$(a)}]};y=new g.u(y);var q=g.Ys(document,"div","ytp-ce-channel-subscribe",y.element)[0];if(a.subscribeButton&&a.channelId){g.C7(q,"ytp-ce-subscribe-button");if(k.player.Z().D){var e=null;var f=a.sessionData.itct}else e="endscreen",f=null;e=new g.yD(a.subscribeButton.subscribeText,a.subscribeButton.subscribeCount,a.subscribeButton.unsubscribeText,a.subscribeButton.unsubscribeCount,!!a.subscribeButton.enabled,!!a.subscribeButton.classic,
a.channelId,!!a.subscribeButton.subscribed,e,f,k.player,!1);q.appendChild(e.element);k.V.push(e)}break;case "WEBSITE":k={C:"div",nw:["ytp-ce-element","ytp-ce-website"],U:{tabindex:"0","aria-label":a.Rh||"","aria-hidden":"true"},S:[{C:"div",T:"ytp-ce-element-shadow"},{C:"div",T:"ytp-ce-expanding-overlay",S:[{C:"div",T:"ytp-ce-expanding-overlay-hider"},{C:"div",T:"ytp-ce-expanding-overlay-background"},{C:"div",T:"ytp-ce-expanding-overlay-content",S:[{C:"div",T:"ytp-ce-expanding-overlay-body",S:[{C:"div",
T:"ytp-ce-expanding-overlay-body-padding",S:[{C:"div",T:"ytp-ce-website-title",U:{dir:g.eO(a.title||"")},Dq:a.title},{C:"div",T:"ytp-ce-website-metadata",Dq:a.metadata},{C:"a",nw:["ytp-ce-website-goto","ytp-ce-link"],U:{href:EE(k,a.targetUrl),target:"_blank",tabindex:"-1"},Dq:a.callToAction}]}]}]}]},{C:"div",T:"ytp-ce-expanding-image",U:$$(a)},{C:"div",T:"ytp-ce-expanding-icon",U:eWT(a.iconUrl)}]};y=new g.u(k);break;case "CREATOR_MERCHANDISE":y="",a.productPrice&&(y={C:"div",T:"ytp-ce-merchandise-price-container",
S:[{C:"div",T:"ytp-ce-merchandise-price",Dq:a.productPrice}]},a.additionalFeesText&&y.S.push({C:"div",T:"ytp-ce-merchandise-additional-fees",Dq:a.additionalFeesText})),k={C:"div",nw:["ytp-ce-element","ytp-ce-merchandise"],U:{tabindex:"0","aria-label":a.Rh||"","aria-hidden":"true"},S:[{C:"div",T:"ytp-ce-element-shadow"},{C:"div",T:"ytp-ce-expanding-overlay",S:[{C:"div",T:"ytp-ce-expanding-overlay-hider"},{C:"div",T:"ytp-ce-expanding-overlay-background"},{C:"div",T:"ytp-ce-expanding-overlay-content",
S:[{C:"div",T:"ytp-ce-expanding-overlay-body",S:[{C:"div",T:"ytp-ce-expanding-overlay-body-padding",S:[{C:"div",T:"ytp-ce-merchandise-title",U:{dir:g.eO(a.title||"")},Dq:a.title},y,{C:"div",T:"ytp-ce-merchandise-metadata",Dq:a.metadata},{C:"a",nw:["ytp-ce-merchandise-goto","ytp-ce-link"],U:{href:EE(k,a.targetUrl),target:"_blank",tabindex:"-1"},Dq:a.callToAction}]}]}]}]},{C:"div",T:"ytp-ce-expanding-image",U:$$(a)},{C:"div",T:"ytp-ce-merchandise-invideo-cta-container",S:[{C:"div",T:"ytp-ce-merchandise-invideo-cta",
Dq:a.callToAction||void 0}]}]},y=new g.u(k)}a.isPlaceholder&&g.C7(y.element,"ytp-ce-placeholder");return y},H3=function(k,a){k="background-image: url("+k+");";
var y=[];a&&y.push(a);return{C:"div",T:"iv-card-image",U:{style:k},S:y}},wia=function(k){var a=k.player.getVideoData();
if(a.sY){var y=k.player.Z().Ij.get(a.videoId);if(y){var q={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,H){e=k.loadNumber;f=a.videoId;k.loaded&&k.loadNumber===e&&k.player.getVideoData().videoId===f&&(H=g.PF(H)&&H.responseXML?H.responseXML:null)&&CsV(k,H)}};
g.HA()&&(q.onFinish=QqG(k,q.onFinish));q.postParams={ic_only:"1"};Zn9(q,y);k.V=!0;g.nT(a.sY,q)}}},xu9=function(k,a){a=!a.isCued()&&!g.h(a,1024);
k.D.h3(a);k.j.h3(a)},RW9=function(k,a,y){yV.call(this,a,y);
var q=this;this.J=k;this.eventId=null;this.jw=this.Ij=this.WO=this.j=this.isInitialized=!1;this.cards=[];this.au=this.X=this.NE=this.N=this.tG=this.K=null;this.Kw=[];this.vz=this.V=this.Ei=this.cz=null;this.G=0;this.JG=new g.gD(function(){},y.B.Kv?4E3:3E3);
g.U(this,this.JG);this.ME=new g.gD(function(){});
g.U(this,this.ME);this.Lw=new jqd(y,function(e,f,H,B,Z,z){Fo(q,e,f,H,B,Z,z)});
this.aj=new g.u({C:"div",T:"iv-drawer",U:{id:"iv-drawer"},S:[{C:"div",T:"iv-drawer-header",U:{"aria-role":"heading"},S:[{C:"span",T:"iv-drawer-header-text"},{C:"button",nw:["iv-drawer-close-button","ytp-button"],U:{"aria-label":"Hide cards",tabindex:"0"}}]},{C:"div",T:"iv-drawer-content"}]});g.U(this,this.aj);this.L=this.aj.element;this.Zq=new g.Yi(this.aj,330);g.U(this,this.Zq);this.ub=g.Pn("iv-drawer-header-text",this.L);this.D=g.Pn("iv-drawer-content",this.L);this.addCueRange(0,y.videoData.lengthSeconds*
1E3,"",function(){q.WO&&d$(q,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(q.WO=q.j)&&B3(q)});
this.sY=new g.e9(this);g.U(this,this.sY);this.J.addEventListener("videodatachange",this.zC.bind(this))},ZN=function(k,a,y,q,e){uP.call(this,a,y,q,e);
this.element=k},lq1=function(k,a){return k.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(y){var q=unescape(y);
q=q.substring(1,q.length-1);return a[q]?escape(a[q]):y})},SlG=function(k,a,y,q,e,f,H){this.K=k;
this.j=a;this.B=y;this.videoData=q;this.logger=e;this.J=f;this.D=H},ljX=function(k){var a=k.player.getVideoData(),y=a.videoId;
k.L&&k.L.abort();y={method:"POST",onFinish:function(e){var f=k.L=null;e.status===200&&(e=e.responseText,e.substring(0,3)===")]}"&&(e=e.substring(3),f=JSON.parse(e),f=Rs9(f,Gt9(k))));k$(k,f)},
urlParams:{v:y},withCredentials:!0};k.aj&&(y.urlParams.ptype="embedded");var q=a.Wf;q&&(y.postParams={ad_tracking:q});if(a=g.hv4(a))if(a=g.sd(a),a=g.OT(a))k.L=g.nT(a,y)},d$=function(k,a,y){if(!k.j){k.Zq.show();
k.tG=new g.gD(function(){g.C7(k.context.J.getRootNode(),g.w8.IV_DRAWER_OPEN)},0);
k.tG.start();k.sY.Y(k.D,"mousewheel",function(H){k.JG.start();H.preventDefault();H=H||window.event;var B=0;H.type=="MozMousePixelScroll"?B=0==(H.axis==H.HORIZONTAL_AXIS)?H.detail:0:window.opera?B=H.detail:B=H.wheelDelta%120==0?"WebkitTransform"in document.documentElement.style?window.chrome&&navigator.platform.indexOf("Mac")==0?H.wheelDeltaY/-30:H.wheelDeltaY/-1.2:H.wheelDelta/-1.6:H.wheelDeltaY/-3;if(H=B)k.D.scrollTop+=H});
k.j=!0;var q=g.Yv();q&&k.cz&&k.V&&g.KO(q,[k.cz,k.V]);a={TRIGGER_TYPE:a};for(var e=g.A(k.cards),f=e.next();!f.done;f=e.next())f=f.value,f.lL||(f.lL=!0,xdX(k.context.logger,f.tV.XY.w3,a)),q&&g.KO(q,[f.tV.Ra]);n_(k.J);y&&(k.N=new g.gD(function(){k.NE=k.X;k.au.focus()},330),k.N.start())}},gA9=function(k){if(k.K)return k.K.tV.type==="productListing";
if(k.J.W("enable_wn_infocards")){var a;return!((a=k.cards)==null||!a.length)&&g.lH(k.cards,function(y){return y.tV.type==="productListing"})}return g.lH(k.cards,function(y){return y.tV.type==="productListing"})},Gt9=function(k){return k.player.getVideoData().SR?"current":k.aj?"new":"current"},Vn9=function(k,a){var y;
return a.onClickCommand&&((y=g.v(a.onClickCommand,g.nH9))==null?void 0:y.targetId)==="engagement-panel-error-corrections"?(k.vz=a,!0):!1},L_=function(k,a){if(!Vn9(k,a)||On1(k,a)){var y=bna(k,a);
if(y){var q={tV:a,Sl:y.element,lL:!1};if(a.onClickCommand)k.J.W("web_infocards_teaser_show_logging_fix")&&(k.jw||c3X(k),sq9(k,a.id),y=k.findLastIndex(q),g.fm(k.cards,y,0,q));else{k.isInitialized||g1K(k);sq9(k,a.id);var e=k.findLastIndex(q);g.fm(k.cards,e,0,q);y.pw(k.D,e);k.m7()}a.autoOpen?k.addCueRange(a.startMs,0x8000000000000,a.id,function(){k.j||(k.K=q,C_(k),yZX(k,q),d$(k,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(y=k.context.J.getCurrentTime()*1E3,y<5E3&&y>a.startMs&&qlX(k,q),k.addCueRange(a.startMs,
a.startMs+1,a.id,function(){qlX(k,q)}),C_(k))}}},AZd=function(k){k.L&&(g.DP.clearTimeout(k.L),k.L=null)},nA9=function(k){if(!k)return null;
var a=he(k.type,pid),y=he(k.trigger,PBr);k=k.url;k=Array.isArray(k)&&k.length?k[0]:k;k=c_(k?k:null);return a?new ajG(a,y,k):null},vA0=function(k){var a=new g.u({C:"div"});
g.aa(a.element,!1);var y=new RW9(k.player,a.element,Xo(k));g.U(y,a);a.pw(k.D.element);y.xC();return y},oA1=function(k,a){a=a.data;
a.autoOpenMs&&k.addCueRange(a.autoOpenMs,0x8000000000000,"",function(){d$(k,"YOUTUBE_DRAWER_AUTO_OPEN")});
a.autoCloseMs&&k.addCueRange(a.autoCloseMs,0x8000000000000,"",function(){B3(k)});
var y=a.headerText;g.uF(k.ub,y);k.X&&(k.J.W("player_tooltip_data_title_killswitch")?k.X.setAttribute("title",y):k.X.setAttribute("data-tooltip-title",y));a.eventId&&(k.eventId=a.eventId);k.cz=g.Kr(a.trackingParams);k.V=g.Kr(a.closeTrackingParams);k.Ei=g.Kr(a.iconTrackingParams)},n1d=function(k){return 3*k*k-2*k*k*k},Nq=function(k,a,y,q){var e=1,f=void 0,H=-1;
if(y){var B=!1;f=function(){e--;e||B||(clearTimeout(H),B=!0,y())};
H=setTimeout(function(){B=!0;y()},1E3)}a=g.A(a||[]);
for(var Z=a.next();!Z.done;Z=a.next())Z=Z.value,e++,g.Jn(Z,f);q&&(e++,q!==0&&k.J.sendVideoStatsEngageEvent(q,f))},qA=function(k,a,y,q){return{feature:y.feature?y.feature:"cards",
src_vid:k.context.videoData.videoId,annotation_id:a,ei:k.context.videoData.eventId||"",itct:q.trackingParams||""}},uLa=function(k,a,y){am.call(this,k,a,y);
var q=this;this.V=this.isCollapsed=this.aj=!1;this.N=5E3;this.D=this.j=this.K=this.L=null;this.G=this.createElement({C:"div",nw:["iv-promo-contents"]});this.X=new g.gD(function(){q.K.setAttribute("aria-hidden","true");g.aa(q.j,!1);g.aa(q.D,!0)},700,this);
g.U(this,this.X)},$$=function(k){if(k.rV)var a=k.rV.thumbnails;
return eWT(a?a[a.length-1].url:null)},JZ9=function(k,a,y,q,e){k.j.stop();
if(!k.L){var f=g.J1(a);k.K||(a.style.width=g.bF(f.width,!0),y.style.width=g.bF(f.width,!0));g.tO(q,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.tO(q,"right","1px");k.L=!0;g.aa(a,!0);k.X=new g.gD(function(){g.C7(this.XR(),"iv-branding-active")},0,k);
k.X.start()}},Hn9=function(k){var a=g.JI(),y=g.Yv();
y&&a&&k.endscreen.visualElement&&g.w4(g.e6)(void 0,y,a,k.endscreen.visualElement)},ok=function(k){return k.value?k.value:null},eE=function(k,a,y){return{w3:(k.impressionLoggingUrlsV2s||[]).map(function(q){return q.baseUrl||""}),
click:(y.loggingUrls||[]).map(function(q){return q.baseUrl||""}),
close:(a.dismissLoggingUrlsV2s||[]).map(function(q){return q.baseUrl||""}),
vZ:(a.impressionLoggingUrlsV2s||[]).map(function(q){return q.baseUrl||""}),
Qm:(a.clickLoggingUrlsV2s||[]).map(function(q){return q.baseUrl||""})}},sq9=function(k,a){if(a=kt9(k,a))a===k.K&&(k.K=null),k.J.removeCueRange(a.tV.id),g.JM(a.Sl),g.d2(k.cards,a),k.m7(),C_(k)},MtK=function(k,a,y,q){this.value=k;
this.target=a;this.showLinkIcon=y;this.K=q},W89=function(k){k.X.stop();
k.isCollapsed&&(g.I1(k.XR(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),k.isCollapsed=!1,k.K&&k.K.removeAttribute("aria-hidden"),g.aa(k.D,!1),g.aa(k.j,!0))},v1r=function(k,a){function y(H){var B=k.loadNumber;
k.X=null;k.loaded&&k.loadNumber===B&&k.player.getVideoData().videoId===q&&(H=g.PF(H)&&H.responseXML?H.responseXML:null)&&(CsV(k,H),g.C7(k.player.getRootNode(),"iv-module-loaded"))}
var q=a.videoId;g.HA()&&(y=QqG(k,y));var e={format:"XML",onFinish:y,onError:function(){k.X=null},
urlParams:{}};a.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=k.player.Z().Ij.get(q);f&&(Math.random()<g.Ht(k.player.Z().experiments,"annotation_module_vast_cards_load_logging_fraction")&&g.vn(new g.s_("Unexpected call to loadVastInfoCards; VastInfoCard exists.")),Zn9(e,f));f=f&&(f.B3||f.tP);if(!a.iq||f)a.sY?(Math.random()<g.Ht(k.player.Z().experiments,"annotation_module_vast_cards_load_logging_fraction")&&g.vn(new g.s_("Unexpected call to loadVastInfoCards; Attempting to load annotations via invideo URL.")),
Nir(k,a.sY,e)):(k.G=function(){if(!k.V)k.onVideoDataChange(e);var H=k.player.getVideoData();(H==null?0:g.Iy(H))&&!k.Kw&&uU9(k,H)},k.player.addEventListener("videodatachange",k.G))},FuG=function(k){if(!k.metaInfo||k.metaInfo.length===0)return"";
var a=[];k=g.A(k.metaInfo);for(var y=k.next();!y.done;y=k.next())a.push(Ik("li","",y.value));return{C:"ul",T:"iv-card-meta-info",S:a}},Tia=function(k){g.C.call(this);
this.D=k||window;this.K=[]},yZX=function(k,a){k.aj.LD?(a=new uP([0,
k.D.scrollTop],[0,a.Sl.offsetTop],600,n1d),k.context.j.listen(a,"animate",function(y){k.D.scrollTop=y.y}),k.context.j.listen(a,"finish",function(y){k.D.scrollTop=y.y}),a.play()):(k.aj.h3(!0),k.D.scrollTop=a.Sl.offsetTop,k.aj.h3(!1))},bna=function(k,a){switch(a.type){case "simple":k=k.Lw;
var y=a.displayDomain?{C:"div",T:"iv-card-image-text",Dq:a.displayDomain}:void 0;var q=fjX(a);y={C:"div",nw:["iv-card"],S:[{C:"a",T:"iv-click-target",U:{href:a.url?ok(a.url)||"":""},S:[H3(a.imageUrl,y),{C:"div",T:"iv-card-content",S:[Ik("h2",void 0,a.title),q]}]}]};y=new g.u(y);zd(k,g.nJ("iv-click-target",y.element),a,a.url);a=y;break;case "collaborator":k=k.Lw;y={C:"div",nw:["iv-card","iv-card-channel"],S:[{C:"a",nw:["iv-click-target"],U:{href:ok(a.url)||"","data-ytid":a.channelId},S:[H3(a.profileImageUrl),
{C:"div",T:"iv-card-content",S:[Xs9(a),{C:"h2",T:"iv-card-primary-link",Dq:a.title},FuG(a)]}]}]};y=new g.u(y);zd(k,g.nJ("iv-click-target",y.element),a,a.url);a=y;break;case "playlist":k=k.Lw;y={C:"div",nw:["iv-card","iv-card-playlist"],S:[{C:"a",T:"iv-click-target",U:{href:ok(a.url)||""},S:[H3(a.Zw,{C:"div",T:"iv-card-image-overlay",S:[{C:"span",T:"iv-card-playlist-video-count",Dq:a.playlistVideoCount}]}),{C:"div",T:"iv-card-content",S:[Xs9(a),Ik("h2","iv-card-primary-link",a.title),FuG(a)]}]}]};
y=new g.u(y);zd(k,g.nJ("iv-click-target",y.element),a,a.url);a=y;break;case "productListing":k=k.Lw;var e=a.offers.length!=0;y=["iv-card"];q="";var f=fjX(a);e&&(y.push("iv-card-product-listing"),q="iv-card-primary-link",f=a.offers[0],e=[],f.price&&e.push({C:"div",T:"iv-card-offer-price",Dq:f.price}),f.merchant&&e.push({C:"div",T:"iv-card-offer-merchant",Dq:f.merchant}),f={C:"div",S:e});e=a.url?ok(a.url)||"":"";y={C:"div",nw:y,U:{tabindex:"0"},S:[{C:"a",nw:["iv-card-image","iv-click-target"],U:{style:"background-image: url("+
a.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{C:"div",T:"iv-card-content",S:[a.sponsored?{C:"div",T:"iv-card-sponsored",S:["Sponsored",{C:"div",T:"iv-ad-info-container",S:[{C:"div",T:"iv-ad-info",Dq:"{{adInfo}}"},{C:"div",T:"iv-ad-info-icon-container",S:[{C:"div",T:"iv-ad-info-icon"},{C:"div",T:"iv-ad-info-callout"}]}]}]}:"",{C:"a",T:"iv-click-target",U:{href:e},S:[Ik("h2",q,a.title),f]}]}]};y=new g.u(y);q=g.d9("span");g.uF(q,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
y.setContent(q,"adInfo");zd(k,g.nJ("iv-click-target",y.element),a,a.url);a=y;break;case "video":k=k.Lw;q=a.videoDuration?{C:"span",T:"iv-card-video-duration",Dq:a.videoDuration}:void 0;f=a.isLiveNow?{C:"span",nw:["yt-badge","yt-badge-live"],Dq:"LIVE NOW"}:null;e={C:"div",nw:["iv-card","iv-card-video"],S:[{C:"a",T:"iv-click-target",U:{href:((y=a.url)==null?void 0:ok(y))||""},S:[H3(a.Zw,q),{C:"div",T:"iv-card-content",S:[Xs9(a),Ik("h2","iv-card-primary-link",a.title),FuG(a),f]}]}]};y=new g.u(e);zd(k,
g.nJ("iv-click-target",y.element),a,a.url);a=y;break;default:return null}return a},zd=function(k,a,y,q){if(q){a=g.A(a);
for(var e=a.next();!e.done;e=a.next())k.K(e.value,q,y.id,y.sessionData,y.XY.click,5)}},o10=function(k,a,y,q,e){if(a.length!=2||y.length!=2)throw Error("Start and end points must be 2D");
ZN.call(this,k,a,y,q,e)},Ddr=function(k){this.J=k},Fo=function(k,a,y,q,e,f,H){k.context.K.listen(a,"click",function(B){k.Vx(y,q,e,f||[],H||0,B)});
k.context.K.listen(a,"touchstart",function(){k.Qh=!1});
k.context.K.listen(a,"touchmove",function(){k.Qh=!0})},uU9=function(k,a){var y,q;
if(a=(y=a.getWatchNextResponse())==null?void 0:(q=y.cards)==null?void 0:q.cardCollectionRenderer)k.Kw=!0,CBr(k,a),a.headerText&&k.F0&&(y=g.Nz(a.headerText),k.player.W("player_tooltip_data_title_killswitch")?k.F0.setAttribute("title",y):k.F0.setAttribute("data-tooltip-title",y))},hW2=function(k,a){return g.mu(k.action,a)},mdT=function(k,a){k.L||(k.L=g.I2(function(){AZd(this);
DuX(this)},a,k))},MnX=function(k){g.pF.call(this,k);
this.L=this.endscreen=null;this.D={};this.N={};this.X=this.j=null;this.V=[];this.K=null;this.Kw=!0;this.G=0;k=k.Z();this.aj=g.M0(k)||g.mC(k);this.events=new g.e9(this);g.U(this,this.events);this.events.Y(this.player,g.BV("creatorendscreen"),this.onCueRangeEnter);this.events.Y(this.player,g.tx("creatorendscreen"),this.onCueRangeExit);this.events.Y(this.player,"resize",this.M0);this.events.Y(window,"focus",this.aAY);this.load();var a=g.d9("STYLE");(g.Cy("HEAD")[0]||document.body).appendChild(a);this.addOnDisposeCallback(function(){g.JM(a)});
a.sheet&&(a.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),a.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},NDr=function(k){k=k.createElement({C:"div",
nw:["annotation","annotation-type-custom"]});g.aa(k,!1);return k},Xir=function(k,a){if(a.channel_name){var y=k.createElement({C:"div",
nw:["iv-branding-context-name"],Dq:a.channel_name}),q=k.createElement({C:"div",nw:["iv-branding-context-subscribe"]}),e=a.standalone_subscribe_button_data;e&&(k.K=new g.yD(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,a.channel_id,!!e.subscribed,e.feature,a.session_data.itct,k.context.J,!1),k.K.pw(q));var f=k.createElement({C:"div",nw:["iv-branding-context-subscribe-caret"]}),H=k.createElement({C:"div",nw:["branding-context-container-inner"]});H.appendChild(f);
H.appendChild(y);H.appendChild(q);g.aa(H,!1);var B=k.createElement({C:"div",nw:["branding-context-container-outer"]});B.appendChild(H);g.tO(B,"right",a.image_width+"px");g.P1(k.XR(),B);k.j=new g.gD(function(){UuX(k,H,B)},500);
g.U(k,k.j);k.context.K.listen(k.XR(),"mouseover",function(){JZ9(k,H,B,f,a.image_height)});
k.context.K.listen(k.XR(),"mouseout",function(){k.j.start()})}},yV=function(k,a){g.C.call(this);
var y=this;this.element=k;this.context=a;this.Qh=!1;this.ge=new Map;this.hG=new Map;this.context.J.addEventListener(g.BV("annotations_module"),function(q){(q=y.ge.get(q))&&q.apply(y)});
this.context.J.addEventListener(g.tx("annotations_module"),function(q){(q=y.hG.get(q))&&q.apply(y)})},rZX=function(k,a,y){if(a.targetUrl&&(!y||y.type!=="keypress"||y.keyCode===13)){for(var q=y.target;q&&!g.zO(q,"ytp-ce-element");){g.zO(q,"subscribe-label")&&K8T(k,a);
if(g.zO(q,"ytp-ce-channel-subscribe"))return;q=q.parentElement||null}if(!q||g.zO(q,"ytp-ce-element-hover")){y.preventDefault();y.stopPropagation();if(q=k.D[a.id])YlT(k,q,a),q.element.blur();if(y.ctrlKey||y.metaKey||a.PIj==="new")K8T(k,a),k.player.sendVideoStatsEngageEvent(17,void 0),k.player.pauseVideo(),y=g.sd(EE(k,a.targetUrl)),y=g.OT(y),g.nW(y,void 0,a.sessionData);else{var e=g.ry(k.player.Z())||k.player.getVideoData().SR,f=function(){var H=EE(k,a.targetUrl),B=a.sessionData,Z=a.watchEndpoint,z=
g.UJ(H);e&&z&&(z.v||z.list)?k.player.QQ(z.v,B,z.list,!1,void 0,Z||void 0):g.WQl(H,B)};
K8T(k,a,function(){k.player.sendVideoStatsEngageEvent(17,f)})}}}},F89=function(k,a){this.merchant=k;
this.price=a},B3=function(k){k.j&&(k.Zq.hide(),g.Eu(k.sY),g.MF(k.context.J.getRootNode(),g.w8.IV_DRAWER_OPEN),k.j=!1,n_(k.J),k.N&&k.N.stop(),k.N=new g.gD(function(){k.NE&&(k.NE.focus(),k.NE=null)},330),k.N.start())},Nir=function(k,a,y){k.V=!0;
k.X=g.nT(a,y)},CBr=function(k,a){var y=!1;
k.K||(k.K=vA0(k),g.U(k,k.K));for(var q=g.A(a.cards||[]),e=q.next();!e.done;e=q.next())e=e.value,e.cardRenderer&&(muV(k.K,e.cardRenderer),y=!0);if(y){var f;(f=k.player.getVideoData())!=null&&g.Iy(f)||(y=k.K,q=a.headerText?g.Nz(a.headerText):"",g.uF(y.ub,q),y.X&&(y.J.W("player_tooltip_data_title_killswitch")?y.X.setAttribute("title",q):y.X.setAttribute("data-tooltip-title",q)),y.context.videoData.eventId&&(y.eventId=y.context.videoData.eventId),y.cz=a.trackingParams?g.Kr(a.trackingParams):null,y.V=
a.closeButton.infoCardIconRenderer.trackingParams?g.Kr(a.closeButton.infoCardIconRenderer.trackingParams):null,y.Ei=a.icon.infoCardIconRenderer.trackingParams?g.Kr(a.icon.infoCardIconRenderer.trackingParams):null,k.xl());n_(k.player)}},cZr=function(k,a){var y=y===void 0?0:y;
var q=UdV(a).width;g.DW(a,q);y=new o10(a,[q,a.offsetTop],[q-q-y,a.offsetTop],200,inT);g.U(k,y);k.context.j.listen(y,"begin",function(){g.aa(a,!0)});
y.play()},QqG=function(k,a){return function(){var y=g.Nf.apply(0,arguments);
k.xs()||k.vz.push(g.Tw.Hi(function(){a.apply(null,g.ls(y))}))}},g1K=function(k){g.LA(k.XR(),[g.w8.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.ED(k.J,k.L,5);k.KL();k.X=g.Pn("ytp-cards-button",k.J.getRootNode());k.au=g.Pn("iv-drawer-close-button",k.L);k.isInitialized=!0};
g.vg.prototype.FP=g.$g(39,function(k,a){var y=g.fE(this.ew());y&&y.FP(k,a)});
var sE={},gt=null;g.gb(uP,g.LK);g.S=uP.prototype;g.S.getDuration=function(){return this.duration};
g.S.play=function(k){if(k||this.K==0)this.progress=0,this.coords=this.D;else if(this.isPlaying())return!1;bP(this);this.startTime=k=g.nj();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.L=this.startTime;this.progress||this.wA();this.Wt("play");this.isPaused()&&this.Wt("resume");this.K=1;var a=g.v7(this);a in sE||(sE[a]=this);iBr();r3d(this,k);return!0};
g.S.stop=function(k){bP(this);this.K=0;k&&(this.progress=1);Y5d(this,this.progress);this.onStop();this.LN()};
g.S.pause=function(){this.isPlaying()&&(bP(this),this.K=-1,this.Wt("pause"))};
g.S.uj=function(){this.K==0||this.stop(!1);this.Wt("destroy");uP.yX.uj.call(this)};
g.S.destroy=function(){this.dispose()};
g.S.Yi=function(){this.Wt("animate")};
g.S.Wt=function(k){this.dispatchEvent(new $uX(k,this))};
g.gb($uX,g.YG);g.gb(ZN,uP);ZN.prototype.j=function(){};
ZN.prototype.Yi=function(){this.j();ZN.yX.Yi.call(this)};
ZN.prototype.LN=function(){this.j();ZN.yX.LN.call(this)};
ZN.prototype.wA=function(){this.j();ZN.yX.wA.call(this)};
g.gb(o10,ZN);o10.prototype.j=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.I(Tia,g.C);g.S=Tia.prototype;g.S.listen=function(k,a,y,q){y=(0,g.nc)(y,q||this.D);k=g.oA(k,a,y);this.K.push(k);return k};
g.S.YV=function(k,a,y,q){y=(0,g.nc)(y,q||this.D);k=Ga9(k,a,y);this.K.push(k);return k};
g.S.xp=function(k){g.ew(k);g.d2(this.K,k)};
g.S.removeAll=function(){g.ew(this.K);this.K.length=0};
g.S.uj=function(){this.removeAll();g.C.prototype.uj.call(this)};g.I(MnX,g.pF);g.S=MnX.prototype;g.S.load=function(){g.pF.prototype.load.call(this);if(!fd(this)){var k=g.ZkD(this.player.getVideoData());k?(k=Rs9(k,Gt9(this)),k$(this,k,!1)):ljX(this)}};
g.S.unload=function(){k$(this,null);this.L&&(this.L.abort(),this.L=null);g.pF.prototype.unload.call(this)};
g.S.S2=function(k,a){return fd(this)?k==="loadCustomEndscreenRenderer"?(k=Rs9(a,"new"),k$(this,k),!0):null:null};
g.S.getOptions=function(){return fd(this)?["loadCustomEndscreenRenderer"]:[]};
g.S.M0=function(){if(this.endscreen&&this.endscreen.elements){var k=this.player.getVideoContentRect();if(k&&k.width!==0&&k.height!==0){var a=this.player.getPlayerSize();if(a&&a.width!==0&&a.height!==0){var y=k.width/k.height;var q=0;for(var e=-1,f=0;f<LuK.length;f++){var H=Math.abs(a.width-LuK[f]);if(e===-1||q>=H)e=f,q=H}q=Ijr[e];this.j&&g.tO(this.j.element,"outline-width",Math.max(a.width,a.height)+"px");for(a=0;a<this.endscreen.elements.length;++a)if(f=this.endscreen.elements[a].id,e=this.D[f],
H=this.N[f],e&&H){var B=H.width*y/H.aspectRatio,Z=Math.round(H.width*k.width);f=Math.round(B*k.height);var z=k.left+Math.round(H.left*k.width),Y=k.top+Math.round(H.top*k.height);g.SA(e.element,Z,f);g.DW(e.element,z,Y);g.I1(e.element,tn9);Z>256||f>256?g.C7(e.element,"ytp-ce-large-round"):Z>96||f>96?g.C7(e.element,"ytp-ce-medium-round"):g.C7(e.element,"ytp-ce-small-round");g.I1(e.element,E10);Z=H.left+H.width/2;H=H.top+B/2;g.C7(e.element,Z<=.5&&H<=.5?"ytp-ce-top-left-quad":Z>.5&&H<=.5?"ytp-ce-top-right-quad":
Z<=.5&&H>.5?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.I1(e.element,Ijr);g.C7(e.element,q);(e=g.Ys(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.tO(e,"height",f+"px")}}}}};
g.S.onCueRangeEnter=function(k){if(this.endscreen)if(k.getId()==="ytp-ce-in-endscreen")K_(this,this.endscreen.impressionUrls),(k=g.Yv())&&this.endscreen.visualElement&&g.uQ(k,this.endscreen.visualElement),this.K&&(g.C7(this.K,"ytp-ce-element-show"),this.K.removeAttribute("aria-hidden"),this.player.Lv()?g.C7(this.K,"ytp-ce-hide-button-lower"):g.MF(this.K,"ytp-ce-hide-button-lower"));else{k=k.getId().substring(15);var a=this.D[k],y=this.N[k];g.C7(a.element,"ytp-ce-element-show");a.element.removeAttribute("aria-hidden");
a=this.player.getRootNode();g.C7(a,"ytp-ce-shown");K_(this,y.impressionUrls);(a=g.Yv())&&g.uQ(a,y.visualElement);this.player.Z().V&&this.player.qE("endscreenelementshown",k)}};
g.S.onCueRangeExit=function(k){if(k.getId()==="ytp-ce-in-endscreen")this.K&&(g.MF(this.K,"ytp-ce-element-show"),this.K.setAttribute("aria-hidden","true"));else{k=k.getId().substring(15);var a=this.D[k];g.MF(a.element,"ytp-ce-element-show");a.element.setAttribute("aria-hidden","true");a=this.player.getRootNode();g.MF(a,"ytp-ce-shown");this.player.Z().V&&this.player.qE("endscreenelementhidden",k)}};
g.S.aAY=function(k){var a=this;k.target===window&&(new g.gD(function(){for(var y=g.A(Object.values(a.D)),q=y.next();!q.done;q=y.next())g.I1(q.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.S.h3=function(k){for(var a=g.A(Object.values(this.D)),y=a.next();!y.done;y=a.next())y=y.value,k?y.element.setAttribute("hidden",""):y.element.removeAttribute("hidden")};
g.S.mfZ=function(k){this.K&&this.player.getRootNode().removeChild(this.K);k&&(g.C7(k,"ytp-ce-hide-button-container"),this.K=k,g.ED(this.player,this.K,4))};
var LuK=[346,426,470,506,570,640,853,1280,1920],Ijr="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),E10=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],tn9=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var hsT={He3:"current",nP3:"new"};var pid={CLOSE:"close",sIZ:"openUrl",SUBSCRIBE:"subscribe"},PBr={oX5:"click",CLOSE:"close",gWw:"hidden",RMF:"rollOut",GUq:"rollOver",qPE:"shown"};J3r.prototype.oY=function(){var k=hW2(this,function(a){return a.type==="openUrl"&&a.url!=null});
return k?k.url:null};
var ps9={TMj:"anchored",sC:"branding",CHANNEL:"channel",U8z:"cta",qRe:"highlightText",RT5:"label",PLAYLIST:"playlist",POPUP:"popup",Q7s:"speech",SUBSCRIBE:"subscribe",CJG:"title",VIDEO:"video",OQj:"website"},A30={sC:"branding",jne:"card",SQZ:"drawer",EWz:"highlight",b8F:"marker",OYh:"promotion",TEXT:"text",xuE:"widget"};var OBG=[".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}"],
QO9=[".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}"];g.I(yV,g.C);g.S=yV.prototype;g.S.addCueRange=function(k,a,y,q,e){k=new g.Uc(k,a,{id:y,namespace:"annotations_module"});q&&this.ge.set(k,q);e&&this.hG.set(k,e);this.context.J.RY([k],1)};
g.S.xC=function(){this.context.D.subscribe("resize",this.m7,this)};
g.S.XR=function(){return this.element};
g.S.Vx=function(k,a,y,q,e,f){if(this.Qh)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(k,y,q,e);return!1};
g.S.show=function(){};
g.S.hide=function(){};
g.S.destroy=function(){g.JM(this.XR())};
g.S.m7=function(){};
g.S.navigate=function(k,a,y,q){var e=this,f=ok(k);if(f){var H=EAV(f,k.target),B=function(){k.K&&e.context.J.pauseVideo();var Z=e.context.videoData.SR||!1,z=g.UJ(f||"");Z&&z&&(z.v||z.list)?e.context.J.QQ(z.v,a,z.list,!1):g.nW(f||"",H==="current"?"_top":void 0,a)};
H==="new"&&(B(),B=null);Nq(this.context.logger,y,B,q);ttT(f)||(y=g.Yv(),q=a.itct,y&&q&&g.vP(y,g.Kr(q)))}};
g.S.uj=function(){this.ge.clear();this.hG.clear();g.C.prototype.uj.call(this)};
g.S.createElement=function(k){k=new g.u(k);g.U(this,k);return k.element};g.I(RW9,yV);g.S=RW9.prototype;g.S.zC=function(){this.vz&&L_(this,this.vz)};
g.S.isAvailable=function(){var k;if(k=!!this.cards.length)(k=this.J.getRootNode())?(k=g.J1(k),k=173<k.width&&173<k.height):k=!1;return k};
g.S.m7=function(){var k=this.isAvailable();g.aa(this.XR(),k);g.iM(this.context.J.getRootNode(),g.w8.IV_DRAWER_ENABLED,k);n_(this.J)};
g.S.destroy=function(){this.J.FP(!1);try{this.J.getRootNode().removeChild(this.L)}catch(k){}g.pu(this.Kw);g.Eu(this.sY);this.tG&&this.tG.dispose();this.N&&this.N.dispose();yV.prototype.destroy.call(this)};
g.S.KL=function(){var k=this;this.context.K.listen(g.Pn("iv-drawer-close-button",this.L),"click",this.vg,this);this.context.K.listen(this.D,"touchend",function(){k.JG.start()});
this.context.K.listen(this.D,"scroll",this.RK,this);this.context.D.subscribe("onHideControls",function(){k.Ij=!0});
this.context.D.subscribe("onShowControls",function(){k.Ij=!1});
this.context.D.subscribe("onVideoAreaChange",function(){k.Ij=g.zO(k.J.getRootNode(),"ytp-autohide")});
this.Kw.push(g.J7("iv-button-shown",this.mEY,this));this.Kw.push(g.J7("iv-button-hidden",this.dEs,this));c3X(this)};
g.S.findLastIndex=function(k){if(this.cards.length===0)return 0;var a=g.YL(this.cards,function(y){return k.tV.startMs>y.tV.startMs||k.tV.startMs===y.tV.startMs&&k.tV.timestamp>=y.tV.timestamp?!0:!1});
return a===-1?0:a+1};
g.S.vg=function(){if(this.j){Nq(this.context.logger,Je(this).XY.close);var k=g.Yv();k&&this.V&&g.vP(k,this.V);B3(this)}};
g.S.RK=function(){g.iM(this.L,"iv-drawer-scrolled",this.D.scrollTop>0)};
g.S.mEY=function(){var k=g.Yv(),a=Je(this);a=a?a.Ei:this.Ei;k&&a&&g.KO(k,[a])};
g.S.dEs=function(){var k=g.Yv(),a=Je(this);a=a?a.Ei:this.Ei;k&&a&&g.Mp(k,[a])};
g.S.Dx=function(){var k=Je(this);Nq(this.context.logger,k.XY.vZ);var a=g.Yv();if(a&&k)if(this.J.W("web_infocards_teaser_show_logging_fix")){var y=[];k.SQ&&y.push(k.SQ);k.Ei&&y.push(k.Ei);y.length>0&&g.KO(a,y)}else g.KO(a,[k.SQ,k.Ei])};
g.S.xEY=function(){var k=g.Yv(),a=Je(this);k&&a&&g.Mp(k,[a.SQ])};
g.S.va=function(k){var a=Je(this),y=g.Yv();this.K?k?(k=this.context.logger,Nq(k,a.XY.Qm),k.J.sendVideoStatsEngageEvent(4,void 0),y&&a.SQ&&g.vP(y,a.SQ)):(k=this.context.logger,Nq(k,a.XY.Qm),k.J.sendVideoStatsEngageEvent(4,void 0),y&&a.Ei&&g.vP(y,a.Ei)):(k=this.context.logger,Nq(k,a.XY.Qm),k.J.sendVideoStatsEngageEvent(4,void 0),y&&this.Ei&&g.vP(y,this.Ei))};g.I(am,yV);am.prototype.xC=function(){yV.prototype.xC.call(this);L8a(this)};
am.prototype.show=function(){yV.prototype.show.call(this);var k=g.Yv(),a=this.annotation.data;k&&a&&(a=a.session_data)&&g.KO(k,[g.Kr(a.itct)])};
am.prototype.hide=function(){yV.prototype.hide.call(this);var k=g.Yv(),a=this.annotation.data;k&&a&&(a=a.session_data)&&g.Mp(k,[g.Kr(a.itct)])};g.I(Mq,am);
Mq.prototype.show=function(){if(!this.isActive){am.prototype.show.call(this);if(!this.G){g.C7(this.XR(),"iv-branding");var k=this.annotation.data;this.D=this.createElement({C:"img",nw:["branding-img","iv-click-target"],U:{"aria-label":"Channel watermark",src:k.image_url,width:k.image_width,height:k.image_height}});g.aa(this.D,!1);var a=this.createElement({C:"button",nw:["branding-img-container","ytp-button"]});a.appendChild(this.D);this.XR().appendChild(a);var y=this.annotation.oY();y&&Fo(this,a,
y,this.annotation.id,k.session_data);this.context.J.W("disable_branding_context")||Xir(this,k);this.G=!0}g.aa(this.XR(),!0);this.isActive=!0;if(this.D){try{cZr(this,this.D)}catch(q){}g.C7(this.context.J.getRootNode(),"ytp-branding-shown");this.context.J.getRootNode().style.setProperty("--branding-image-width",this.D.getAttribute("width")+"px")}}};
Mq.prototype.hide=function(){this.isActive&&(am.prototype.hide.call(this),g.aa(this.XR(),!1),this.isActive=!1,g.MF(this.context.J.getRootNode(),"ytp-branding-shown"))};
Mq.prototype.destroy=function(){this.K&&(this.K.dispose(),this.K=null);g.MF(this.context.J.getRootNode(),"ytp-branding-shown");am.prototype.destroy.call(this)};g.I(uLa,am);g.S=uLa.prototype;g.S.show=function(){this.isActive||(am.prototype.show.call(this),this.aj||(bB9(this),this.aj=!0),g.aa(this.XR(),!0),g.I2(function(){g.MF(this.XR(),"iv-promo-inactive")},100,this),this.XR().removeAttribute("aria-hidden"),this.isActive=!0,AZd(this),W89(this),mdT(this,this.N))};
g.S.hide=function(){this.isActive&&(g.C7(this.XR(),"iv-promo-inactive"),this.isActive=!1,this.XR().setAttribute("aria-hidden","true"))};
g.S.Vx=function(k,a,y,q,e,f){return this.isCollapsed?!1:am.prototype.Vx.call(this,k,a,y,q,e,f)};
g.S.wp=function(k){this.V=!0;TDK(this,500,k)};
g.S.iy=function(){this.V=!1;DuX(this)};
g.S.vE=function(k){k.stopPropagation();this.hide()};
g.S.Dy=function(k){k.stopPropagation();AZd(this);this.isCollapsed=!0;g.C7(this.XR(),"iv-promo-collapsed-no-delay");this.X.start()};
g.S.destroy=function(){this.X.dispose();am.prototype.destroy.call(this)};g.I(wsr,g.pF);g.S=wsr.prototype;g.S.S2=function(k,a){if(!zWK(this.player.Z().playerStyle))return null;switch(k){case "loadCustomAnnotationsXml":return(k=g.uf(a))&&CsV(this,k),!0;case "removeCustomAnnotationById":return a&&this.K&&(sq9(this.K,a),n_(this.player)),!0}return null};
g.S.getOptions=function(){return zWK(this.player.Z().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.S.EF=function(){var k=this.player.Z(),a=this.player.getVideoData(),y=k.annotationsLoadPolicy||a.annotationsLoadPolicy;return a.SR||this.player.isMutedByEmbedsMutedAutoplay()?!1:y===1&&!a.h1||k.Ij.get(a.videoId)||g.or(a)||g.zb4(a)?!0:!1};
g.S.xl=function(){if(this.j){var k=this.player.yh().getVideoContentRect(!0);g.SA(this.j.element,k.width,k.height);g.DW(this.j.element,k.left,k.top)}if(this.K){var a=this.player.TC();k=this.K;a=a.width;g.iM(k.L,"iv-drawer-small",a<=426);g.iM(k.L,"iv-drawer-big",a>=1280)}};
g.S.ue=function(k){xu9(this,k.state);g.h(k.state,2)&&(this.Lv()&&this.tN()&&this.player.getPresentingPlayerType()!==2&&this.gH(!1),this.FP(!1))};
g.S.load=function(){g.pF.prototype.load.call(this);xu9(this,this.player.getPlayerStateObject());this.loadNumber++;var k=this.player.getVideoData();v1r(this,k);g.ED(this.player,this.j.element,4);this.xl();var a=g.or(k);a&&CBr(this,a);if((a=g.zb4(k))&&a.featuredChannel){var y=a.featuredChannel;a=a.annotationId||"branding";var q=k.videoId||null,e=k.eventId||null;if(!this.player.Z().rJ){var f=[];y.navigationEndpoint&&g.v(y.navigationEndpoint,g.xn)&&g.v(y.navigationEndpoint,g.xn).browseId&&f.push(new ajG("openUrl",
"click",new MtK("/channel/"+g.v(y.navigationEndpoint,g.xn).browseId,"new",!0,!0)));var H=y.watermark.thumbnails[0];q={channel_name:y.channelName,end_ms:y.endTimeMs,image_height:H.height,image_type:1,image_url:H.url,image_width:H.width,is_mobile:!1,session_data:{annotation_id:a,ei:e,feature:"iv",itct:y.trackingParams,src_vid:q},start_ms:y.startTimeMs};if(y.subscribeButton&&g.v(y.subscribeButton,g.hx)){q.channel_id=g.v(y.subscribeButton,g.hx).channelId;var B;y=g.v(y.subscribeButton,g.hx);H=e=null;y.subscribed?
(y.subscriberCountWithUnsubscribeText&&(e=g.Nz(y.subscriberCountWithUnsubscribeText)),y.subscriberCountText&&(H=g.Nz(y.subscriberCountText))):(y.subscriberCountText&&(e=g.Nz(y.subscriberCountText)),y.subscriberCountWithSubscribeText&&(H=g.Nz(y.subscriberCountWithSubscribeText)));var Z,z=((Z=g.v((B=y.signInEndpoint)==null?void 0:B.commandMetadata,g.Uw))==null?void 0:Z.url)||"";B={subscribeText:g.Nz(y.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.Nz(y.subscribedButtonText),unsubscribeCount:H||
"",enabled:y.enabled||!1,classic:!1,subscribed:y.subscribed||!1,feature:"iv",signInUrl:z};q.standalone_subscribe_button_data=B}B=new J3r(a,"branding","branding",f,q);Z=NDr(this);this.player.W("web_player_overlay_positioned_layout")?(Z.setAttribute("data-overlay-order","11"),this.player.xH(Z,4,!0)):this.D.element.appendChild(Z);B=new Mq(Z,Xo(this),B);B.xC();g.U(B,B);this.N[a]=B}}this.F0=g.Pn("ytp-cards-button",this.player.getRootNode());g.Iy(k)&&uU9(this,k)};
g.S.onVideoDataChange=function(k){var a=this.player.getVideoData();a.sY&&Nir(this,a.sY,k)};
g.S.unload=function(){this.player.J_("annotations_module");for(var k=g.A(Object.keys(this.N)),a=k.next();!a.done;a=k.next())this.N[a.value].destroy();this.aj=null;this.K&&(this.K.destroy(),this.K=null,n_(this.player));this.V=!1;this.X&&(this.X.abort(),this.X=null);this.Kw=!1;this.N={};this.D.hide();g.pF.prototype.unload.call(this);this.j.detach();this.G&&(this.player.removeEventListener("videodatachange",this.G),this.G=null)};
g.S.If=function(k){k===this.player.getVideoData().videoId&&(this.loaded?wia(this):this.load())};
g.S.Lv=function(){var k;return((k=this.K)==null?void 0:k.isAvailable())||this.Kw};
g.S.tN=function(){return!!this.K&&this.K.j};
g.S.gH=function(k,a,y){a=a===void 0?!1:a;this.Lv();this.K&&(k?y?d$(this.K,y,a):d$(this.K,"YOUTUBE_DRAWER_AUTO_OPEN",a):B3(this.K))};
g.S.FP=function(k,a){this.player.publish(k?"cardsteasershow":"cardsteaserhide",a)};
g.S.uj=function(){this.player.Z().Ij.unsubscribe("vast_info_card_add",this.If,this);g.MF(this.player.getRootNode(),g.w8.IV_DRAWER_OPEN);for(var k=this.vz,a=g.Tw,y=0,q=k.length;y<q;y++)a.iX(k[y]);this.vz.length=0;g.pF.prototype.uj.call(this)};
g.S.createElement=function(k){k=new g.u(k);g.U(this,k);return k.element};g.ht("annotations_module",wsr);g.ht("creatorendscreen",MnX);})(_yt_player);
