(function(g){var window=this;'use strict';var W3=function(k,a,y){k.loaded&&k.unload();y!=null&&(k.V=y,k.V&&(g.ry(k.B)?Y$(k,!!a):r$(k,!!a)));a!==null||jE(k,!0)||k.HA(a,!!a,k.V?"m":"s");k.D=a;jE(k)&&(k.D=iT(k));var q;a2a(k,(q=k.D)!=null?q:void 0);k.load()},q_a=function(k,a,y){k.K||(k.K=new yn9);
k=k.K.j(a,y);Math.random()<.01&&g.vn(Error("Deprecated subtitles format in web player: WebVTT"));return k},mt=function(k){k.isActive()||k.start()},eLX=function(k,a){return a?k.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},f20=function(){this.timestamp=this.K=0},dfa=function(k,a,y){k.cz=k.cz||!!y;
var q={};Object.assign(q,k.K.bY);Object.assign(q,y||a.K);Object.assign(q,k.FR.bY);(y=!k.G)&&$fr(k);for(var e=k.NE&&k.Ij&&g.dy(q,k.Ij)?k.NE:HM1(k,q),f=typeof a.text==="string",H=f?a.text.split("\n"):[a.text],B=0;B<H.length;B++){var Z=B>0||!a.append,z=H[B];Z&&!y?($fr(k),e=HM1(k,q)):Z&&y&&(y=!1);z&&(e.appendChild(f?g.m_(z):z),f||z.tagName!=="RUBY"||z.childElementCount!==4||g.Wt||!g.X1(z.children[2],"text-emphasis")||(Z=k.j?"padding-right":"padding-top",g.X1(z.children[2],"text-emphasis-position")&&(Z=
k.j?"padding-left":"padding-bottom"),g.Qk?g.tO(e,Z,"1em"):g.tO(e,Z,"0.5em")))}k.Ij=q;k.NE=e;k.N.push(a)},HM1=function(k,a){var y=g.d9("SPAN");
g.tO(y,{display:"inline-block","white-space":"pre-wrap"});g.tO(y,Bzr(k,a));y.classList.add("ytp-caption-segment");k.G.appendChild(y);y.previousElementSibling&&(g.tO(y.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.tO(y,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return y},ZM0=function(k,a){var y=g.oT(k.segments,a);
y>=0||y<0&&(-y-1)%2===1||(y=-y-1,y>0&&a-k.segments[y-1]===1&&y<k.segments.length&&k.segments[y]-a===1?(g.sT(k.segments,y),g.sT(k.segments,y-1)):y>0&&a-k.segments[y-1]===1?k.segments[y-1]=a:y<k.segments.length&&k.segments[y]-a===1?k.segments[y]=a:(g.fm(k.segments,y,0,a),g.fm(k.segments,y+1,0,a)))},zLd=function(k,a,y,q){var e=a/360*16;
a>=k&&(k=640,q>y*1.3&&(k=480),e=y/k*16);return e},Td=function(k,a){if(!k.K)return null;
if(k.aj&&k.aj.L)return k.aj.L;a=Y_9(k,a);a=g.nF(k.K.D,a);var y=null;if(rnT(k.B)){var q=k.J.isInline()?void 0:g.bN("yt-player-caption-sticky-language");for(var e=[q,k.videoData.captionsLanguagePreference,k.B.captionsLanguagePreference,g.Ym(k.videoData,"yt:cc_default_lang")],f=!1,H=0;H<e.length;H++){var B=e[H];if(B){f=!0;for(var Z=0;Z<a.length;Z++)if(g.hW(a[Z])===B)return a[Z];for(Z=0;Z<a.length;Z++)if(g.hW(a[Z]).split("-")[0]===B.split("-")[0])return a[Z]}}if(f&&k.K&&(e=k.K.X,e.length))for(e=g.A(e),
f=e.next();!f.done;f=e.next())if(f=f.value,f.languageCode===q){y=f;break}}else for(q=[k.videoData.captionsLanguagePreference,k.B.captionsLanguagePreference,g.Ym(k.videoData,"yt:cc_default_lang")],e=0;e<q.length;e++)for(f=0;f<a.length;f++)if(g.hW(a[f])===q[e])return a[f];q=null;k.aj&&k.aj.j&&(q=k.aj.j);q||(q=a.find(function(z){return z.isDefault})||null);
q||(q=a[0]||iT(k));q&&y&&g.hW(q).split("-")[0]!==y.languageCode.split("-")[0]&&(q=jMX(q,y));return q},iM9=function(k,a){if(k.policy.l8&&k.player.VL()){var y=g.tj(a,k.policy,{});
y.set("pot",k.player.VL());y=y.oY()}else y=g.tj(a,k.policy,{}).oY();var q={format:"RAW",withCredentials:!0};if(k.policy.Ij){q.method="POST";var e=a.L;e&&Object.keys(e).length>0?q.postBody=g.Jr(e,g.Gh):q.postBody=(0,g.YK)([120,0])}k.X&&(q.responseType="arraybuffer");var f=++k.vz,H=(0,g.Bi)();k.D=g.CN(y,q,3,100,-1,function(B){B.errorCode==="net.timeout"&&k.player.lj("capnt",{rn:f++})}).then(function(B){if(k.policy.oH&&f%100===1){var Z=(0,g.Bi)();
k.player.lj("caprsp",{rn:f,ms:Z-H,kb:(B.xhr.responseText.length/1024).toFixed()})}a:{B=B.xhr;k.xs();if(k.j){var z=!(k.X?B.response:B.responseText)||B.status>=400;if(Z=g.UUD(B)){B=g.tj(k.j,k.policy,{});k.j.mV(B,Z);iM9(k,k.j);break a}if(z)k.player.lj("capfail",{status:B.status});else{var Y;g.UK("fcb_r",(0,g.Bi)(),((Y=k.player.getVideoData())==null?void 0:Y.Kw)||"");Y=k.j.S3[0];Z=Y.Wz;k.V!=null&&k.N!==Z&&(k.X?k.V(B.response,(Y.startTime+k.player.Yk())*1E3):k.V(B.responseText,(Y.startTime+k.player.Yk())*
1E3),k.N=Z)}}k.j=null;k.D=null}}).Bd(function(B){k.j=null;
k.D=null;var Z;k.player.lj("capfail",{rn:f,status:(Z=B.xhr)==null?void 0:Z.status})});
k.j=a;ZM0(k.L,k.j.S3[0].Wz)},Tz9=function(k){if(!WaT.test(k))throw Error("'"+k+"' is not a valid hex color");
k.length==4&&(k=k.replace(mfr,"#$1$1$2$2$3$3"));k=k.toLowerCase();k=parseInt(k.slice(1),16);return[k>>16,k>>8&255,k&255]},S_d=function(k,a,y){y=y===void 0?!1:y;
var q=SE.bY;k.j={};Object.assign(k.j,SE);k.j.bY={};Object.assign(k.j.bY,q);k.N={bY:{}};var e=a.backgroundOverride?k.N:k.j,f=a.background||q.background;UM.test(f);e.bY.background=f;e=a.colorOverride?k.N:k.j;f=a.color||q.color;UM.test(f);e.bY.color=f;e=a.windowColorOverride?k.N:k.j;f=a.windowColor||SE.windowColor;UM.test(f);e.windowColor=f;e=a.backgroundOpacityOverride?k.N:k.j;f=a.backgroundOpacity;f==null&&(f=q.backgroundOpacity);e.bY.backgroundOpacity=f;e=a.fontSizeIncrementOverride?k.N:k.j;f=a.fontSizeIncrement;
f==null&&(f=q.fontSizeIncrement);e.bY.fontSizeIncrement=f;f=a.fontStyleOverride?k.N:k.j;e=a.fontStyle;e==null&&(e=q.bold&&q.italic?3:q.bold?1:q.italic?2:0);f=f.bY;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=a.textOpacityOverride?k.N:k.j;f=a.textOpacity;f==null&&(f=q.textOpacity);e.bY.textOpacity=f;e=a.windowOpacityOverride?k.N:k.j;f=a.windowOpacity;f==null&&(f=SE.windowOpacity);e.windowOpacity=
f;e=a.charEdgeStyleOverride?k.N:k.j;f=a.charEdgeStyle;f==null&&(f=q.charEdgeStyle);e.bY.charEdgeStyle=f;e=a.fontFamilyOverride?k.N:k.j;f=a.fontFamily;f==null&&(f=q.fontFamily);e.bY.fontFamily=f;k.loaded&&k.h9();y&&g.Zz("yt-player-caption-display-settings",a,2592E3)},Ufd=function(k){k.style.set(1);
k.K=k.L;k.K.K=0;k.K.style=k.style;k.j.mode=1<<k.K.L},Dfr=function(k,a){var y="vertical-rl";
k.K.oL===1&&(y="vertical-lr");g.oB&&(y=y==="vertical-lr"?"tb-lr":"tb-rl");g.tO(a,"-o-writing-mode",y);g.tO(a,"-webkit-writing-mode",y);g.tO(a,"writing-mode",y);g.tO(a,"text-orientation","upright");g.C7(a,"ytp-vertical-caption");k.D.params.Vt===3&&(g.tO(a,"text-orientation",""),g.tO(a,"transform","rotate(180deg)"))},DN=function(k,a){k=k.getAttribute(a);
if(k!=null)return Number(k)},QV=function(k){this.X=k;
this.j=[];this.K=this.D=this.row=0;this.style=new OM;for(k=this.L=0;k<=15;k++){this.j[k]=[];for(var a=0;a<=32;a++)this.j[k][a]=new f20}},w$=function(k,a,y){this.trackData=k;
this.N=y;this.version=this.X=this.j=this.byteOffset=0;this.D=[];this.K=new DataView(this.trackData)},xfr=function(k){g.pF.call(this,k);
var a=this;this.J=k;this.NE=[];this.Lw={};this.ge={};this.V=!1;this.L="NONE";this.K=this.aj=this.Kw=this.tG=this.ME=null;this.jw={YH:function(){a.YH()},
h0:function(f,H,B,Z){a.h0(f,H,B,Z)}};
this.D=null;this.B=this.J.Z();this.videoData=this.J.getVideoData();this.Qh=this.J.yh();this.j={bY:{}};this.N={bY:{}};g.gQ(this.videoData)?this.L="OFFLINE":OM0(this.videoData,this.J)?this.L="SABR_LIVE":g.bw3(this.videoData,this.J)?this.L="LIVE":this.videoData.captionTracks.length?this.L="INNERTUBE":this.videoData.eb&&(this.L="TTS");this.hG=this.B.controlsType==="3";this.Zq=new x$(this.J,this.B);this.cz=new g.e9(this);this.G=new g.u({C:"div",T:"ytp-caption-window-container",U:{id:"ytp-caption-window-container"}});
this.vz={top:0,right:0,bottom:0,left:0,width:1,height:1};var y=null,q=g.ND("yt-html5-player-modules::subtitlesModuleData");q&&(y=new g.JJ(q));this.storage=y;var e;this.au=!((e=k.qN())==null||!e.fV());this.X=QM9(this);this.JG=!this.X&&this.hG&&this.au&&(this.L==="LIVE"||this.L==="SABR_LIVE");g.U(this,this.Zq);this.X?this.sY=this.Ij=null:(this.Ij=new g.Ab(this.UI,void 0,this),g.U(this,this.Ij),this.sY=new g.gD(this.Onw,2E3,this),g.U(this,this.sY));g.U(this,this.cz);g.ED(this.player,this.G.element,4);
g.U(this,this.G);this.X||this.cz.Y(k,"resize",this.h9);(this.ub=g.tk(this.B)&&!g.v9()&&!this.J.isFullscreen()&&!this.X&&!this.JG)&&this.cz.Y(k,"resize",this.BkY);this.cz.Y(k,"onPlaybackAudioChange",this.wOz);this.cz.Y(k,g.BV("captions"),function(f){a.onCueRangeEnter(f)});
this.cz.Y(k,g.tx("captions"),function(f){a.onCueRangeExit(f)});
S_d(this,wVd()||{});this.player.vu("onCaptionsModuleAvailable")},g79=function(k,a,y,q){k.D.update();
a=RL1(a,y,k.D);switch(a.result){case 0:return;case 1:case 2:return}var e=a.jU;y=a.L_;if(32<=e||!e)k.K.mode&k.K.D&&(a=e,a&128&&(a=127),y&128&&(y=127),k=k.L.K,a&96&&Rm(k,0,a),y&96&&Rm(k,0,y),a!==0&&y!==0&&k.style.type===3&&Gd(k,q));else if(e&16)a:if(!k.D.matches(e,y)&&(a=k.D,a.jU=e,a.L_=y,a.state=2,a=e&8?k.N:k.j,k.L=a,k.K.mode=1<<(k.X<<2)+(a.X<<1)+(a.style.type===4?1:0),(k.K.mode|1<<(k.X<<2)+(a.X<<1)+(a.style.type!==4?1:0))&k.K.D))if(y&64){q=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|y>>5&1];
k=y&16?((y&14)>>1)*4:0;y=a.K;switch(a.style.get()){case 4:q=y.row;break;case 3:if(q!==y.row){if(q<y.K&&(q=y.K,q===y.row))break;var f=1+y.row-y.K,H=1+q-y.K;GQ2(y,H,f,y.K);a=f;e=y.K;H<f?(f=H+e-f,f>0&&(a+=f,e-=f)):(f=f+e-H,f>0&&(e-=f));lT(y,a,e)}}y.row=q;y.D=k+1}else switch(e&7){case 1:switch(y&112){case 32:Rm(a.K,0,32);break a;case 48:y===57?(q=a.K,VV(q).K=0,q.D<32&&q.D++):Rm(a.K,1,y&15)}break;case 2:y&32&&Rm(a.K,2,y&31);break;case 3:y&32&&Rm(a.K,3,y&31);break;case 4:case 5:if(32<=y&&y<=47)switch(y){case 32:Ufd(a);
break;case 33:q=a.K;q.D>1&&(--q.D,VV(q).K=0);break;case 36:q=a.K;a=VV(q);for(k=0;k<=15;k++)for(y=0;y<=32;y++)if(q.j[k][y]===a){for(;y<=32;y++)q.j[k][y].reset();break}break;case 37:l20(a,2,q);break;case 38:l20(a,3,q);break;case 39:l20(a,4,q);break;case 40:Rm(a.K,0,32);break;case 41:a.style.set(2);a.K=a.D;a.K.K=0;a.K.style=a.style;a.j.mode=1<<a.K.L;break;case 42:q=a.text;q.K=15;q.style.set(4);Vfr(q);bM9(a);break;case 43:bM9(a);break;case 44:k=a.D;switch(a.style.get()){case 1:case 2:case 3:Gd(k,q)}lT(k,
0,15);break;case 45:b:{k=a.K;switch(a.style.get()){default:case 2:case 1:break b;case 4:if(k.row<15){++k.row;k.D=1;break b}break;case 3:}k.K<2&&(k.K=2,k.row<k.K&&(k.row=k.K));a=k.row-k.K+1;Gd(k,q);GQ2(k,a,a+1,k.K-1);lT(k,k.row,1)}break;case 46:lT(a.L,0,15);break;case 47:Gd(a.D,q),a.L.updateTime(a.j.time+0),q=a.L,a.L=a.D,a.D=q,Ufd(a)}break;case 7:switch(y){case 33:case 34:case 35:q=a.K,(q.D+=y&3)>32&&(q.D=32)}}},sMa=function(k){var a=k.Qh.getVideoContentRect(!0).height,y=k.Qh.getVideoContentRect(!0).width;
if(!a||!y)return null;a*=k.vz.height;y*=k.vz.width;return{width:y,height:a}},An0=function(k,a,y){g.Q(function(q){k.K=g.nT(a,y);
g.wg(q)})},wVd=function(){return g.bN("yt-player-caption-display-settings")},QM9=function(k){var a,y=!((a=k.J.qN())==null||!a.FT());
return k.hG&&y&&k.L!=="LIVE"&&k.L!=="SABR_LIVE"},pVG=function(k,a,y,q){q=Object.assign({Pr:0},q);
return new bT(k,a,y,"_"+g$++,q)},PKa=function(k){return k.K&&k.K.N?k.K.N+k.player.Yk()<k.player.getCurrentTime():!1},Y_9=function(k,a){g.vo(k.videoData)&&(a=!0);
a||(a=k.L==="TTS"?!1:k.L==="INNERTUBE"?!1:!0);return a||k.B.W("web_deprecate_always_includes_asr_setting")&&g.ry(k.B)?!0:!!g.SD().EM(66)},Jnr=function(k,a){k.K.sort(function(e,f){var H=e.time-f.time;
return H===0?e.order-f.order:H});
for(var y=g.A(k.K),q=y.next();!q.done;q=y.next())q=q.value,k.time=q.time,q.type===0?n7r(k,q.ZP,q.Or,a):q.type===1&&k.D&496&&g79(k.X,q.ZP,q.Or,a);k.K.length=0},OM0=function(k,a){if(!g.QV8(k)||k.K!=null&&g.TW(a,k.K)&&k.K.K.rawcc!=null)return!1;
a=!!k.K&&k.K.isManifestless&&Object.values(k.K.K).some(function(y){return g.iW(y,"386")});
k=!!k.K&&!k.K.isManifestless&&g.eaa(k.K);return a||k},Nz9=function(k,a){var y={},q=a.getAttribute("wp");
q&&Object.assign(y,k.V[q]);k=sM(a,"ap");k!=null&&(y.CY=k);k=DN(a,"cc");k!=null&&(y.X7=k);k=DN(a,"ah");k!=null&&(y.rU=k);k=DN(a,"rc");k!=null&&(y.z0=k);a=DN(a,"av");a!=null&&(y.JN=a);return y},ur0=function(k,a){var y={},q=a.getAttribute("ws");
Object.assign(y,q?k.aj[q]:k.L);k=sM(a,"mh");k!=null&&(y.Pr=k);k=sM(a,"ju");k!=null&&(y.textAlign=k);k=sM(a,"pd");k!=null&&(y.Vt=k);k=sM(a,"sd");k!=null&&(y.oL=k);k=AD(a,"wfc");k!=null&&(y.windowColor=k);a=DN(a,"wfo");a!==void 0&&(y.windowOpacity=a/255);return y},v79=function(k,a,y,q,e){q===0&&(q=0x8000000000000);
var f={};a.wpWinPosId&&Object.assign(f,k.L.get(a.wpWinPosId));a.wsWinStyleId&&Object.assign(f,k.X.get(a.wsWinStyleId));k=a.rcRowCount;k!==void 0&&(f.z0=k);a=a.ccColCount;a!==void 0&&(f.X7=a);if(f.Vt===2||f.Vt===3)a=f.z0,f.z0=f.X7,f.X7=a;return new bT(y,q,0,e,f)},$fr=function(k){k.G=g.d9("SPAN");
g.tO(k.G,{display:"block"});g.C7(k.G,"caption-visual-line");k.L.appendChild(k.G)},FaG=function(k,a){var y=k.J.qN().XR().textTracks;
k=k.D.toString();for(var q=0;q<y.length;q++){var e=y[q];e.id===k&&(a?e.mode!=="showing"&&(e.mode="showing"):e.mode==="showing"&&(e.mode="disabled"))}},CK9=function(k,a){var y=[],q;
for(q in k.K.K)if(k.K.K.hasOwnProperty(q)){var e=k.K.K[q];if(g.iW(e,a||null)){var f=e.info.id,H=f,B="."+f,Z="",z="";if(e=e.info.captionTrack)f=e.languageCode,H=e.displayName,B=e.vssId,Z=e.kind,z=e.id;else{e=f;var Y=g.kar.get(e);Y==null&&(Y=o7X[e]||o7X[e.replace(/-/g,"_")],g.kar.set(e,Y));e=Y;H=e||H}y.push(new g.$p({id:q,languageCode:f,languageName:H,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:B,kind:Z,captionId:z}))}}return y},XVK=function(k){if(k.B.PC===1||k.videoData.qO===1||g.Ym(k.videoData,
"yt:cc")==="alwayson")return!0;
if(k.videoData.captionTracks.length)var a=k.getAudioTrack().D;if(k.B.PC===2){if(g.ry(k.B))var y=hLd(k);else if(k.storage)try{y=k.storage.get("module-enabled")}catch(e){k.storage.remove("module-enabled")}else y=null;if(y!=null)return!!y}y=eLX(k.player.getAudioTrack(),g.ry(k.B));var q=g.Ym(k.videoData,"yt:cc");if(Mf9(k)===void 0){if(y==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return q?q==="on":!0;if(y==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return q==="on"}else return q==="on";return a==="ON"||g.Ym(k.videoData,
"yt:cc")==="on"},La9=function(k,a,y){cna(k,a).then(function(q){q&&y(q.trackData,new g.$p(q.metadata))})},I2d=function(k){var a=1+.25*(k.fontSizeIncrement||0);
if(k.offset===0||k.offset===2)a*=.8;return a},kGX=function(k,a,y){if(typeof a==="string"||tf9(a))return[{trackData:a,
ym:y}];if(typeof a==="string"&&a.substring(0,6)==="WEBVTT"||typeof a!=="string"&&E7V(a))return[{trackData:a,ym:y}];var q=new DataView(a);if(q.byteLength<=8||q.getUint32(4)!==1718909296)return[];var e=g.HG1(q);if(k.D&&e){var f=g.ZX8(e),H=g.KVH(e);e=e.EO;f&&e&&k.D.nu(e,f,H)}k=g.Bb(q,1835295092);if(!k||!k.length||!k[0].size)return[];f=[];for(H=0;H<k.length;H++)e=k[H],e=new Uint8Array(a,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.HT(e),f.push({trackData:e,ym:y+H*1E3});Kaa(q,f,y);return f=f.filter(function(B){return!!B.trackData})},
qc9=function(k,a){aPr(k);
var y=k.Lw.reduce(function(f,H){return(k.j?H.offsetWidth:H.offsetHeight)+f},0);
y=k.V-y;if(y!==k.sY){var q=y>0&&k.sY===0,e=y<k.sY;a||isNaN(y)||q||!e||(g.C7(k.element,"ytp-rollup-mode"),k.Y(k.element,"transitionend",k.cw));g.tO(k.L,"transform",yFd(k,y));k.sY=y}aPr(k)},l20=function(k,a,y){var q=k.D,e=!1;
switch(k.style.get()){case 4:case 1:case 2:k.style.get()===4&&q.K>0||(Gd(q,y),Vfr(k.D),Vfr(k.L),q.row=15,q.K=a,e=!0)}k.style.set(3);k.K=q;k.K.style=k.style;k.j.mode=1<<q.L;e?q.D=1:q.K!==a&&(q.K>a?(Gd(q,y),lT(q,q.row-q.K,a)):q.row<a&&(a=q.K),q.K=a)},eZ1=function(k,a){if(!k.K)return{};
if(a){g.SV(a)||k.F6(a.vss_id,"m");if(k.X||!g.nL(a))return;if(g.SV(a)){W3(k,null,!0);return}for(var y,q=g.nF(k.K.D,!0),e=0;e<q.length;e++){var f=q[e];f.languageCode!==a.languageCode||y&&(f.languageName!==a.languageName||(f.captionId||"")!==(a.captionId||"")||g.sg(f)!==a.displayName)||(y=a.translationLanguage?jMX(f,a.translationLanguage):f)}k.JX(a.position);!y||y===k.D&&k.loaded||(a=g.WN(),q=g.hW(y),a.length&&q===a[a.length-1]||(a.push(q),g.Zz("yt-player-caption-language-preferences",a)),rnT(k.B)&&
!k.J.isInline()&&g.Zz("yt-player-caption-sticky-language",q,2592E3),W3(k,y,!0))}else return k.loaded&&k.D&&!pd(k)?g.AI(k.D):{};return""},Bzr=function(k,a){var y={},q=a.background?a.background:k.K.bY.background;
if(a.backgroundOpacity!=null||a.background){var e=a.backgroundOpacity!=null?a.backgroundOpacity:k.K.bY.backgroundOpacity;q=Tz9(q);y.background="rgba("+q[0]+","+q[1]+","+q[2]+","+e+")";k.WO&&(y["box-decoration-break"]="clone",y["border-radius"]=k.ge/8+"px")}if(a.fontSizeIncrement!=null||a.offset!=null)y["font-size"]=k.tG*I2d(a)+"px";q=1;e=a.color||k.K.bY.color;if(a.color||a.textOpacity!=null)e=Tz9(e),q=a.textOpacity==null?k.K.bY.textOpacity:a.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+q+")",
y.color=e,y.fill=e;var f=a.charEdgeStyle;f===0&&(f=void 0);if(f){e="rgba(34, 34, 34, "+q+")";var H="rgba(204, 204, 204, "+q+")";a.Q4&&(H=e=a.Q4);var B=k.tG/16/2,Z=Math.max(B,1),z=Math.max(2*B,1),Y=Math.max(3*B,1),r=Math.max(5*B,1);q=[];switch(f){case 4:for(;Y<=r;Y+=B)q.push(z+"px "+z+"px "+Y+"px "+e);break;case 1:z=window.devicePixelRatio>=2?.5:1;for(f=Z;f<=Y;f+=z)q.push(f+"px "+f+"px "+e);break;case 2:q.push(Z+"px "+Z+"px "+H);q.push("-"+Z+"px -"+Z+"px "+e);break;case 3:for(Y=0;Y<5;Y++)q.push("0 0 "+
z+"px "+e)}y["text-shadow"]=q.join(", ")}e="";switch(a.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.UD()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(y["font-family"]=e);e=a.offset;e==null&&(e=k.K.bY.offset);switch(e){case 0:y["vertical-align"]="sub";break;case 2:y["vertical-align"]="super"}a.fontFamily===7&&(y["font-variant"]="small-caps");a.bold&&(y["font-weight"]="bold");a.italic&&(y["font-style"]="italic");a.underline&&(y["text-decoration"]=
"underline");a.UE&&(y.visibility="hidden");a.L0===1&&k.j&&(y["text-combine-upright"]="all",y["text-orientation"]="mixed",e=g.Wt||g.zi,k.D.params.Vt===3?y.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(y.transform="rotate(-90deg)"));if(a.textEmphasis===1||a.textEmphasis===2||a.textEmphasis===3||a.textEmphasis===4||a.textEmphasis===5)if(g.Wt)y["font-weight"]="bold";else switch(y["text-emphasis-style"]="filled circle",y["text-emphasis-color"]="currentcolor",y["webkit-text-emphasis"]="filled circle",
a.textEmphasis){case 4:case 3:y["text-emphasis-position"]="under left";y["webkit-text-emphasis-position"]="under left";break;case 5:case 2:y["text-emphasis-position"]="over right",y["webkit-text-emphasis-position"]="over right"}return y},fPG=function(){var k=void 0;
k=k===void 0?{}:k;var a="suggest_correction"in g.GST?g.GST.suggest_correction:"Edit caption";a=a||"";var y={},q;for(q in k){y={m6:y.m6};y.m6=q;var e=function(f){return function(){return String(k[f.m6])}}(y);
a=a.replace(new RegExp("\\$\\{"+y.m6+"\\}","gi"),e);a=a.replace(new RegExp("\\$"+y.m6,"gi"),e)}return a},$02=function(){},bT=function(k,a,y,q,e){g.Uc.call(this,k,k+a,{priority:y,
namespace:"captions"});this.id=q;this.params=e;this.K=[]},yn9=function(){P3.call(this)},H3V=function(k){var a={};
if(k=g.hW(k))a.lang=k,g.f79.test(k)&&(a.Vt=1);return a},bM9=function(k){k.style.set(4);
k.K=k.text;k.K.style=k.style;k.j.mode=1<<k.K.L},d02=function(k,a){return a!=null&&a in k.K.K?k.K.K[a]:null},RL1=function(k,a,y){if(k===255&&a===255||!k&&!a)return{jU:k,
L_:a,result:0};k=BR9[k];a=BR9[a];if(k&128){var q;if(q=!(a&128))q=a,q=y.sb()&&y.L_===q;if(q)return{jU:k,L_:a,result:1}}else if(a&128&&1<=k&&k<=31)return{jU:k,L_:a,result:2};return{jU:k,L_:a,result:3}},Z3r=function(k,a){var y=sMa(k);
if(!y)return null;var q=k.D?g.hW(k.D):null;q&&g.f79.test(q)&&(a.params.Vt=1);var e=k.Qh.getPlayerSize();q=e.height*k.vz.height;e=e.width*k.vz.width;k.B.playerStyle!=="google-live"||k.j.isDefault||Object.assign(a.params,k.j);switch(a.params.Pr!=null?a.params.Pr:a.K.length>1?1:0){case 1:return new nd(a,k.j,k.N,y.width,y.height,e,q,k.B.experiments,k.Ut.bind(k),k.J);case 2:return new JD(a,k.j,k.N,y.width,y.height,e,q,k.B.experiments,k.Ut.bind(k),k.J);default:return new NA(a,k.j,k.N,y.width,y.height,e,
q,k.B.experiments,k.Ut.bind(k),k.J)}},i3d=function(k,a){switch(k){case 0:return zZ0[(a&127)-32];
case 1:return YcK[a&15];case 2:return rF1[a&31];case 3:return j69[a&31]}return 0},WYX=function(k){var a="_"+g$++;
return new bT(0,0x8000000000000,0,a,k)},TR1=function(k){this.K=k;
this.X=0;this.j=new m0G(this.K);this.N=new m0G(this.K);this.D=new uT;this.L=this.j},iT=function(k){return k.aj&&k.aj.K},Y$=function(k,a){k.J.isInline()||g.Zz("yt-player-sticky-caption",a,2592E3)},v3=function(k){k=g.nz(Math.round(k),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-k.length)+k},AD=function(k,a){k=k.getAttribute(a);
if(k!=null)return UM.test(k),k},Vfr=function(k){k.row=k.K>0?k.K:1;
k.D=1;lT(k,0,15)},Sc1=function(){this.j=this.time=this.mode=this.D=0;
this.L=new TR1(this);this.X=new TR1(this);this.K=[];this.clear()},cna=function(k,a){var y,q,e;
return g.Q(function(f){if(f.K==1)return y=k+"|"+a,g.p(f,g.g2(),2);if(f.K!=3){q=f.D;if(!q)throw g.sQ("gct");return g.p(f,g.Al(q),3)}e=f.D;return f.return(e.get("captions",y))})},D09=function(k,a,y){a&&!k.Kw?(a=WYX({Vt:0,
lang:"en"}),k.Kw=[a,new F7(a.start,a.end-a.start,0,a.id,y!=null?y:"Captions look like this")],k.player.RY(k.Kw)):!a&&k.Kw&&(U0d(k,k.Kw),k.Kw=null)},GQ2=function(k,a,y,q){for(var e=0;e<q;e++)for(var f=0;f<=32;f++){var H=k.j[a+e][f],B=k.j[y+e][f];
H.K=B.K;H.timestamp=B.timestamp}},uT=function(){this.state=this.L_=this.jU=0},om=function(k){k=k.split("px");
return k.length>0?(k=Number(k[0]))?k:0:0},O3G=function(k,a,y,q){var e={};
Object.assign(e,Nz9(k,a));Object.assign(e,ur0(k,a));q?g.dy(e,k.L)?(q=k.X,e=k.L):q="_"+g$++:q=a.getAttribute("id")||"_"+g$++;k=DN(a,"t")+y;a=DN(a,"d")||0x8000000000000;if(e.Vt===2||e.Vt===3)y=e.z0,e.z0=e.X7,e.X7=y;return new bT(k,a,0,q,e)},Mf9=function(k){var a=void 0,y=g.SD().EM(65);
if(g.ry(k.B)&&y!=null){if(hLd(k)!=null)return!1;a=!y}return a},m0G=function(k){this.j=k;
this.X=0;this.style=new OM;this.N=new QV(this.j);this.G=new QV(this.j);this.text=new QV(this.j);this.D=this.N;this.L=this.G;this.K=this.D},wpK=function(k,a,y,q,e,f,H){var B=f[0],Z=H[B.getAttribute("p")];
if(Z.Lq===1){var z=f[1],Y=f[2];f=f[3];B.getAttribute("t");z.getAttribute("t");Y.getAttribute("t");f.getAttribute("t");B.getAttribute("p");z.getAttribute("p");f.getAttribute("p");H=H[Y.getAttribute("p")];B=Q6r(B.textContent,z.textContent,Y.textContent,f.textContent,H);return new F7(k,a,e,y,B,q,Z)}switch(Z.Lq){case 9:case 10:Z.textEmphasis=1;break;case 11:Z.textEmphasis=2;break;case 12:Z.textEmphasis=3;break;case 13:Z.textEmphasis=4;break;case 14:Z.textEmphasis=5}return new F7(k,a,e,y,B.textContent||
"",q,Z)},Cd=function(){this.segments=[]},OM=function(){this.type=0},JD=function(k,a,y,q,e,f,H,B,Z,z){NA.call(this,k,a,y,q,e,f,H,B,Z,z);
var Y=this;this.type=2;this.Lw=[];this.Kw=this.V=this.sY=0;this.JG=NaN;this.ub=0;this.mO=null;this.jw=new g.gD(this.cw,433,this);this.X&&(z.createClientVe(this.X,this,167342),this.Y(this.X,"click",function(){z.logClick(Y.X)}),k=new g.sW(this.element,!0),g.U(this,k),k.subscribe("hoverstart",function(){z.logVisibility(Y.X,!0)},this));
g.C7(this.element,"ytp-caption-window-rollup");g.U(this,this.jw);g.tO(this.element,"overflow","hidden")},x0V=function(k,a,y){var q=[],e;
for(e in k.K.K)if(k.K.K.hasOwnProperty(e)){var f=k.K.K[e];if(g.iW(f,y||null)){var H=f.info.captionTrack;H&&H.languageCode===a&&q.push(f)}}return q.length?q[0]:null},RZX=function(k){var a=k.split(":");
k=0;a=g.A(a);for(var y=a.next();!y.done;y=a.next())k=k*60+Number(y.value);return k*1E3},hD=function(k){P3.call(this);
this.L=k;this.pens={};this.V={};this.aj={};this.X="_"+g$++;this.G={};this.D=this.K=null;this.N=!0},Q6r=function(k,a,y,q,e){var f=g.UD(),H=f?g.d9("DIV"):g.d9("RUBY"),B=g.d9("SPAN");
B.textContent=k;H.appendChild(B);k=f?g.d9("DIV"):g.d9("RP");k.textContent=a;H.appendChild(k);a=f?g.d9("DIV"):g.d9("RT");a.textContent=y;H.appendChild(a);y=e.Lq;if(y===10||y===11||y===12||y===13||y===14)if(g.tO(a,"text-emphasis-style","filled circle"),g.tO(a,"text-emphasis-color","currentcolor"),g.tO(a,"webkit-text-emphasis","filled circle"),e.Lq===11||e.Lq===13)g.tO(a,"webkit-text-emphasis-position","under left"),g.tO(a,"text-emphasis-position","under left");y=!0;if(e.Lq===4||e.Lq===7||e.Lq===12||
e.Lq===14)g.tO(H,"ruby-position","over"),g.tO(H,"-webkit-ruby-position","before");else if(e.Lq===5||e.Lq===6||e.Lq===11||e.Lq===13)g.tO(H,"ruby-position","under"),g.tO(H,"-webkit-ruby-position","after"),y=!1;e=f?g.d9("DIV"):g.d9("RP");e.textContent=q;H.appendChild(e);f&&(q=y,g.tO(H,{display:"inline-block",position:"relative"}),f=H.firstElementChild.nextElementSibling,g.tO(f,"display","none"),f=f.nextElementSibling,g.tO(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.tO(H.lastElementChild,"display","none"),q?(g.tO(H,"padding-top","0.6em"),g.tO(f,"top","0")):(g.tO(H,"padding-bottom","0.6em"),g.tO(f,"bottom","0")));return H},r$=function(k,a){if(k.storage)try{k.storage.set("module-enabled",a)}catch(y){}},jMX=function(k,a){var y=new g.$p;
y.languageCode=k.languageCode;y.languageName=k.languageName;y.name=k.name;y.displayName=k.displayName;y.kind=k.kind;y.isDefault=!1;y.K=k.K;y.isTranslateable=k.isTranslateable;y.vssId=k.vssId;y.url=k.url;y.translationLanguage=a;k.xtags&&(y.xtags=k.xtags);k.captionId&&(y.captionId=k.captionId);return y},MA=function(k){P3.call(this);
this.N=k;this.K=new Map;this.L=new Map;this.X=new Map;this.D=new Map},tf9=function(k){if(typeof k==="string")return!1;
k=new w$(k,8,0);return GG9(k)},X7=function(k,a,y){g.H2.call(this,k);
this.videoData=a;this.audioTrack=y;this.X=a.mS},jE=function(k,a){if(k.D&&(a===void 0||!a)||!k.videoData.captionTracks.length)return!1;
k=k.getAudioTrack();return!!k.K||k.D==="FORCED_ON"},lPV=function(k,a){k=g.oT(k,{startTimeMs:a},function(y,q){return y.startTimeMs-q.startTimeMs});
return k>=0?k:-k-2},c3=function(k,a){g.H2.call(this,a);
this.K=k;this.J=a;this.L=null;this.N=!1;this.logger=new g.ci("caps");this.G=g.TW(this.J,this.K)},rnT=function(k){return g.ry(k)||k.W("web_enable_caption_language_preference_stickiness")},sM=function(k,a){k=DN(k,a);
return k!==void 0?k:null},hLd=function(k){if(!k.J.isInline())return g.bN("yt-player-sticky-caption")},aPr=function(k){k.Lw=Array.from(k.element.getElementsByClassName("caption-visual-line"));
for(var a=k.D.params.z0,y=0,q=0,e=k.Lw.length-1;y<a&&e>-1;){var f=k.Lw[e];q+=k.j?f.offsetWidth:f.offsetHeight;y++;e--}k.V=q;a=Math;y=a.max;isNaN(k.JG)&&((q=k.K.X7)?(e=g.d9("SPAN"),g.uF(e,"\u2013".repeat(q)),g.tO(e,Bzr(k,k.K.bY)),k.L.appendChild(e),k.JG=e.offsetWidth,k.L.removeChild(e)):k.JG=0);q=k.L;k.Kw=y.call(a,k.JG,k.ub,(k.j?q.offsetHeight:q.offsetWidth)+1)},nd=function(k,a,y,q,e,f,H,B,Z,z){NA.call(this,k,a,y,q,e,f,H,B,Z,z);
this.type=1},F7=function(k,a,y,q,e,f,H){f=f===void 0?!1:f;
H=H===void 0?null:H;g.Uc.call(this,k,k+a,{priority:y,namespace:"captions"});this.windowId=q;this.text=e;this.append=f;this.K=H},VqG=function(k,a){k.K=function(y,q){if(y.info.L){var e=y;
if(k.YP.length>0){for(e=k.YP.shift();k.YP.length>0;)e=g.ck(e,k.YP.shift());e=g.ck(e,y)}if(e){y=e;try{var f=g.zP(y)*1E3}catch(z){f=y.info.startTime*1E3}try{var H=g.xKl(y)*1E3}catch(z){H=y.info.duration*1E3}if(f<0||H<0)f<0&&(f=y.info.startTime*1E3),H<0&&(H=y.info.duration*1E3);y.info.startTime=f/1E3;y.info.X=f/1E3;y.info.duration=H/1E3;y.info.V=H/1E3;f=k.FM(e);H=f.Wz;f={formatId:f.formatId,startTimeMs:f.startTimeMs,durationMs:f.durationMs,wT:H,QX:H};H=lPV(k.u_,f.startTimeMs);var B=(y=H>=0?k.u_[H]:null)?
y.startTimeMs+y.durationMs:0,Z=f.startTimeMs+f.durationMs;!y||f.startTimeMs-B>k.D?k.u_.splice(H+1,0,f):(y.durationMs=Math.max(B,Z)-y.startTimeMs,y.QX=Math.max(y.QX,f.QX));q(k.u_);f=g.fI(e);q=k.j;f=f.buffer.slice(f.byteOffset,f.byteLength+f.byteOffset);e=e.info.X;q.N?q.L==null?g.VR(q.logger,350058965,"Null loaded track meta data at captions data received"):a.h0(f,q.L,e*1E3):g.VR(q.logger,350058965,"Null Representation at captions data received")}else g.VR(k.logger,350058965,"Empty slice")}else k.YP.push(y)};
k.J.addEventListener("sabrCaptionsDataLoaded",k.K)},E7V=function(k){var a=b3G.length;
if(k.byteLength<a)return!1;k=new Uint8Array(k,0,a);for(var y=0;y<a;y++)if(b3G[y]!==k[y])return!1;return!0},Ld=function(k,a){g.H2.call(this,a);
this.K=k;this.J=a;this.logger=new g.ci("caps");this.L=this.N=null;this.G=new gLd(this.J,this,this.logger,this.K.dk)},gLd=function(k,a,y,q){var e=this;
this.J=k;this.j=a;this.logger=y;this.dk=q;this.u_=[];this.YP=[];this.K=null;this.Sw={Jp3:function(){return e.K},
g9:function(){return e.u_}};
k=g.Ht(this.J.Z().experiments,"html5_override_micro_discontinuities_threshold_ms");this.D=k>0?k:10},P3=function(){g.C.apply(this,arguments)},s6a=function(k,a,y,q,e,f,H,B,Z){switch(H.tagName){case "b":B.bold=!0;
break;case "i":B.italic=!0;break;case "u":B.underline=!0}for(var z=0;z<H.childNodes.length;z++){var Y=H.childNodes[z];if(Y.nodeType===3)Y=new F7(a,y,q,e.id,Y.nodeValue,f||z>0,g.SV(B)?void 0:B),Z.push(Y),e.K.push(Y);else{var r={};Object.assign(r,B);s6a(k,a,y,q,e,!0,Y,r,Z)}}},Im=function(k,a){P3.call(this);
this.D=k;this.L=a;this.track=this.L.languageName==="CC3"?4:0;this.K=new Sc1;this.K.D=1<<this.track},AFd=function(k,a,y){var q=[],e;
for(e in k.K.K)if(k.K.K.hasOwnProperty(e)){var f=k.K.K[e];if(g.iW(f,y||null)){var H=f.info.captionTrack;H&&H.languageCode===a&&q.push(f)}}return q.length?q[0]:null},VV=function(k){return k.j[k.row][k.D]},n7r=function(k,a,y,q){a===255&&y===255||!a&&!y?(++k.j===45&&k.reset(),k.L.D.clear(),k.X.D.clear()):(k.j=0,g79(k.L,a,y,q))},x$=function(k,a){g.C.call(this);
this.J=k;this.B=a;this.K=null;this.D=this.J.Ae();this.logger=new g.ci("caps")},tD=function(k){var a=k.byteOffset;
k.byteOffset+=4;return k.K.getUint32(a)},ppr=function(k,a,y,q,e,f){g.C.call(this);
this.policy=k;this.player=a;this.Kw=y;this.V=q;this.X=e;this.aj=f;this.L=new Cd;this.N=-1;this.D=this.j=this.K=null;this.vz=0;this.G=new g.gD(this.Qp,1E3,this);this.events=new g.e9(this);g.U(this,this.G);g.U(this,this.events);this.events.Y(a,"SEEK_COMPLETE",this.tC);this.tC();this.Qp()},EM=function(k){var a=k.byteOffset;
k.byteOffset+=1;return k.K.getUint8(a)},lT=function(k,a,y){for(var q=0;q<y;q++)for(var e=0;e<=32;e++)k.j[a+q][e].reset()},Kd=function(k,a){k=k.getAttribute(a);
if(k!=null)return k==="1"},yFd=function(k,a){if(!a)return"";
k.j&&k.D.params.oL!==1&&(a*=-1);return"translate"+(k.j?"X":"Y")+"("+a+"px)"},PY9=function(k,a){if(a instanceof bT){var y=k.Lw[a.id];
y&&y.D!==a&&(y.dispose(),delete k.Lw[a.id],y=null);y||(y=Z3r(k,a))&&(k.Lw[a.id]=y)}else y=a.windowId,k.ge[y]||(k.ge[y]=[]),k.ge[y].push(a)},GG9=function(k){if(!(k.byteOffset<k.K.byteLength)||tD(k)!==1380139777)return!1;
k.version=EM(k);if(k.version>1)return!1;EM(k);EM(k);EM(k);return!0},U0d=function(k,a){k.player.M8(a);
a=g.A(a);for(var y=a.next();!y.done;y=a.next())g.d2(k.NE,y.value);mt(k.Ij)},NA=function(k,a,y,q,e,f,H,B,Z,z){var Y=z.isInline()&&!0,r={};
Object.assign(r,a);Object.assign(r,k.params);Object.assign(r,y);var W={};Object.assign(W,a.bY);k.params.bY&&Object.assign(W,k.params.bY);Object.assign(W,y.bY);Y&&(r.windowOpacity=.6,W.backgroundOpacity=0);r.bY=W;var m=r.Vt===1,T=[{C:"span",T:"captions-text",U:{style:"word-wrap: normal; display: block;"}}],O,x,V;(B=B.OY("caption_edit_on_hover")&&((O=z.getVideoData().getPlayerResponse())==null?void 0:(x=O.captions)==null?void 0:(V=x.playerCaptionsTracklistRenderer)==null?void 0:V.openTranscriptCommand))&&
T.unshift({C:"button",T:"caption-edit",U:{tabindex:"0","aria-label":fPG()},S:[{C:"svg",U:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},S:[{C:"path",U:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.u.call(this,{C:"div",T:"caption-window",U:{id:"caption-window-"+k.id,dir:m?"rtl":"ltr",tabindex:"0",lang:r.lang},S:T});var l=
this;this.N=[];this.cz=!1;this.D=k;this.Ij=this.NE=null;this.DS=f;this.gk=H;this.G=null;this.maxWidth=f*.96;this.maxHeight=H*.96;this.K=r;this.FR=y;this.vz=a;this.L=this.ij("captions-text");this.WO=this.L.style.getPropertyValue("box-decoration-break")!==""||this.L.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.tG=zLd(q,e,f,H);this.HO=Z;B&&(this.X=this.ij("caption-edit"),this.Y(this.X,"click",function(){l.HO()}));
this.type=0;this.ge=this.tG*I2d(W);this.au=Y;k=new g.sW(this.element,!0);g.U(this,k);k.subscribe("dragstart",this.wf,this);k.subscribe("dragmove",this.LA,this);k.subscribe("dragend",this.jN,this);this.Zq=this.hG=this.Qh=this.ME=0;k="";this.K.windowOpacity&&(k=Tz9(this.K.windowColor),k="rgba("+k[0]+","+k[1]+","+k[2]+","+this.K.windowOpacity+")");a={"background-color":k,display:this.K.isVisible===!1?"none":"","text-align":nLr[this.K.textAlign]};this.WO&&(a["border-radius"]=k?this.ge/8+"px":"");(this.j=
this.D.params.Vt===2||this.D.params.Vt===3)&&Dfr(this,this.element);g.tO(this.element,a);if(Y){var P;(P=this.element.parentElement)==null||P.style.setProperty("--caption-window-color",k)}switch(this.K.CY){case 0:case 1:case 2:g.C7(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.C7(this.element,"ytp-caption-window-bottom")}},Gd=function(k,a){if(k.style.type===3){for(var y=0,q=0,e=k.X.time+0,f="",H="",B=e,Z=1;Z<=15;++Z){for(var z=!1,Y=q?q:1;Y<=32;++Y){var r=k.j[Z][Y];
if(r.K!==0){y===0&&(y=Z,q=Y);z=String.fromCharCode(r.K);var W=r.timestamp;W<e&&(e=W);r.timestamp=B;H&&(f+=H,H="");f+=z;z=!0}if((r.K===0||Y===32)&&z){H="\n";break}else if(q&&!z)break}if(y&&!z)break}f&&a.L(y,q,e,B,f)}else for(q=y=0,f=e=k.X.time+0,H=1;H<=15;++H)for(B="",Z=1;Z<=32;++Z)if(Y=k.j[H][Z],r=Y.K,r!==0&&(y===0&&(y=H,q=Z),z=String.fromCharCode(r),W=Y.timestamp,W<=e&&(e=W),B+=z,Y.reset()),Z===32||r===0)B&&a.L(y,q,e,f,B),e=f,B="",q=y=0},a2a=function(k,a){k.B.W("html5_modify_caption_vss_logging")&&
(k.videoData.C6=a)},Kaa=function(k,a,y){var q=g.$5(k,0,1836476516),e=9E4;
q&&(e=g.Hn(q)||9E4);q=0;for(var f=g.Bb(k,1836019558),H=0;H<f.length;H++){var B=f[H];H<a.length&&(B=g.$5(k,B.dataOffset,1953653094))&&(B=g.$5(k,B.dataOffset,1952867444))&&(B=g.dj(B)/e*1E3,H===0&&(q=B),a[H].ym=B-q+y||y*H*1E3)}},Rm=function(k,a,y){a>=2&&k.D>1&&(--k.D,VV(k).K=0);
var q=VV(k);q.timestamp=k.X.time+0;q.K=i3d(a,y);k.D<32&&k.D++},pd=function(k){var a=iT(k);
return!!a&&k.D===a},JFd=function(k,a){var y=[],q;
for(q in k.K.K)if(k.K.K.hasOwnProperty(q)){var e=k.K.K[q];if(g.iW(e,a||null)){var f=e.info.id,H=f,B="."+f,Z="",z="";if(e=e.info.captionTrack)f=e.languageCode,H=e.displayName,B=e.vssId,Z=e.kind,z=e.id;y.push(new g.$p({id:q,languageCode:f,languageName:H,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:B,kind:Z,captionId:z}))}}return y};
g.H2.prototype.q6=g.$g(71,function(){return!1});
g.H2.prototype.SV=g.$g(70,function(){});
g.ZC.prototype.SV=g.$g(69,function(k,a,y){var q=this;this.xs();a=this.F7(k,a);var e=this.Rj.Z().W("html5_report_captions_ctmp_qoe"),f=(0,g.Bi)();this.cS();An0(this,a,{format:"RAW",onSuccess:function(H){q.K=null;if(e){var B=(H.responseText.length/1024).toFixed(),Z=(0,g.Bi)();q.videoData.lj("capresp",{ms:Z-f,kb:B})}y.h0(H.responseText,k)},
onError:e?function(H){var B;H=(B=H==null?void 0:H.status)!=null?B:0;q.videoData.lj("capfail",{status:H})}:void 0,
withCredentials:!0})});
g.u4.prototype.SV=g.$g(68,function(k,a,y){var q=this;this.xs();a=this.F7(k,a);this.cS();this.K=g.nT(a,{format:"RAW",onSuccess:function(e){q.K=null;y.h0(e.responseText,k)},
withCredentials:!0})});
g.IY.prototype.dZ=g.$g(67,function(){for(var k=g.Ys(document,"track",void 0,this.K),a=0;a<k.length;a++)g.JM(k[a])});
g.CO.prototype.dZ=g.$g(66,function(){this.mediaElement.dZ()});
g.IY.prototype.fV=g.$g(65,function(){return!(!this.K.textTracks||!this.K.textTracks.addEventListener)});
g.CO.prototype.fV=g.$g(64,function(){return this.mediaElement.fV()});
g.IY.prototype.FT=g.$g(63,function(){return!!this.K.textTracks});
g.CO.prototype.FT=g.$g(62,function(){return this.mediaElement.FT()});
g.IY.prototype.Yt=g.$g(61,function(k){for(var a=0;a<k.length;a++)this.K.appendChild(k[a])});
g.CO.prototype.Yt=g.$g(60,function(k){this.mediaElement.Yt(k)});
g.bp.prototype.nu=g.$g(59,function(k,a,y){this.zW.nu(k,a,y)});
g.Bn.prototype.nu=g.$g(58,function(k,a,y){this.D.set(k,{zy:a,i4:y})});
g.dq.prototype.nu=g.$g(57,function(k,a,y){this.vz.nu(k,a,y)});
g.bp.prototype.rS=g.$g(56,function(k){return this.zW.rS(k)});
g.dq.prototype.rS=g.$g(55,function(k){var a=2;this.X.has(k)?a=0:g.v8(this,k)&&(a=1);return a});
g.vg.prototype.BS=g.$g(43,function(k){var a=this.app.W_({playerType:void 0});return a?a.BS(k):!1});
g.Se.prototype.BS=g.$g(42,function(k){return this.Pz.Bl.BS(k)});
g.dz.prototype.BS=g.$g(41,function(k){return this.G9().some(function(a){return a.namespace===k})});
g.Jz.prototype.BS=g.$g(40,function(){return!1});
g.vg.prototype.F6=g.$g(38,function(k,a){this.app.F5().F6(k,a)});
g.Se.prototype.F6=g.$g(37,function(k,a){this.Pz.F6(k,a)});
g.rX.prototype.F6=g.$g(36,function(k,a){k=[k,a];g.ur(this,g.ym(this.provider),"cfi",k)});
g.Y7.prototype.F6=g.$g(35,function(k,a){this.qoe&&this.qoe.F6(k,a)});
g.iK.prototype.F6=g.$g(34,function(k,a){this.rk.F6(k,a)});
g.Jz.prototype.F6=g.$g(33,function(){});
g.vg.prototype.HA=g.$g(32,function(k,a,y){this.app.F5().HA(k,a,y)});
g.Se.prototype.HA=g.$g(31,function(k,a,y){this.Pz.HA(k,a,y)});
g.rX.prototype.HA=g.$g(30,function(k,a,y){if(this.Ij!==k||this.HO!==a)a=a==="rawcc"?"":a,y=[k,a,this.Ij,y],g.ur(this,g.ym(this.provider),"cfs",y),this.Ij=k,this.HO=a});
g.Y7.prototype.HA=g.$g(29,function(k,a,y){this.qoe&&this.qoe.HA(k,a,y)});
g.iK.prototype.HA=g.$g(28,function(k,a,y){this.rk.HA(k,a,y)});
g.Jz.prototype.HA=g.$g(27,function(){});
g.RJ.prototype.bW=g.$g(12,function(){return this.V});
g.cg.prototype.bW=g.$g(11,function(){return this.F5().Ae()});
g.vg.prototype.Ae=g.$g(10,function(){return this.app.bW()});
g.Se.prototype.Ae=g.$g(9,function(){return this.Pz.Ae()});
g.iK.prototype.Ae=g.$g(8,function(){var k;return((k=this.loader)==null?void 0:k.bW())||null});
g.Jz.prototype.Ae=g.$g(7,function(){return null});
g.fo.prototype.gm=g.$g(1,function(k){return(k=this.du(k))?k.K:0});
g.gG.prototype.gm=g.$g(0,function(){return 0});
var mfr=/#(.)(.)(.)/,WaT=/^#(?:[0-9a-f]{3}){1,2}$/i,o7X={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};Cd.prototype.contains=function(k){k=g.oT(this.segments,k);return k>=0||k<0&&(-k-1)%2===1};
Cd.prototype.length=function(){return this.segments.length/2};
g.I(ppr,g.C);g.S=ppr.prototype;g.S.uj=function(){g.C.prototype.uj.call(this);this.D&&this.D.cancel()};
g.S.tC=function(){this.seekTo(this.player.getCurrentTime())};
g.S.seekTo=function(k){k-=this.player.Yk();var a=this.K;this.K=g.vp(this.Kw.Ud(k).S3);a!==this.K&&this.aj&&this.aj()};
g.S.reset=function(){this.L=new Cd;this.N=-1;this.D&&(this.D.cancel(),this.D=null)};
g.S.Qp=function(){this.xs();var k;if(k=this.K!=null)k=this.K,k=k.K.Qe(k);if(k&&!this.D&&!(this.K&&this.K.startTime-this.player.getCurrentTime()>30)){k=this.K;k=k.K.P0(k);var a=k.S3[0],y;if((y=this.player.getVideoData())==null?0:y.enableServerStitchedDai)if(y=this.player.Ae()){var q=a.K.info.id,e=a.Wz,f=k.S3[0].X;if(this.policy.Ij){if(y=y.qD(f,e,q,3))k.L=y}else if(q=y.yu(f,e,q,3))if(y=y.rS(e),y===0)q&&(k.K=new g.cn(q));else if(y===2){this.G.start();PKa(this)&&this.seekTo(this.player.getCurrentTime());
return}}a.K.index.FS(a.Wz)?(this.L.contains(k.S3[0].Wz)||iM9(this,k),this.K=g.vp(k.S3)):PKa(this)&&this.seekTo(this.player.getCurrentTime())}this.G.start()};
g.I(c3,g.H2);g.S=c3.prototype;g.S.SV=function(k,a,y){var q=this;this.cS();a=d02(this,k.getId());a||(a=k.languageCode,a=this.K.isManifestless?x0V(this,a,"386"):x0V(this,a));if(a){var e=(a.index.gm(a.index.GU())-a.index.getStartTime(a.index.GU()))*1E3,f=new g.U9H(this.J.Z());this.L=new ppr(f,this.J,a,function(H,B){y.h0(H,k,B,e)},this.G||g.$y(a.info),function(){q.L&&q.L.reset();
q.N=!0})}};
g.S.q6=function(){var k=this.N;this.N=!1;return k};
g.S.W5=function(k){var a=this.J.Z().W("html5_fallback_if_rawcc_missing");var y=this.K.K.rawcc!=null;if(!this.G||!y&&a)a=this.K.isManifestless?CK9(this,"386"):CK9(this);else{if(!y){g.VR(this.logger,386248249,"rawcc used but unavailable");return}a=[new g.$p({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.$p({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}a=g.A(a);
for(y=a.next();!y.done;y=a.next())g.Um(this.D,y.value);k.YH()};
g.S.cS=function(){this.L&&(this.L.dispose(),this.L=null)};
g.S.F7=function(){return""};
var UM=/^#(?:[0-9a-f]{3}){1,2}$/i;var nLr=["left","right","center","justify"];g.I(NA,g.u);g.S=NA.prototype;g.S.wf=function(k,a){this.hG=k;this.Zq=a;var y=g.DZ(this.element,this.element.parentElement);this.ME=k-y.x;this.Qh=a-y.y};
g.S.LA=function(k,a){if(k!==this.hG||a!==this.Zq){g.zO(this.element,"ytp-dragging")||g.C7(this.element,"ytp-dragging");var y=g.J1(this.element);k=k-this.ME-.02*this.DS;var q=a-this.Qh-.02*this.gk,e=(k+y.width/2)/this.maxWidth*3;e=Math.floor(g.nz(e,0,2));var f=(q+y.height/2)/this.maxHeight*3;f=Math.floor(g.nz(f,0,2));a=e+f*3;k=(k+e/2*y.width)/this.maxWidth;k=g.nz(k,0,1)*100;y=(q+f/2*y.height)/this.maxHeight;y=g.nz(y,0,1)*100;this.D.params.CY=a;this.D.params.JN=y;this.D.params.rU=k;this.D.params.isDefault=
!1;this.K.CY=a;this.K.JN=y;this.K.rU=k;this.K.isDefault=!1;this.vz.CY=a;this.vz.JN=y;this.vz.rU=k;this.vz.isDefault=!1;this.jk()}};
g.S.jN=function(){g.MF(this.element,"ytp-dragging")};
g.S.jk=function(){this.yy(this.N)};
g.S.yy=function(k){var a=this.au?0:Math.min(this.C4(),this.maxWidth),y=this.wP(),q=this.au;if(q){var e=getComputedStyle(this.L.parentNode);e=om(e.borderLeftWidth)+om(e.borderRightWidth)+om(e.paddingLeft)+om(e.paddingRight)}else e=0;var f=e;e="";this.D.params.Vt===3&&(e="rotate(180deg)");var H=q?"calc(96% - "+f+"px)":"96%";g.tO(this.element,{top:0,left:0,right:"",bottom:"",width:a?a+"px":"",height:y?y+"px":"","max-width":H,"max-height":H,margin:"",transform:""});this.hR(k);e={transform:e,top:"",left:"",
width:a?a+"px":"",height:y?y+"px":"","max-width":"","max-height":""};var B=this.K.rU*.96+2;H=this.K.CY;switch(H){case 0:case 3:case 6:(q=this.K.bY.fontSizeIncrement)&&q>0&&this.K.Vt!==2&&this.K.Vt!==3&&(B=Math.max(B/(1+q*2),2));e.left=B+"%";break;case 1:case 4:case 7:e.left=B+"%";B=this.L.offsetWidth;a||B?(a=a||B+1,e.width=a+"px",e["margin-left"]=q?a/-2-f/2+"px":a/-2+"px"):e.transform+=" translateX(-50%)";break;case 2:case 5:case 8:e.right=100-B+"%"}q=this.K.JN*.96+2;switch(H){case 0:case 1:case 2:e.top=
q+"%";break;case 3:case 4:case 5:e.top=q+"%";(y=y||this.element.clientHeight)?(e.height=y+"px",e["margin-top"]=y/-2+"px"):e.transform+=" translateY(-50%)";break;case 6:case 7:case 8:e.bottom=100-q+"%"}g.tO(this.element,e);if(this.X){y=this.L.offsetHeight;q=1;for(a=0;a<k.length;a++)e=k[a],typeof e.text==="string"&&(q+=e.text.split("\n").length-1,e.append||a===0||q++);y/=q;this.X.style.height=y+"px";this.X.style.width=y+"px";this.element.style.paddingLeft=y+5+"px";this.element.style.paddingRight=y+
5+"px";k=Number(this.element.style.marginLeft.replace("px",""))-y-5;y=Number(this.element.style.marginRight.replace("px",""))-y-5;this.element.style.marginLeft=k+"px";this.element.style.marginRight=y+"px"}};
g.S.hR=function(k){var a;for(a=0;a<k.length&&k[a]===this.N[a];a++);if(this.cz||this.N.length>a)a=0,this.cz=!1,this.N=[],this.G=this.Ij=this.NE=null,g.J2(this.L);for(;a<k.length;a++)dfa(this,k[a])};
g.S.C4=function(){return 0};
g.S.wP=function(){return 0};
g.S.toString=function(){return g.u.prototype.toString.call(this)};Sc1.prototype.clear=function(){this.j=this.time=this.mode=0;this.K=[];this.reset()};
Sc1.prototype.reset=function(){this.mode=0;this.L.reset(0);this.X.reset(1)};
var BR9=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];OM.prototype.set=function(k){this.type=k};
OM.prototype.get=function(){return this.type};
uT.prototype.clear=function(){this.state=0};
uT.prototype.update=function(){this.state=this.state===2?1:0};
uT.prototype.sb=function(){return this.state!==0};
uT.prototype.matches=function(k,a){return this.sb()&&k===this.jU&&a===this.L_};
f20.prototype.reset=function(){this.timestamp=this.K=0};
QV.prototype.updateTime=function(k){for(var a=1;a<=15;++a)for(var y=1;y<=32;++y)this.j[a][y].timestamp=k};
QV.prototype.debugString=function(){for(var k="\n",a=1;a<=15;++a){for(var y=1;y<=32;++y){var q=this.j[a][y];k=q.K===0?k+"_":k+String.fromCharCode(q.K)}k+="\n"}return k};
QV.prototype.reset=function(k){for(var a=0;a<=15;a++)for(var y=0;y<=32;y++)this.j[a][y].reset();this.L=k;this.K=0;this.D=this.row=1};
var zZ0=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],YcK=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],rF1=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],j69=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];m0G.prototype.reset=function(k,a){this.X=a;this.style.set(2);this.D=this.N;this.L=this.G;this.K=this.D;var y=(k<<2)+(a<<1);this.N.reset(y);this.G.reset(y);this.text.reset((k<<2)+(a<<1)+1)};
TR1.prototype.reset=function(k){this.X=k;this.D.clear();this.L=this.j;this.j.reset(k,0);this.N.reset(k,1)};$02.prototype.L=function(){};g.I(F7,g.Uc);F7.prototype.toString=function(){return g.Uc.prototype.toString.call(this)};g.I(P3,g.C);P3.prototype.reset=function(){};g.I(bT,g.Uc);bT.prototype.toString=function(){return g.Uc.prototype.toString.call(this)};
var g$=0;g.I(hD,P3);hD.prototype.reset=function(){this.G={};this.D=this.K=null;this.N=!0};
hD.prototype.j=function(k,a){k=k.firstChild;k.getAttribute("format");a=a||0;Number.isFinite(a);k=Array.from(k.childNodes);k=g.A(k);for(var y=k.next();!y.done;y=k.next())if(y=y.value,y.nodeType===1)switch(y.tagName){case "head":var q=y;break;case "body":var e=y}if(q)for(q=Array.from(q.childNodes),q=g.A(q),k=q.next();!k.done;k=q.next())if(k=k.value,k.nodeType===1)switch(k.tagName){case "pen":y=k.getAttribute("id");var f=this.pens,H={},B=k.getAttribute("p");B&&Object.assign(H,this.pens[B]);B=Kd(k,"b");
B!=null&&(H.bold=B);B=Kd(k,"i");B!=null&&(H.italic=B);B=Kd(k,"u");B!=null&&(H.underline=B);B=sM(k,"et");B!=null&&(H.charEdgeStyle=B);B=sM(k,"of");B!=null&&(H.offset=B);B=AD(k,"bc");B!=null&&(H.background=B);B=AD(k,"ec");B!=null&&(H.Q4=B);B=AD(k,"fc");B!=null&&(H.color=B);B=sM(k,"fs");B!=null&&B!==0&&(H.fontFamily=B);B=DN(k,"sz");B!==void 0&&(H.fontSizeIncrement=B/100-1);B=DN(k,"bo");B!==void 0&&(H.backgroundOpacity=B/255);B=DN(k,"fo");B!==void 0&&(H.textOpacity=B/255);B=sM(k,"rb");B!=null&&B!==10&&
B!==0&&(H.Lq=B>10?B-1:B);k=sM(k,"hg");k!=null&&(H.L0=k);f[y]=H;break;case "ws":y=k.getAttribute("id");this.aj[y]=ur0(this,k);break;case "wp":y=k.getAttribute("id"),this.V[y]=Nz9(this,k)}if(e){q=[];e=Array.from(e.childNodes);e=g.A(e);for(k=e.next();!k.done;k=e.next())if(k=k.value,k.nodeType===1)switch(k.tagName){case "w":this.K=O3G(this,k,a,!1);(k=this.G[this.K.id])&&k.end>this.K.start&&(k.end=this.K.start);this.G[this.K.id]=this.K;q.push(this.K);break;case "p":var Z=k;B=a;y=[];f=Z.getAttribute("w")||
this.X;H=!!Kd(Z,"a");B=(DN(Z,"t")||0)+B;var z=DN(Z,"d")||5E3;H||(!this.N&&this.D&&this.D.windowId===f&&this.D.end>B&&(this.D.end=B),this.D&&this.D.text==="\n"&&(this.D.text=""));var Y=H?6:5,r=Z.getAttribute("p");r=r?this.pens[r]:null;var W=Array.from(Z.childNodes);W.length&&(this.N=Z.getAttribute("d")!=null);for(Z=0;Z<W.length;Z++){var m=W[Z],T=void 0;Z>0&&(H=!0);var O=void 0;m.nodeType===1&&(O=m);if(O&&O.tagName==="s"){if((m=(m=O.getAttribute("p"))?this.pens[m]:null)&&m.Lq&&(m.Lq===1?(m=W.slice(Z,
Z+4),m.length===4&&(T=wpK(B,z,f,H,Y,m,this.pens),Z+=3)):T=wpK(B,z,f,H,Y,[O],this.pens)),!T){var x=O;T=B;O=z;m=f;var V=H,l=Y,P=x.textContent?x.textContent:"",N=x.getAttribute("p");N=N?this.pens[N]:null;x=DN(x,"t")||0;T=new F7(T+x,O-x,l,m,P,V,N)}}else T=new F7(B,z,Y,f,m.textContent||"",H,r);y.push(T);this.D=T}if(y.length>0)for(y[0].windowId===this.X&&(this.K=O3G(this,k,a,!0),q.push(this.K)),k=g.A(y),y=k.next();!y.done;y=k.next())y=y.value,y.windowId=this.K.id,this.K.K.push(y),q.push(y)}a=q}else a=[];
return a};var NRK=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.I(MA,P3);MA.prototype.reset=function(){this.D.clear()};
MA.prototype.j=function(k,a){var y=JSON.parse(k);if(!y)return[];if(y.pens){k=0;for(var q=g.A(y.pens),e=q.next();!e.done;e=q.next()){e=e.value;var f={},H=e.pParentId;H&&Object.assign(f,this.K.get(H));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);H=e.ofOffset;H!=null&&(f.offset=H);e.szPenSize!==void 0&&(f.fontSizeIncrement=e.szPenSize/100-1);H=e.etEdgeType;H!=null&&(f.charEdgeStyle=H);e.ecEdgeColor!==void 0&&(f.Q4=v3(e.ecEdgeColor));H=e.fsFontStyle;H!=null&&H!==0&&(f.fontFamily=
H);e.fcForeColor!==void 0&&(f.color=v3(e.fcForeColor));e.foForeAlpha!==void 0&&(f.textOpacity=e.foForeAlpha/255);e.bcBackColor!==void 0&&(f.background=v3(e.bcBackColor));e.boBackAlpha!==void 0&&(f.backgroundOpacity=e.boBackAlpha/255);(H=e.rbRuby)&&H!==10&&(f.Lq=H>10?H-1:H,f.textEmphasis=NRK.get(f.Lq));e.hgHorizGroup&&(f.L0=e.hgHorizGroup);this.K.set(k++,f)}}if(y.wsWinStyles)for(k=0,q=g.A(y.wsWinStyles),e=q.next();!e.done;e=q.next())e=e.value,f={},(H=e.wsParentId)?Object.assign(f,this.X.get(H)):Object.assign(f,
this.N),e.mhModeHint!==void 0&&(f.Pr=e.mhModeHint),e.juJustifCode!==void 0&&(f.textAlign=e.juJustifCode),e.pdPrintDir!==void 0&&(f.Vt=e.pdPrintDir),e.sdScrollDir!==void 0&&(f.oL=e.sdScrollDir),e.wfcWinFillColor!==void 0&&(f.windowColor=v3(e.wfcWinFillColor)),e.wfoWinFillAlpha!==void 0&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.X.set(k++,f);if(y.wpWinPositions)for(k=0,q=g.A(y.wpWinPositions),e=q.next();!e.done;e=q.next())e=e.value,f={},(H=e.wpParentId)&&Object.assign(f,this.L.get(H)),e.ahHorPos!==
void 0&&(f.rU=e.ahHorPos),e.apPoint!==void 0&&(f.CY=e.apPoint),e.avVerPos!==void 0&&(f.JN=e.avVerPos),e.ccCols!==void 0&&(f.X7=e.ccCols),e.rcRows!==void 0&&(f.z0=e.rcRows),this.L.set(k++,f);if(y.events){k=[];y=g.A(y.events);for(q=y.next();!q.done;q=y.next()){var B=q.value;e=(B.tStartMs||0)+a;f=B.dDurationMs||0;if(B.id)H=String(B.id),q=v79(this,B,e,f,H),k.push(q),this.D.set(H,q);else{B.wWinId?H=B.wWinId.toString():(H="_"+g$++,q=v79(this,B,e,f,H),k.push(q),this.D.set(H,q));q=k;var Z=B;f===0&&(f=5E3);
B=this.D.get(H);var z=!!Z.aAppend,Y=z?6:5,r=Z.segs,W=null;Z.pPenId&&(W=this.K.get(Z.pPenId));for(Z=0;Z<r.length;Z++){var m=r[Z],T=m.utf8;if(T){var O=m.tOffsetMs||0,x=null;m.pPenId&&(x=this.K.get(m.pPenId));if((B.params.Pr!=null?B.params.Pr:B.K.length>1?1:0)===2&&z&&T==="\n")continue;m=null;var V=[],l;if(l=x&&x.Lq===1){l=r;var P=Z;if(P+3>=l.length||!l[P+1].pPenId||!l[P+2].pPenId||!l[P+3].pPenId)l=!1;else{var N=l[P+1].pPenId;(N=this.K.get(N))&&N.Lq&&N.Lq===2?(N=l[P+2].pPenId,N=this.K.get(N),!N||!N.Lq||
N.Lq<3?l=!1:(N=l[P+3].pPenId,l=(N=this.K.get(N))&&N.Lq&&N.Lq===2?!0:!1)):l=!1}}if(l)O=r[Z+1].utf8,m=r[Z+3].utf8,l=r[Z+2].utf8,P=this.K.get(r[Z+2].pPenId),T=Q6r(T,O,l,m,P),m=new F7(e,f,Y,H,T,z,x),Z+=3;else{if(T.indexOf("<")>-1){var F=void 0;V=x;l=W;P=e;N=f;var t=O,M=Y,ea=z,Zl=[],fG=g.uf("<html>"+T+"</html>");if(!fG.getElementsByTagName("parsererror").length&&((F=fG.firstChild)==null?0:F.childNodes.length))for(F=g.A(fG.firstChild.childNodes),fG=F.next();!fG.done;fG=F.next()){fG=fG.value;var r4=void 0,
a3=void 0,OZ=(a3=(r4=fG.textContent)==null?void 0:r4.replace(/\n/g,""))!=null?a3:"";if(fG.nodeType!==3||OZ&&OZ.match(/^ *$/)==null){r4={};Object.assign(r4,V||l);a3=void 0;switch((a3=fG)==null?void 0:a3.tagName){case "b":r4.bold=!0;break;case "i":r4.italic=!0;break;case "u":r4.underline=!0}Zl.push(new F7(P+t,N-t,M,B.id,OZ,ea,r4))}}V=Zl}V.length||(V=[new F7(e+O,f-O,Y,B.id,T,z,x||W)])}if(V.length)for(z=g.A(V),x=z.next();!x.done;x=z.next())x=x.value,q.push(x),B.K.push(x);else m&&(q.push(m),B.K.push(m))}z=
!0}}}a=k}else a=[];return a};g.I(X7,g.H2);X7.prototype.SV=function(k,a,y){La9(this.videoData.videoId,k.vssId,y.h0)};
X7.prototype.W5=function(k){if(this.audioTrack)for(var a=g.A(this.audioTrack.captionTracks),y=a.next();!y.done;y=a.next())g.Um(this.D,y.value);k.YH()};g.I(nd,NA);nd.prototype.hR=function(k){var a=this.D.K;NA.prototype.hR.call(this,k);for(k=k.length;k<a.length;k++){var y=a[k];if(f&&y.K===e)var q=f;else{q={};Object.assign(q,y.K);Object.assign(q,ui0);var e=y.K;var f=q}dfa(this,y,q)}};
var ui0={UE:!0};g.I(w$,$02);w$.prototype.L=function(k,a,y,q,e){if(y<q){var f="_"+g$++;y=y/1E3-this.N;q=q/1E3-this.N;k=new bT(y,q-y,5,f,{textAlign:0,CY:0,rU:a*2.5,JN:k*5.33});e=new F7(y,q-y,5,f,e);this.D.push(k);this.D.push(e)}};
g.I(Im,P3);Im.prototype.j=function(k){k=new w$(k,k.byteLength,this.D);if(GG9(k)){for(;k.byteOffset<k.K.byteLength;)for(k.version===0?k.j=tD(k)*(1E3/45):k.version===1&&(k.j=tD(k)*4294967296+tD(k)),k.X=EM(k);k.X>0;k.X--){var a=EM(k),y=EM(k),q=EM(k);a&4&&(a&3)===this.track&&(this.track===0||this.track===1)&&(a=this.K,a.K.push({time:k.j,type:this.track,ZP:y,Or:q,order:a.K.length}))}Jnr(this.K,k);return k.D}return[]};
Im.prototype.reset=function(){this.K.clear()};g.I(JD,NA);g.S=JD.prototype;g.S.jk=function(){g.VT(this.jw)};
g.S.cw=function(){this.element.removeEventListener("transitionend",this.cw,!1);g.MF(this.element,"ytp-rollup-mode");this.yy(this.mO,!0)};
g.S.wP=function(){return this.j?this.Kw:this.V};
g.S.C4=function(){return this.j?this.V:this.Kw};
g.S.yy=function(k,a){this.mO=k;if(this.D.params.z0){for(var y=0,q=0;q<this.N.length&&y<k.length;q++)this.N[q]===k[y]&&y++;y>0&&y<k.length&&(k=this.N.concat(k.slice(y)));this.ub=this.Kw;this.V=this.Kw=0;NA.prototype.yy.call(this,k);qc9(this,a)}NA.prototype.yy.call(this,k)};gLd.prototype.unload=function(){this.K!=null&&(this.J.removeEventListener("sabrCaptionsDataLoaded",this.K),this.K=null);this.u_=[];this.J.publish("sabrCaptionsBufferedRangesUpdated",this.u_)};
gLd.prototype.FM=function(k){return{formatId:g.wI(k.info.K.info,this.dk),Wz:k.info.Wz+(this.dk?0:1),startTimeMs:k.info.X*1E3,durationMs:k.info.V*1E3}};g.I(Ld,g.H2);Ld.prototype.SV=function(k,a,y){this.cS();a=k.getId();a=a!=null&&a in this.K.K?this.K.K[a]:null;a||(a=k.languageCode,a=this.K.isManifestless?AFd(this,a,"386"):AFd(this,a));a&&(this.L=k,this.N=a,VqG(this.G,y),this.J.publish("sabrCaptionsTrackChanged",g.wI(a.info,this.K.dk)))};
Ld.prototype.W5=function(k){var a=this.K.isManifestless?JFd(this,"386"):JFd(this);a=g.A(a);for(var y=a.next();!y.done;y=a.next())g.Um(this.D,y.value);k.YH()};
Ld.prototype.cS=function(){this.L&&(this.L=this.N=null,this.G.unload(),this.J.publish("sabrCaptionsTrackChanged",null))};
Ld.prototype.F7=function(){return""};var b3G="WEBVTT".split("").map(function(k){return k.charCodeAt(0)});
g.I(yn9,P3);
yn9.prototype.j=function(k,a){k instanceof ArrayBuffer&&(k=g.HT(new Uint8Array(k)));var y=[];k=k.split(vLr);for(var q=1;q<k.length;q++){var e=k[q],f=a;if(e!==""&&!FYV.test(e)){var H=oLV.exec(e);if(H&&H.length>=4){var B=RZX(H[1]),Z=RZX(H[2])-B;B+=f;var z=(H=H[3])?H.split(" "):[];H={};var Y=null;var r="";var W=null,m="";z=g.A(z);for(var T=z.next();!T.done;T=z.next())if(T=T.value.split(":"),T.length===2){var O=T[1];switch(T[0]){case "line":T=O.split(",");T[0].endsWith("%")&&(Y=T[0],H.JN=Number.parseInt(Y,
10),T.length===2&&(r=T[1].trim()));break;case "position":T=O.split(",");W=T[0];H.rU=Number.parseInt(W,10);T.length===2&&(m=T[1].trim());break;case "align":switch(O){case "start":H.textAlign=0;break;case "middle":H.textAlign=2;break;case "end":H.textAlign=1}}}Y||r||(r="end");if(!W)switch(H.textAlign){case 0:H.rU=0;break;case 1:H.rU=100;break;case 2:H.rU=50}if(H.textAlign!=null){Y=0;switch(r){case "center":Y+=3;break;case "end":Y+=6;break;default:Y+=0}switch(m){case "line-left":Y+=0;break;case "center":Y+=
1;break;case "line-right":Y+=2;break;default:switch(H.textAlign){case 0:Y+=0;break;case 2:Y+=1;break;case 1:Y+=2}}r=Y<0||Y>8?7:Y;H.CY=r}e=e.substring(oLV.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");m=H;H=e;e={};if(H.indexOf("<")<0&&H.indexOf("&")<0)f=pVG(B,Z,5,m),Z=new F7(B,Z,5,f.id,H,!1,g.SV(e)?void 0:e),y.push(f),y.push(Z),f.K.push(Z);else for(r=H.split(CYr),r.length===1?(H=5,m=pVG(B,Z,H,m)):(Y=H=6,m=Object.assign({X7:32},m),m=new bT(B,Z,Y,"_"+g$++,m)),y.push(m),Y=B,W=0;W<r.length;W++)z=r[W],
W%2===0?(T=g.uf("<html>"+z+"</html>"),T.getElementsByTagName("parsererror").length?(O=T.createElement("span"),O.appendChild(T.createTextNode(z))):O=T.firstChild,s6a(this,Y,Z-(Y-B),H,m,W>0,O,e,y)):Y=RZX(z)+f}oLV.lastIndex=0}}return y};
var FYV=/^NOTE/,vLr=/(?:\r\n|\r|\n){2,}/,oLV=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),CYr=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.I(x$,g.C);x$.prototype.clear=function(){this.K&&this.K.dispose();this.K=null};
x$.prototype.reset=function(){this.K&&this.K.reset()};
x$.prototype.uj=function(){g.C.prototype.uj.call(this);this.clear()};var SE={windowColor:"#080808",windowOpacity:0,textAlign:2,CY:7,rU:50,JN:100,isDefault:!0,bY:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.I(xfr,g.pF);g.S=xfr.prototype;g.S.uj=function(){if(this.X||this.JG){var k=this.J.qN();k&&!k.xs()&&k.dZ()}else D09(this,!1);g.pF.prototype.uj.call(this)};
g.S.St=function(){return this.B.W("html5_honor_caption_availabilities_in_audio_track")&&this.L!=="LIVE"&&this.L!=="SABR_LIVE"};
g.S.EF=function(){if(this.hG)return this.X||this.JG;var k=this.getAudioTrack();if(this.St()){if(!k.captionTracks.length)return!1;if(!this.K)return!0}k=eLX(k,g.ry(this.B));return k==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:k==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?jE(this):Mf9(this)||jE(this)?!0:XVK(this)};
g.S.load=function(){g.pF.prototype.load.call(this);this.aj=this.getAudioTrack();if(this.K)this.D&&(this.Zq.clear(),this.X?FaG(this,!0):this.player.getPresentingPlayerType()!==3&&this.K.SV(this.D,"json3",this.jw),this.X||this.JG||pd(this)||this.player.vu("captionschanged",g.AI(this.D)));else{var k;this.L==="OFFLINE"?k=new X7(this.player,this.videoData,this.getAudioTrack()):this.L==="SABR_LIVE"?k=new Ld(this.videoData.K,this.player):this.L==="LIVE"?k=new c3(this.videoData.K,this.player):this.L==="INNERTUBE"?
k=new g.ZC(this.player,this.videoData,this.getAudioTrack()):k=new g.u4(this.player,this.videoData.eb,this.videoData.videoId,g.mZD(this.videoData),this.videoData.a7,this.videoData.eventId);this.K=k;g.U(this,this.K);this.K.W5(this.jw)}};
g.S.unload=function(){this.X&&this.D?FaG(this,!1):(this.sY&&g.MI(this.sY),this.player.J_("captions"),this.NE=[],this.K&&this.K.cS(),this.Zq.clear(),this.Kw&&this.player.RY(this.Kw),this.h9());g.pF.prototype.unload.call(this);this.player.Mh();this.player.vu("captionschanged",{})};
g.S.create=function(){this.EF()&&this.load();var k;a:{var a,y,q;if(this.B.W("web_player_nitrate_promo_tooltip")&&((a=this.videoData.getPlayerResponse())==null?0:(y=a.captions)==null?0:(q=y.playerCaptionsTracklistRenderer)==null?0:q.enableTouchCaptionsNitrate)){var e,f;if(a=(k=this.videoData.getPlayerResponse())==null?void 0:(e=k.captions)==null?void 0:(f=e.playerCaptionsTracklistRenderer)==null?void 0:f.captionTracks)for(k=g.A(a),e=k.next();!e.done;e=k.next())if(e=e.value,e.kind==="asr"&&e.languageCode===
"en"){k=!0;break a}}k=!1}k&&this.J.publish("showpromotooltip",this.G.element)};
g.S.YH=function(){var k=eLX(this.player.getAudioTrack(),g.ry(this.B));var a=k==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?Td(this,this.V):k==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&jE(this)?iT(this):Mf9(this)||this.V||XVK(this)?Td(this,this.V):jE(this)?iT(this):null;if(this.X||this.JG){var y=g.nF(this.K.D,!0);k=[];for(var q=0;q<y.length;q++){var e=y[q],f=g.d9("TRACK");f.setAttribute("kind","subtitles");f.setAttribute("label",g.sg(e));f.setAttribute("srclang",g.hW(e));f.setAttribute("id",e.toString());
this.JG||f.setAttribute("src",this.K.F7(e,"vtt"));e===a&&f.setAttribute("default","1");k.push(f)}a=this.J.qN();a.Yt(k);k=a.XR();this.au&&this.cz.Y(k.textTracks,"change",this.O7q)}else!this.D&&a&&W3(this,a),this.player.vu("onCaptionsTrackListChanged"),this.player.I4("onApiChange")};
g.S.O7q=function(){for(var k=this.J.qN().XR().textTracks,a=null,y=0;y<k.length;y++)if(k[y].mode==="showing")a:{a=g.nF(this.K.D,!0);for(var q=0;q<a.length;q++)if(a[q].toString()===k[y].id){a=a[q];break a}a=null}(this.loaded?this.D:null)!==a&&W3(this,a,!0)};
g.S.mg5=function(){!this.D&&this.X||this.unload()};
g.S.h0=function(k,a,y,q){if(k){var e;a2a(this,(e=this.D)!=null?e:void 0);this.K.q6()&&(this.NE=[],this.J.J_("captions"),mt(this.Ij),this.Zq.reset());a:{e=this.Zq;q=q||0;y=kGX(e,k,y||0);k=[];try{for(var f=g.A(y),H=f.next();!H.done;H=f.next()){var B=H.value,Z=B.trackData,z=B.ym,Y=e.B.W("safari_live_drm_captions_fix");if(typeof Z!=="string"){y=k;var r=y.concat;if(Y&&E7V(Z))var W=q_a(e,Z,z);else{var m=e,T=a,O=Z,x=z,V=q;if(!tf9(O))throw Error("Invalid binary caption track data");m.K||(m.K=new Im(V,T));
W=m.K.j(O,x)}var l=r.call(y,W)}else{if(Z.substring(0,6)==="WEBVTT")var P=k.concat(q_a(e,Z,z));else{y=k;var N=y.concat;b:{T=m=void 0;O=e;x=a;if(Z[0]==="{")try{O.K||(O.K=new MA(H3V(x)));var F=T=O.K.j(Z,z);break b}catch(a3){g.kh(a3);F=[];break b}var t=g.uf(Z);if(!t||!t.firstChild){var M=Error("Invalid caption track data");M.params=Z;throw M;}if(t.firstChild.tagName==="timedtext"){if(Number(t.firstChild.getAttribute("format"))===3){O.K||(O.K=new hD(H3V(x),O.B));F=m=O.K.j(t,z);break b}var ea=Error("Unsupported subtitles format in web player (Format2)");
ea.params=Z;throw ea;}if(t.firstChild.tagName==="transcript"){var Zl=Error("Unsupported subtitles format in web player (Format1)");Zl.params=Z;throw Zl;}var fG=Error("Invalid caption track data");fG.params=Z;throw fG;}P=N.call(y,F)}l=P}k=l}var r4=k;break a}catch(a3){g.VR(e.logger,187101178,"Captions parsing failed: "+a3.message+". ");e.clear();r4=[];break a}r4=void 0}a=r4;a.length>0&&(r4=this.D,this.HA(r4,!!r4,pd(this)?"g":this.V?"m":"s"));this.player.RY(a,void 0,this.L==="LIVE"||this.L==="SABR_LIVE");
!this.V||this.JG||pd(this)||g.i9(this.B)||g.Ti(this.B)||g.mi(this.B)||this.B.cz==="shortspage"||this.player.isInline()||(g.MI(this.sY),a=WYX({CY:0,rU:5,JN:5,z0:2,textAlign:0,Vt:0,lang:"en"}),this.tG=[a],r4=["Click "," for settings"],this.ME||(f=new g.G1(g.YC()),g.U(this,f),this.ME=f.element),f=a.end-a.start,(H=g.sg(this.D))&&this.tG.push(new F7(a.start,f,0,a.id,H)),this.tG.push(new F7(a.start,f,0,a.id,r4[0]),new F7(a.start,f,0,a.id,this.ME,!0),new F7(a.start,f,0,a.id,r4[1],!0)),this.player.RY(this.tG),
g.rD(this.sY));!this.V||this.JG||pd(this)||(g.ry(this.B)?Y$(this,!0):r$(this,!0),this.aj&&(this.aj.L=this.D),this.player.Mh());this.V=!1}};
g.S.onCueRangeEnter=function(k){this.NE.push(k);mt(this.Ij)};
g.S.onCueRangeExit=function(k){g.d2(this.NE,k);this.K instanceof c3&&this.K.G&&this.player.M8([k]);mt(this.Ij)};
g.S.getCaptionWindowContainerId=function(){return this.G.element.id};
g.S.Onw=function(){U0d(this,this.tG);this.tG=null};
g.S.UI=function(){var k=this;if(!this.ub||!this.X){this.Ij.stop();g.BJG(this.ge);this.NE.sort(g.tH8);var a=this.NE;if(this.Kw){var y=g.yv(a,function(f){return this.Kw.indexOf(f)===-1},this);
y.length&&(a=y)}a=g.A(a);for(y=a.next();!y.done;y=a.next())PY9(this,y.value);a=g.A(Object.entries(this.Lw));var q=a.next();for(y={};!q.done;y={WW:void 0,rC:void 0},q=a.next()){var e=g.A(q.value);q=e.next().value;e=e.next().value;y.WW=q;y.rC=e;this.ge[y.WW]?(y.rC.element.parentNode||(y.rC instanceof JD||y.rC instanceof nd||g.ra(this.Lw,function(f){return function(H,B){B!==f.WW&&H.D.params.CY===f.rC.D.params.CY&&H.D.params.rU===f.rC.D.params.rU&&H.D.params.JN===f.rC.D.params.JN&&(H.dispose(),delete k.Lw[B]);
return B===f.WW}}(y),this),this.G.element.appendChild(y.rC.element)),y.rC.yy(this.ge[y.WW])):(y.rC.dispose(),delete this.Lw[y.WW])}}};
g.S.Q4e=function(){S_d(this,{},!0);this.player.vu("captionssettingschanged")};
g.S.fm=function(){var k=SE.bY;k={background:k.background,backgroundOpacity:k.backgroundOpacity,charEdgeStyle:k.charEdgeStyle,color:k.color,fontFamily:k.fontFamily,fontSizeIncrement:k.fontSizeIncrement,fontStyle:k.bold&&k.italic?3:k.bold?1:k.italic?2:0,textOpacity:k.textOpacity,windowColor:SE.windowColor,windowOpacity:SE.windowOpacity};var a=wVd()||{};a.background!=null&&(k.background=a.background);a.backgroundOverride!=null&&(k.backgroundOverride=a.backgroundOverride);a.backgroundOpacity!=null&&(k.backgroundOpacity=
a.backgroundOpacity);a.backgroundOpacityOverride!=null&&(k.backgroundOpacityOverride=a.backgroundOpacityOverride);a.charEdgeStyle!=null&&(k.charEdgeStyle=a.charEdgeStyle);a.charEdgeStyleOverride!=null&&(k.charEdgeStyleOverride=a.charEdgeStyleOverride);a.color!=null&&(k.color=a.color);a.colorOverride!=null&&(k.colorOverride=a.colorOverride);a.fontFamily!=null&&(k.fontFamily=a.fontFamily);a.fontFamilyOverride!=null&&(k.fontFamilyOverride=a.fontFamilyOverride);a.fontSizeIncrement!=null&&(k.fontSizeIncrement=
a.fontSizeIncrement);a.fontSizeIncrementOverride!=null&&(k.fontSizeIncrementOverride=a.fontSizeIncrementOverride);a.fontStyle!=null&&(k.fontStyle=a.fontStyle);a.fontStyleOverride!=null&&(k.fontStyleOverride=a.fontStyleOverride);a.textOpacity!=null&&(k.textOpacity=a.textOpacity);a.textOpacityOverride!=null&&(k.textOpacityOverride=a.textOpacityOverride);a.windowColor!=null&&(k.windowColor=a.windowColor);a.windowColorOverride!=null&&(k.windowColorOverride=a.windowColorOverride);a.windowOpacity!=null&&
(k.windowOpacity=a.windowOpacity);a.windowOpacityOverride!=null&&(k.windowOpacityOverride=a.windowOpacityOverride);return k};
g.S.q9=function(k,a){var y={};Object.assign(y,wVd());Object.assign(y,k);S_d(this,y,a);this.player.vu("captionssettingschanged")};
g.S.h9=function(){!this.X&&this.loaded&&(g.IX(this.Lw,function(k,a){k.dispose();delete this.Lw[a]},this),this.UI())};
g.S.S2=function(k,a){switch(k){case "fontSize":if(isNaN(a))break;k=g.nz(a,-2,4);this.q9({fontSizeIncrement:k});return k;case "reload":a&&!this.X&&W3(this,this.D,!0);break;case "stickyLoading":a!==void 0&&this.B.V&&(g.ry(this.B)?Y$(this,!!a):r$(this,!!a));break;case "track":return eZ1(this,a);case "tracklist":return this.K?g.Bh(g.nF(this.K.D,!(!a||!a.includeAsr)),function(y){return g.AI(y)}):[];
case "translationLanguages":return this.K?this.K.X.map(function(y){return Object.assign({},y)}):[];
case "sampleSubtitles":this.X||a===void 0||D09(this,!!a);break;case "sampleSubtitlesCustomized":this.X||D09(this,!!a,a);break;case "recommendedTranslationLanguages":return g.WN();case "defaultTranslationSourceTrackIndices":return this.K?this.K.V:[]}};
g.S.getOptions=function(){var k="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.B.V&&k.push("stickyLoading");return k};
g.S.VP=function(){var k=this.D;if(this.J.BS("captions")){if(this.B.W("html5_modify_caption_vss_logging")){var a;return(k=(a=this.videoData.C6)!=null?a:null)?{cc:g.lul(k)}:{}}if(k)return a=k.vssId,k.translationLanguage&&a&&(a="t"+a+"."+g.hW(k)),{cc:a}}return{}};
g.S.j_3=function(){this.isSubtitlesOn()?(g.ry(this.B)?Y$(this,!1):r$(this,!1),a2a(this),W3(this,null,!0)):this.eJ()};
g.S.eJ=function(){var k=pd(this)||!this.D?Td(this,!0):this.D;k&&this.F6(k.vssId,"m");this.isSubtitlesOn()||W3(this,pd(this)||!this.D?Td(this,!0):this.D,!0)};
g.S.isSubtitlesOn=function(){return!!this.loaded&&!!this.D&&!pd(this)};
g.S.wOz=function(){var k=pd(this);jE(this,k)?W3(this,this.getAudioTrack().K,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.St()&&(this.V=!1,this.D=null,this.K&&(this.K.dispose(),this.K=null)),this.EF()&&(k?W3(this,Td(this,!1),!1):this.load()))};
g.S.JX=function(k){k&&(this.vz={top:k.top,right:k.right,bottom:k.bottom,left:k.left,width:1-k.left-k.right,height:1-k.top-k.bottom},this.G.element.style.top=this.vz.top*100+"%",this.G.element.style.left=this.vz.left*100+"%",this.G.element.style.width=this.vz.width*100+"%",this.G.element.style.height=this.vz.height*100+"%",this.G.element.style.position="absolute",k=sMa(this))&&(this.G.element.style.width=k.width+"px",this.G.element.style.height=k.height+"px")};
g.S.onVideoDataChange=function(k,a){k==="newdata"&&(this.videoData=a,this.loaded&&this.unload(),this.V=!1,this.D=null,this.K&&(this.K.dispose(),this.K=null,this.player.vu("captionschanged",{})),this.EF()&&this.load())};
g.S.getAudioTrack=function(){return this.player.getAudioTrack()};
g.S.BkY=function(){var k=this.J.qN();k&&!k.xs()&&k.dZ();this.J.isFullscreen()?(this.X=this.hG=!0,this.loaded&&this.YH()):(this.hG=this.B.controlsType==="3",this.X=QM9(this));W3(this,this.D)};
g.S.Ut=function(){var k,a,y,q=(k=this.videoData.getPlayerResponse())==null?void 0:(a=k.captions)==null?void 0:(y=a.playerCaptionsTracklistRenderer)==null?void 0:y.openTranscriptCommand;q&&this.player.qE("innertubeCommand",q)};
g.S.HA=function(k,a,y){var q=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,e="";k&&(e=k.vssId,e=e.replace(q,""));var f="";k&&k.getId()&&(f=k.getId()||"");k&&k.getXtags()&&(k=k.getXtags(),k=k.replace(q,""),f=f.concat(";"+k));this.J.HA(a?e:"",a?f:"",y)};
g.S.F6=function(k,a){k=(k||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");k.length>0&&this.J.F6(k,a)};g.ht("captions",xfr);})(_yt_player);
