(function(g){var window=this;'use strict';var iWr=function(k){k.player.J_("endscreen");var a=k.player.getVideoData();a=new g.Uc(Math.max((a.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var y=new g.Uc(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});k.player.RY([a,y])},Hc=function(k){var a=k.Z(),y=a.L;
g.u.call(this,{C:"a",T:"ytp-autonav-suggestion-card",U:{href:"{{url}}",target:y?a.aj:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},S:[{C:"div",nw:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],U:{style:"{{background}}"},S:[{C:"div",U:{"aria-label":"{{timestamp}}"},nw:["ytp-autonav-timestamp"],Dq:"{{duration}}"},{C:"div",nw:["ytp-autonav-live-stamp"],Dq:"Live"},{C:"div",
nw:["ytp-autonav-upcoming-stamp"],Dq:"Upcoming"},{C:"div",T:"ytp-autonav-list-overlay",S:[{C:"div",T:"ytp-autonav-mix-text",Dq:"Mix"},{C:"div",T:"ytp-autonav-mix-icon"}]}]},{C:"div",nw:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],Dq:"{{title}}"},{C:"div",nw:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],Dq:"{{author}}"},{C:"div",nw:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],Dq:"{{views_and_publish_time}}"}]});this.J=k;this.suggestion=
null;this.K=y;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},WW9=function(k){dh.call(this,k,"videowall-endscreen");
var a=this;this.J=k;this.stills=[];this.j=this.videoData=null;this.L=this.N=!1;this.G=null;g.C7(this.element,"modern-videowall-endscreen");this.D=new g.e9(this);g.U(this,this.D);this.X=new g.gD(function(){g.C7(a.element,"ytp-show-tiles")},0);
g.U(this,this.X);this.table=new g.G1({C:"div",T:"ytp-modern-endscreen-content"});g.U(this,this.table);this.table.pw(this.element);k.getVideoData().rJ?this.K=new Bc(k,!0):this.K=new ZJ(k);g.U(this,this.K);g.ED(this.player,this.K.element,4);k.createClientVe(this.element,this,158789);this.hide()},mI2=function(k){dh.call(this,k,"subscribecard-endscreen");
this.K=new g.u({C:"div",T:"ytp-subscribe-card",S:[{C:"img",T:"ytp-author-image",U:{src:"{{profilePicture}}"}},{C:"div",T:"ytp-subscribe-card-right",S:[{C:"div",T:"ytp-author-name",Dq:"{{author}}"},{C:"div",T:"html5-subscribe-button-container"}]}]});g.U(this,this.K);this.K.pw(this.element);var a=k.getVideoData();this.subscribeButton=new g.yD("Subscribe",null,"Unsubscribe",null,!0,!1,a.BC,a.subscribed,"trailer-endscreen",null,k,!1);g.U(this,this.subscribeButton);this.subscribeButton.pw(this.K.ij("html5-subscribe-button-container"));
this.Y(k,"videodatachange",this.GF);this.GF();this.hide()},Tn9=function(k){if(k.J.isFullscreen()){var a;
k=(a=k.J.getVideoData())==null?void 0:a.Uk;return k===-1||k===void 0?8E3:k}return k.J.tY()>=0?k.J.tY():g.Ht(k.J.Z().experiments,"autoplay_time")||1E4},zr=function(k){dh.call(this,k,"videowall-endscreen");
var a=this;this.J=k;this.j=0;this.stills=[];this.L=this.videoData=null;this.X=this.G=!1;this.V=null;this.D=new g.e9(this);g.U(this,this.D);this.N=new g.gD(function(){g.C7(a.element,"ytp-show-tiles")},0);
g.U(this,this.N);var y=new g.u({C:"button",nw:["ytp-button","ytp-endscreen-previous"],U:{"aria-label":"Previous"},S:[g.jt()]});g.U(this,y);y.pw(this.element);y.listen("click",this.xG,this);this.table=new g.G1({C:"div",T:"ytp-endscreen-content"});g.U(this,this.table);this.table.pw(this.element);y=new g.u({C:"button",nw:["ytp-button","ytp-endscreen-next"],U:{"aria-label":"Next"},S:[g.g7()]});g.U(this,y);y.pw(this.element);y.listen("click",this.df,this);k.getVideoData().rJ?this.K=new Bc(k,!0):this.K=
new ZJ(k);g.U(this,this.K);g.ED(this.player,this.K.element,4);k.createClientVe(this.element,this,158789);this.hide()},YW=function(k){dh.call(this,k,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.u({C:"div",T:"ytp-suggestion-panel",S:[{C:"div",nw:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],Dq:"More videos"}]});this.G=new g.u({C:"div",T:"ytp-suggestions-container"});this.videos=[];this.j=null;this.X=this.N=!1;this.D=new Bc(this.player);g.U(this,this.D);this.D.pw(this.element);k.getVideoData().rJ?this.K=this.D:(this.K=new ZJ(k),g.ED(this.player,this.K.element,4),g.U(this,this.K));this.overlay=new g.u({C:"div",
T:"ytp-autonav-overlay-cancelled-state"});g.U(this,this.overlay);this.overlay.pw(this.element);this.L=new g.e9(this);g.U(this,this.L);g.U(this,this.table);this.table.pw(this.element);this.table.show();g.U(this,this.G);this.G.pw(this.table.element);this.hide()},UId=function(k,a){a=Sd9(k,a);
var y=Math,q=y.min;var e=(0,g.Bi)()-k.D;y=q.call(y,e,a);a=a===0?1:Math.min(y/a,1);k.X.setAttribute("stroke-dashoffset",""+-211*(a+1));a>=1&&k.sR()&&k.api.getPresentingPlayerType()!==3?k.select(!0):k.sR()&&k.K.start()},DIK=function(k){var a,y,q;
return k==null?void 0:(a=k.playerOverlays)==null?void 0:(y=a.playerOverlayRenderer)==null?void 0:(q=y.autoplay)==null?void 0:q.playerOverlayAutoplayRenderer},OW1=function(k,a){k.qE("onAutonavCoundownStarted",a)},Sd9=function(k,a){if(a)return a;
if(k.api.isFullscreen()){var y;k=(y=k.api.getVideoData())==null?void 0:y.Uk;return k===-1||k===void 0?8E3:k}return k.api.tY()>=0?k.api.tY():g.Ht(k.api.Z().experiments,"autoplay_time")||1E4},rh=function(k){var a=k.Z(),y=g.eP||g.s4?{style:"will-change: opacity"}:void 0,q=a.L,e=["ytp-videowall-still"];
a.D&&e.push("ytp-videowall-show-text");g.u.call(this,{C:"a",nw:e,U:{href:"{{url}}",target:q?a.aj:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},S:[{C:"div",T:"ytp-videowall-still-image",U:{style:"{{background}}"}},{C:"span",T:"ytp-videowall-still-info",U:{"aria-hidden":"true"},S:[{C:"span",T:"ytp-videowall-still-info-bg",S:[{C:"span",T:"ytp-videowall-still-info-content",U:y,S:[{C:"span",T:"ytp-videowall-still-info-title",Dq:"{{title}}"},
{C:"span",T:"ytp-videowall-still-info-author",Dq:"{{author_and_views}}"},{C:"span",T:"ytp-videowall-still-info-live",Dq:"Live"},{C:"span",T:"ytp-videowall-still-info-duration",Dq:"{{duration}}"}]}]}]},{C:"span",nw:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],U:{"aria-hidden":"true"},S:[{C:"span",T:"ytp-videowall-still-listlabel-icon"},"Playlist",{C:"span",T:"ytp-videowall-still-listlabel-length",S:[" (",{C:"span",Dq:"{{playlist_length}}"},")"]}]},{C:"span",nw:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],U:{"aria-hidden":"true"},S:[{C:"span",T:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{C:"span",T:"ytp-videowall-still-listlabel-length",Dq:" (50+)"}]}]});this.suggestion=null;this.D=q;this.api=k;this.K=new g.e9(this);g.U(this,this.K);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.K.Y(k,"videodatachange",this.onVideoDataChange);k.createServerVe(this.element,this);this.onVideoDataChange()},ji=function(k){var a=k.DA();
a!==k.N&&(k.N=a,QZX(k.player))},wm9=function(k){var a;
return!((a=k.J.getVideoData())==null||!a.watchToWatchTransitionRenderer)},i1=function(k){var a=k.J.TC(!0,k.J.isFullscreen());
g.iM(k.container.element,"ytp-autonav-endscreen-small-mode",k.O_(a));g.iM(k.container.element,"ytp-autonav-endscreen-is-premium",!!k.suggestion&&!!k.suggestion.hIj);g.iM(k.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!k.J.DA());g.iM(k.J.getRootNode(),"countdown-running",k.sR());g.iM(k.container.element,"ytp-player-content",k.J.DA());g.tO(k.overlay.element,{width:a.width+"px"});if(!k.sR()){k.J.DA()?xId(k,Math.round(Tn9(k)/1E3)):xId(k);a=!!k.suggestion&&!!k.suggestion.jT;var y=k.J.DA()||
!a;g.iM(k.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!y&&a);g.iM(k.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",y&&!a);k.D.h3(k.J.DA());g.iM(k.element,"ytp-enable-w2w-color-transitions",wm9(k))}},Wc=function(k){return g.L4(k.player)&&k.DR()&&!k.j},Bc=function(k,a){a=a===void 0?!1:a;
g.u.call(this,{C:"div",T:"ytp-autonav-endscreen-countdown-overlay"});var y=this;this.N=a;this.cancelCommand=this.X=void 0;this.j=0;this.container=new g.u({C:"div",T:"ytp-autonav-endscreen-countdown-container"});g.U(this,this.container);this.container.pw(this.element);a=k.Z();var q=a.L;this.J=k;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.Y(k,"videodatachange",this.onVideoDataChange);this.K=new g.u({C:"div",T:"ytp-autonav-endscreen-upnext-container",U:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},S:[{C:"div",T:"ytp-autonav-endscreen-upnext-header"},{C:"div",T:"ytp-autonav-endscreen-upnext-alternative-header",Dq:"{{autoplayAlternativeHeader}}"},{C:"a",T:"ytp-autonav-endscreen-link-container",U:{href:"{{url}}",target:q?a.aj:""},S:[{C:"div",T:"ytp-autonav-endscreen-upnext-thumbnail",U:{style:"{{background}}"},S:[{C:"div",U:{"aria-label":"{{timestamp}}"},nw:["ytp-autonav-timestamp"],
Dq:"{{duration}}"},{C:"div",nw:["ytp-autonav-live-stamp"],Dq:"Live"},{C:"div",nw:["ytp-autonav-upcoming-stamp"],Dq:"Upcoming"}]},{C:"div",T:"ytp-autonav-endscreen-video-info",S:[{C:"div",T:"ytp-autonav-endscreen-premium-badge"},{C:"div",T:"ytp-autonav-endscreen-upnext-title",Dq:"{{title}}"},{C:"div",T:"ytp-autonav-endscreen-upnext-author",Dq:"{{author}}"},{C:"div",T:"ytp-autonav-view-and-date",Dq:"{{views_and_publish_time}}"},{C:"div",T:"ytp-autonav-author-and-view",Dq:"{{author_and_views}}"}]}]}]});
g.U(this,this.K);this.K.pw(this.container.element);q||this.Y(this.K.ij("ytp-autonav-endscreen-link-container"),"click",this.sz);this.J.createClientVe(this.container.element,this,115127);this.J.createClientVe(this.K.ij("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.u({C:"div",T:"ytp-autonav-overlay"});g.U(this,this.overlay);this.overlay.pw(this.container.element);this.D=new g.u({C:"div",T:"ytp-autonav-endscreen-button-container"});g.U(this,this.D);this.D.pw(this.container.element);
this.cancelButton=new g.u({C:"button",nw:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",a.W("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],U:{"aria-label":"Cancel autoplay"},Dq:"Cancel"});g.U(this,this.cancelButton);this.cancelButton.pw(this.D.element);this.cancelButton.listen("click",this.pA,this);this.J.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.u({C:"a",nw:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
a.W("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],U:{href:"{{url}}",role:"button","aria-label":"Play next video"},Dq:"Play Now"});g.U(this,this.playButton);this.playButton.pw(this.D.element);this.playButton.listen("click",this.sz,this);this.J.createServerVe(this.playButton.element,this.playButton,!0);(a=this.J.getVideoData())&&RX9(this,a);this.L=new g.gD(function(){GUK(y)},500);
g.U(this,this.L);this.x7();this.Y(k,"autonavvisibility",this.x7);this.J.W("web_autonav_color_transition")&&(this.Y(k,"autonavchange",this.Jm),this.Y(k,"onAutonavCoundownStarted",this.Cbw))},m6=function(k){var a=k.DA();
a!==k.X&&(k.X=a,QZX(k.player),k.X?(k.D!==k.K&&k.D.hide(),k.table.hide()):(k.D!==k.K&&k.D.show(),k.table.show()))},GUK=function(k){var a=Tn9(k),y=Math,q=y.min;
var e=k.j?Date.now()-k.j:0;y=q.call(y,e,a);xId(k,Math.ceil((a-y)/1E3));a-y<=500&&k.sR()?k.select(!0):k.sR()&&k.L.start()},lYX=function(k){k=k.Z();
return k.I8&&!k.zo&&!k.disableOrganicUi},Tr=function(k){dh.call(this,k,"watch-again-on-youtube-endscreen");
this.watchButton=new VwG(k,1);g.U(this,this.watchButton);this.watchButton.pw(this.element);g.LP7(k)&&(this.K=new g.PP(k),g.U(this,this.K),this.D=new g.u({C:"div",nw:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],U:{tabIndex:"-1"},S:[this.K]}),g.U(this,this.D),this.K.pw(this.D.element),this.D.pw(this.element));k.createClientVe(this.element,this,156914);this.hide()},RX9=function(k,a){a=a.getWatchNextResponse();
var y,q;a=(y=DIK(a))==null?void 0:(q=y.nextButton)==null?void 0:q.buttonRenderer;k.X=a==null?void 0:a.navigationEndpoint;y=a==null?void 0:a.trackingParams;k.playButton&&y&&k.J.setTrackingParams(k.playButton.element,y)},xId=function(k,a){a=a===void 0?-1:a;
k=k.K.ij("ytp-autonav-endscreen-upnext-header");g.J2(k);if(a>=0){a=String(a);var y="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],q="Up next in $SECONDS".indexOf(y);if(q>=0){k.appendChild(g.m_("Up next in $SECONDS".slice(0,q)));var e=g.d9("span");g.h7(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.uF(e,a);k.appendChild(e);k.appendChild(g.m_("Up next in $SECONDS".slice(q+y.length)));return}}g.uF(k,"Up next")},QZX=function(k){k.publish("autonavvisibility")},ZJ=function(k){g.u.call(this,
{C:"div",
nw:["ytp-upnext","ytp-player-content"],U:{"aria-label":"{{aria_label}}"},S:[{C:"div",T:"ytp-cued-thumbnail-overlay-image",U:{style:"{{background}}"}},{C:"span",T:"ytp-upnext-top",S:[{C:"span",T:"ytp-upnext-header",Dq:"Up Next"},{C:"span",T:"ytp-upnext-title",Dq:"{{title}}"},{C:"span",T:"ytp-upnext-author",Dq:"{{author}}"}]},{C:"a",T:"ytp-upnext-autoplay-icon",U:{role:"button",href:"{{url}}","aria-label":"Play next video"},S:[{C:"svg",U:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
S:[{C:"circle",T:"ytp-svg-autoplay-circle",U:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{C:"circle",T:"ytp-svg-autoplay-ring",U:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{C:"path",T:"ytp-svg-fill",U:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{C:"span",T:"ytp-upnext-bottom",S:[{C:"span",T:"ytp-upnext-cancel"},{C:"span",T:"ytp-upnext-paused",
Dq:"Autoplay is paused"}]}]});this.api=k;this.cancelButton=null;this.X=this.ij("ytp-svg-autoplay-ring");this.j=this.notification=this.K=this.suggestion=null;this.L=new g.gD(this.hP,5E3,this);this.D=0;var a=this.ij("ytp-upnext-cancel");this.cancelButton=new g.u({C:"button",nw:["ytp-upnext-cancel-button","ytp-button"],U:{tabindex:"0","aria-label":"Cancel autoplay"},Dq:"Cancel"});g.U(this,this.cancelButton);this.cancelButton.listen("click",this.eN,this);this.cancelButton.pw(a);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.U(this,this.L);this.api.createClientVe(this.element,this,18788);a=this.ij("ytp-upnext-autoplay-icon");this.Y(a,"click",this.nA);this.api.createClientVe(a,this,115130);this.TA();this.Y(k,"autonavvisibility",this.TA);this.Y(k,"mdxnowautoplaying",this.P_G);this.Y(k,"mdxautoplaycanceled",this.aSZ);g.iM(this.element,"ytp-upnext-mobile",this.api.Z().D)},dh=function(k,a){g.u.call(this,{C:"div",
nw:["html5-endscreen","ytp-player-content",a||"base-endscreen"]});this.created=!1;this.player=k},g_X=function(k){g.pF.call(this,k);
var a=this;this.endScreen=null;this.K=this.D=this.j=!1;this.listeners=new g.e9(this);g.U(this,this.listeners);var y=k.Z();k.isEmbedsShortsMode()?this.endScreen=new Tr(k):lYX(k)?(this.j=!0,bWd(this),this.K?this.endScreen=new YW(k):y.W("delhi_modern_endscreen")?this.endScreen=new WW9(k):this.endScreen=new zr(k)):y.zo?this.endScreen=new mI2(k):this.endScreen=new dh(k);g.U(this,this.endScreen);g.ED(k,this.endScreen.element,4);iWr(this);this.listeners.Y(k,"videodatachange",this.onVideoDataChange,this);
this.listeners.Y(k,g.BV("endscreen"),function(q){a.onCueRangeEnter(q)});
this.listeners.Y(k,g.tx("endscreen"),function(q){a.onCueRangeExit(q)})},bWd=function(k){var a=k.player.getVideoData();
if(!a||k.K===a.vC&&k.D===a.rJ)return!1;k.K=a.vC;k.D=a.rJ;return!0},VwG=function(k,a){g.u.call(this,{C:"button",
nw:["ytp-watch-on-youtube-button","ytp-button"],Dq:"{{content}}"});this.J=k;this.buttonType=this.buttonType=a;this.r6();this.buttonType===2&&g.C7(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.r6);this.h3(!0)},Si=function(k){return g.L4(k.player)&&k.DR()&&!k.L},UL=function(k){var a=k.DA();
a!==k.G&&(k.G=a,QZX(k.player))};
g.vg.prototype.tY=g.$g(6,function(){return this.app.tY()});
g.cg.prototype.tY=g.$g(5,function(){return this.getVideoData().yr});
g.WM.prototype.qY=g.$g(4,function(k){this.TN().qY(k)});
g.aA.prototype.qY=g.$g(3,function(k){this.zj!==k&&(this.zj=k,this.lq())});
g.I(Hc,g.u);Hc.prototype.select=function(){this.J.QQ(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Hm||void 0)&&this.J.logClick(this.element)};
Hc.prototype.onClick=function(k){g.TU(k,this.J,this.K,this.suggestion.sessionData||void 0)&&this.select()};
Hc.prototype.onKeyPress=function(k){switch(k.keyCode){case 13:case 32:k.defaultPrevented||(this.select(),k.preventDefault())}};g.I(Bc,g.u);g.S=Bc.prototype;g.S.fK=function(k){this.suggestion!==k&&(this.suggestion=k,g.HD(this.K,k),this.playButton.updateValue("url",this.suggestion.GN()),i1(this))};
g.S.sR=function(){return this.j>0};
g.S.u$=function(){this.sR()||(this.j=Date.now(),GUK(this),OW1(this.J,Tn9(this)),g.iM(this.J.getRootNode(),"countdown-running",this.sR()))};
g.S.GP=function(){this.wC();GUK(this);var k=this.K.ij("ytp-autonav-endscreen-upnext-header");k&&g.uF(k,"Up next")};
g.S.wC=function(){this.sR()&&(this.L.stop(),this.j=0)};
g.S.select=function(k){this.J.nextVideo(!1,k===void 0?!1:k);this.wC()};
g.S.sz=function(k){g.TU(k,this.J)&&(k.currentTarget===this.playButton.element?this.J.logClick(this.playButton.element):k.currentTarget===this.K.ij("ytp-autonav-endscreen-link-container")&&(k=this.K.ij("ytp-autonav-endscreen-link-container"),this.J.logVisibility(k,!0),this.J.logClick(k)),this.X?(this.J.qE("innertubeCommand",this.X),this.wC()):this.select())};
g.S.pA=function(){this.J.logClick(this.cancelButton.element);g.hl(this.J,!0);this.cancelCommand&&this.J.qE("innertubeCommand",this.cancelCommand)};
g.S.onVideoDataChange=function(k,a){RX9(this,a);k=a.getWatchNextResponse();var y,q;k=(y=DIK(k))==null?void 0:(q=y.cancelButton)==null?void 0:q.buttonRenderer;this.cancelCommand=k==null?void 0:k.command};
g.S.Cbw=function(k){if(wm9(this)){var a=this.J.getVideoData().watchToWatchTransitionRenderer,y=a==null?void 0:a.fromColorPaletteDark;a=a==null?void 0:a.toColorPaletteDark;if(y&&a){var q=this.element;q.style.setProperty("--w2w-start-background-color",g.dw(y.surgeColor));q.style.setProperty("--w2w-start-primary-text-color",g.dw(y.primaryTitleColor));q.style.setProperty("--w2w-start-secondary-text-color",g.dw(y.secondaryTitleColor));q.style.setProperty("--w2w-end-background-color",g.dw(a.surgeColor));
q.style.setProperty("--w2w-end-primary-text-color",g.dw(a.primaryTitleColor));q.style.setProperty("--w2w-end-secondary-text-color",g.dw(a.secondaryTitleColor));q.style.setProperty("--w2w-animation-duration",k+"ms")}g.iM(this.element,"ytp-w2w-animate",!0)}};
g.S.Jm=function(k){this.J.W("web_autonav_color_transition")&&k!==2&&g.iM(this.element,"ytp-w2w-animate",!1)};
g.S.x7=function(){var k=this.J.DA();this.N&&this.LD!==k&&this.h3(k);i1(this);this.J.logVisibility(this.container.element,k);this.J.logVisibility(this.cancelButton.element,k);this.J.logVisibility(this.K.ij("ytp-autonav-endscreen-link-container"),k);this.J.logVisibility(this.playButton.element,k)};
g.S.O_=function(k){return k.width<400||k.height<459};g.I(dh,g.u);g.S=dh.prototype;g.S.create=function(){this.created=!0};
g.S.destroy=function(){this.created=!1};
g.S.DR=function(){return!1};
g.S.DA=function(){return!1};
g.S.ZG=function(){return!1};g.I(ZJ,g.u);g.S=ZJ.prototype;g.S.hP=function(){this.notification&&(this.L.stop(),this.xp(this.j),this.j=null,this.notification.close(),this.notification=null)};
g.S.fK=function(k){this.suggestion=k;g.HD(this,k,"hqdefault.jpg")};
g.S.TA=function(){this.h3(this.api.DA());this.api.logVisibility(this.element,this.api.DA());this.api.logVisibility(this.ij("ytp-upnext-autoplay-icon"),this.api.DA());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.DA())};
g.S.Ldj=function(){window.focus();this.hP()};
g.S.u$=function(k){var a=this;this.sR()||(g.u$("a11y-announce","Up Next "+this.suggestion.title),this.D=(0,g.Bi)(),this.K=new g.gD(function(){UId(a,k)},25),UId(this,k),OW1(this.api,Sd9(this,k)));
g.MF(this.element,"ytp-upnext-autoplay-paused")};
g.S.hide=function(){g.u.prototype.hide.call(this)};
g.S.sR=function(){return!!this.K};
g.S.GP=function(){this.wC();this.D=(0,g.Bi)();UId(this);g.C7(this.element,"ytp-upnext-autoplay-paused")};
g.S.wC=function(){this.sR()&&(this.K.dispose(),this.K=null)};
g.S.select=function(k){k=k===void 0?!1:k;if(this.api.Z().W("autonav_notifications")&&k&&window.Notification&&typeof document.hasFocus==="function"){var a=Notification.permission;a==="default"?Notification.requestPermission():a!=="granted"||document.hasFocus()||(this.hP(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.d9()}),this.j=this.Y(this.notification,"click",this.Ldj),this.L.start())}this.wC();this.api.nextVideo(!1,k)};
g.S.nA=function(k){!g.RE(this.cancelButton.element,k.target)&&g.TU(k,this.api)&&(this.api.DA()&&this.api.logClick(this.ij("ytp-upnext-autoplay-icon")),this.select())};
g.S.eN=function(){this.api.DA()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.hl(this.api,!0)};
g.S.P_G=function(k){this.api.getPresentingPlayerType();this.show();this.u$(k)};
g.S.aSZ=function(){this.api.getPresentingPlayerType();this.wC();this.hide()};
g.S.uj=function(){this.wC();this.hP();g.u.prototype.uj.call(this)};g.I(YW,dh);g.S=YW.prototype;g.S.create=function(){dh.prototype.create.call(this);this.L.Y(this.player,"appresize",this.gD);this.L.Y(this.player,"onVideoAreaChange",this.gD);this.L.Y(this.player,"videodatachange",this.onVideoDataChange);this.L.Y(this.player,"autonavchange",this.zA);this.L.Y(this.player,"onAutonavCancelled",this.oA);this.onVideoDataChange()};
g.S.show=function(){dh.prototype.show.call(this);(this.N||this.j&&this.j!==this.videoData.clientPlaybackNonce)&&g.hl(this.player,!1);g.L4(this.player)&&this.DR()&&!this.j?(m6(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.K.select(!0):this.K.u$():this.videoData.autonavState===3&&this.K.GP()):(g.hl(this.player,!0),m6(this));this.gD()};
g.S.hide=function(){dh.prototype.hide.call(this);this.K.GP();m6(this)};
g.S.gD=function(){var k=this.player.TC(!0,this.player.isFullscreen());m6(this);i1(this.D);g.iM(this.element,"ytp-autonav-cancelled-small-mode",this.O_(k));g.iM(this.element,"ytp-autonav-cancelled-tiny-mode",this.ow(k));g.iM(this.element,"ytp-autonav-cancelled-mini-mode",k.width<=400||k.height<=360);this.overlay&&g.tO(this.overlay.element,{width:k.width+"px"});if(!this.X)for(k=0;k<this.videos.length;k++)g.iM(this.videos[k].element,"ytp-suggestion-card-with-margin",k%2===1)};
g.S.onVideoDataChange=function(){var k=this.player.getVideoData();if(this.videoData!==k&&k){this.videoData=k;k=this.videoData.suggestions;var a=g.tU(this.videoData);a&&(this.K.fK(a),this.K!==this.D&&this.D.fK(a));if(k&&k.length)for(a=0;a<sZ9.length;++a){var y=sZ9[a];if(k&&k[y]){this.videos[a]=new Hc(this.player);var q=this.videos[a];y=k[y];q.suggestion!==y&&(q.suggestion=y,g.HD(q,y));g.U(this,this.videos[a]);this.videos[a].pw(this.G.element)}}this.gD()}};
g.S.zA=function(k){k===1?(this.N=!1,this.j=this.videoData.clientPlaybackNonce,this.K.wC(),this.LD&&this.gD()):(this.N=!0,this.DA()&&(k===2?this.K.u$():k===3&&this.K.GP()))};
g.S.oA=function(k){k?this.zA(1):(this.j=null,this.N=!1)};
g.S.DR=function(){return this.videoData.autonavState!==1};
g.S.O_=function(k){return(k.width<910||k.height<459)&&!this.ow(k)&&!(k.width<=400||k.height<=360)};
g.S.ow=function(k){return k.width<800&&!(k.width<=400||k.height<=360)};
g.S.DA=function(){return this.LD&&g.L4(this.player)&&this.DR()&&!this.j};
var sZ9=[1,3,2,4];g.I(WW9,dh);g.S=WW9.prototype;g.S.create=function(){dh.prototype.create.call(this);var k=this.player.getVideoData();k&&(this.videoData=k);this.Tl();this.D.Y(this.player,"appresize",this.Tl);this.D.Y(this.player,"onVideoAreaChange",this.Tl);this.D.Y(this.player,"videodatachange",this.onVideoDataChange);this.D.Y(this.player,"autonavchange",this.FV);this.D.Y(this.player,"onAutonavCancelled",this.IA);k=this.videoData.autonavState;k!==this.G&&this.FV(k);this.D.Y(this.element,"transitionend",this.Wa)};
g.S.destroy=function(){g.Eu(this.D);g.WT(this.stills);this.stills=[];dh.prototype.destroy.call(this);g.MF(this.element,"ytp-show-tiles");this.X.stop();this.G=this.videoData.autonavState};
g.S.DR=function(){return this.videoData.autonavState!==1};
g.S.show=function(){var k=this.LD;dh.prototype.show.call(this);g.MF(this.element,"ytp-show-tiles");this.player.Z().D?g.VT(this.X):this.X.start();(this.L||this.j&&this.j!==this.videoData.clientPlaybackNonce)&&g.hl(this.player,!1);Wc(this)?(ji(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.K.select(!0):this.K.u$():this.videoData.autonavState===3&&this.K.GP()):(g.hl(this.player,!0),ji(this));k!==this.LD&&this.player.logVisibility(this.element,!0)};
g.S.hide=function(){var k=this.LD;dh.prototype.hide.call(this);this.K.GP();ji(this);k!==this.LD&&this.player.logVisibility(this.element,!1)};
g.S.Wa=function(k){k.target===this.element&&this.Tl()};
g.S.Tl=function(){var k,a,y,q;var e=((k=this.videoData)==null?0:(a=k.suggestions)==null?0:a.length)?(y=this.videoData)==null?void 0:y.suggestions:[(q=this.videoData)==null?void 0:g.tU(q)];if(e.length){a=this.J.TC(!0,this.J.isFullscreen());k=Math.floor((a.width-64+16)/(g.nz(a.width*.27,250,450)+16));a=Math.min(3,Math.floor((a.height-64)/((a.width-64-(k-1)*16)/k*.5625+70)));g.I1(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.C7(this.element,"ytp-modern-endscreen-limit-rows-"+a);g.iM(this.element,"ytp-modern-endscreen-single-item",k===1);g.iM(this.element,"ytp-modern-endscreen-row-0",a===0);k=this.table.element;k.ariaLive="polite";this.K.fK(g.tU(this.videoData));this.K instanceof Bc&&i1(this.K);g.iM(this.element,"ytp-endscreen-takeover",Wc(this));ji(this);a=0;k.ariaBusy="true";y=e.length;for(q=0;q<y;q++){var f=q%y,H=this.stills[q];H||(H=new g.AM(this.player),this.stills[q]=H,k.appendChild(H.element));g.WGO(H,e[f]);a++}this.stills.length=
a}};
g.S.onVideoDataChange=function(){var k=this.player.getVideoData(1);this.videoData!==k&&(k!=null&&g.tU(k)?(this.videoData=k,this.Tl()):this.player.lj("missg",{vid:(k==null?void 0:k.videoId)||"",cpn:(k==null?void 0:k.clientPlaybackNonce)||""}))};
g.S.ZG=function(){return this.K.sR()};
g.S.FV=function(k){k===1?(this.L=!1,this.j=this.videoData.clientPlaybackNonce,this.K.wC(),this.LD&&this.Tl()):(this.L=!0,this.LD&&Wc(this)&&(k===2?this.K.u$():k===3&&this.K.GP()))};
g.S.IA=function(k){if(k){for(k=0;k<this.stills.length;k++)this.J.logVisibility(this.stills[k].element,!0);this.FV(1)}else this.j=null,this.L=!1;this.Tl()};
g.S.DA=function(){return this.LD&&Wc(this)};g.I(mI2,dh);mI2.prototype.GF=function(){var k=this.player.getVideoData();this.K.update({profilePicture:k.profilePicture,author:k.author});this.subscribeButton.channelId=k.BC;var a=this.subscribeButton;k.subscribed?a.K():a.D()};g.I(rh,g.u);rh.prototype.select=function(){this.api.QQ(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Hm||void 0)&&this.api.logClick(this.element)};
rh.prototype.onClick=function(k){if(g.kq(this.api.Z())&&this.api.W("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var a=this.suggestion.GN(),y={};g.Wm(this.api,y);a=g.D2(a,y);g.mW(a,this.api,k)}else g.TU(k,this.api,this.D,this.suggestion.sessionData||void 0)&&this.select()};
rh.prototype.onKeyPress=function(k){switch(k.keyCode){case 13:case 32:k.defaultPrevented||(this.select(),k.preventDefault())}};
rh.prototype.onVideoDataChange=function(){var k=this.api.getVideoData(),a=this.api.Z();this.D=k.SR?!1:a.L};g.I(zr,dh);g.S=zr.prototype;g.S.create=function(){dh.prototype.create.call(this);var k=this.player.getVideoData();k&&(this.videoData=k);this.J5();this.D.Y(this.player,"appresize",this.J5);this.D.Y(this.player,"onVideoAreaChange",this.J5);this.D.Y(this.player,"videodatachange",this.onVideoDataChange);this.D.Y(this.player,"autonavchange",this.gQ);this.D.Y(this.player,"onAutonavCancelled",this.N7);k=this.videoData.autonavState;k!==this.V&&this.gQ(k);this.D.Y(this.element,"transitionend",this.s8)};
g.S.destroy=function(){g.Eu(this.D);g.WT(this.stills);this.stills=[];dh.prototype.destroy.call(this);g.MF(this.element,"ytp-show-tiles");this.N.stop();this.V=this.videoData.autonavState};
g.S.DR=function(){return this.videoData.autonavState!==1};
g.S.show=function(){var k=this.LD;dh.prototype.show.call(this);g.MF(this.element,"ytp-show-tiles");this.player.Z().D?g.VT(this.N):this.N.start();(this.X||this.L&&this.L!==this.videoData.clientPlaybackNonce)&&g.hl(this.player,!1);Si(this)?(UL(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.K.select(!0):this.K.u$():this.videoData.autonavState===3&&this.K.GP()):(g.hl(this.player,!0),UL(this));k!==this.LD&&this.player.logVisibility(this.element,!0)};
g.S.hide=function(){var k=this.LD;dh.prototype.hide.call(this);this.K.GP();UL(this);k!==this.LD&&this.player.logVisibility(this.element,!1)};
g.S.s8=function(k){k.target===this.element&&this.J5()};
g.S.J5=function(){var k,a,y,q;var e=((k=this.videoData)==null?0:(a=k.suggestions)==null?0:a.length)?(y=this.videoData)==null?void 0:y.suggestions:[(q=this.videoData)==null?void 0:g.tU(q)];if(e.length){g.C7(this.element,"ytp-endscreen-paginate");var f=this.J.TC(!0,this.J.isFullscreen());if(k=g.nO(this.J))k=k.ww()?48:32,f.width-=k*2;var H=f.width/f.height;q=96/54;a=k=2;var B=Math.max(f.width/96,2),Z=Math.max(f.height/54,2);y=e.length;var z=y*4;for(z-=4;z>0&&(k<B||a<Z);){var Y=k/2,r=a/2,W=k<=B-2&&z>=
r*4,m=a<=Z-2&&z>=Y*4;if((Y+1)/r*q/H>H/(Y/(r+1)*q)&&m)z-=Y*4,a+=2;else if(W)z-=r*4,k+=2;else if(m)z-=Y*4,a+=2;else break}q=!1;z>=12&&y*4-z<=6&&(a>=4||k>=4)&&(q=!0);z=k*96;B=a*54;H=z/B<H?f.height/B:f.width/z;H=Math.min(H,2);z=Math.floor(Math.min(f.width,z*H));B=Math.floor(Math.min(f.height,B*H));f=this.table.element;f.ariaLive="polite";g.SA(f,z,B);g.tO(f,{marginLeft:z/-2+"px",marginTop:B/-2+"px"});this.K.fK(g.tU(this.videoData));this.K instanceof Bc&&i1(this.K);g.iM(this.element,"ytp-endscreen-takeover",
Si(this));UL(this);z+=4;B+=4;H=0;f.ariaBusy="true";for(Z=0;Z<k;Z++)for(Y=0;Y<a;Y++)if(r=H,m=0,q&&Z>=k-2&&Y>=a-2?m=1:Y%2===0&&Z%2===0&&(Y<2&&Z<2?Y===0&&Z===0&&(m=2):m=2),r=g.cg8(r+this.j,y),m!==0){W=this.stills[H];W||(W=new rh(this.player),this.stills[H]=W,f.appendChild(W.element));var T=Math.floor(B*Y/a),O=Math.floor(z*Z/k),x=Math.floor(B*(Y+m)/a)-T-4,V=Math.floor(z*(Z+m)/k)-O-4;g.DW(W.element,O,T);g.SA(W.element,V,x);g.tO(W.element,"transitionDelay",(Y+Z)/20+"s");g.iM(W.element,"ytp-videowall-still-mini",
m===1);g.iM(W.element,"ytp-videowall-still-large",m>2);m=Math.max(V,x);g.iM(W.element,"ytp-videowall-still-round-large",m>=256);g.iM(W.element,"ytp-videowall-still-round-medium",m>96&&m<256);g.iM(W.element,"ytp-videowall-still-round-small",m<=96);r=e[r];W.suggestion!==r&&(W.suggestion=r,m=W.api.Z(),T=g.zO(W.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.HD(W,r,T),g.kq(m)&&!W.api.W("web_player_log_click_before_generating_ve_conversion_params")&&(m=r.GN(),T={},g.lB(W.api,"addEmbedsConversionTrackingParams",
[T]),m=g.D2(m,T),W.updateValue("url",m)),(r=(r=r.sessionData)&&r.itct)&&W.api.setTrackingParams(W.element,r));H++}f.ariaBusy="false";g.iM(this.element,"ytp-endscreen-paginate",H<y);for(e=this.stills.length-1;e>=H;e--)k=this.stills[e],g.JM(k.element),g.Q9(k);this.stills.length=H}};
g.S.onVideoDataChange=function(){var k=this.player.getVideoData(1);this.videoData!==k&&(k!=null&&g.tU(k)?(this.j=0,this.videoData=k,this.J5()):this.player.lj("missg",{vid:(k==null?void 0:k.videoId)||"",cpn:(k==null?void 0:k.clientPlaybackNonce)||""}))};
g.S.df=function(){this.j+=this.stills.length;this.J5()};
g.S.xG=function(){this.j-=this.stills.length;this.J5()};
g.S.ZG=function(){return this.K.sR()};
g.S.gQ=function(k){k===1?(this.X=!1,this.L=this.videoData.clientPlaybackNonce,this.K.wC(),this.LD&&this.J5()):(this.X=!0,this.LD&&Si(this)&&(k===2?this.K.u$():k===3&&this.K.GP()))};
g.S.N7=function(k){if(k){for(k=0;k<this.stills.length;k++)this.J.logVisibility(this.stills[k].element,!0);this.gQ(1)}else this.L=null,this.X=!1;this.J5()};
g.S.DA=function(){return this.LD&&Si(this)};g.I(VwG,g.u);g.S=VwG.prototype;g.S.r6=function(){switch(this.buttonType){case 1:var k="Watch again on YouTube";var a=156915;break;case 2:k="Continue watching on YouTube";a=156942;break;default:k="Continue watching on YouTube",a=156942}this.update({content:k});this.J.hasVe(this.element)&&this.J.destroyVe(this.element);this.J.createClientVe(this.element,this,a)};
g.S.onClick=function(k){this.J.W("web_player_log_click_before_generating_ve_conversion_params")&&this.J.logClick(this.element);g.mW(this.getVideoUrl(),this.J,k);this.J.W("web_player_log_click_before_generating_ve_conversion_params")||this.J.logClick(this.element)};
g.S.getVideoUrl=function(){var k=!0;switch(this.buttonType){case 1:k=!0;break;case 2:k=!1}k=this.J.getVideoUrl(k,!1,!1,!0);var a=this.J.Z();if(g.kq(a)){var y={};g.kq(a)&&g.lB(this.J,"addEmbedsConversionTrackingParams",[y]);k=g.D2(k,y)}return k};
g.S.logVisibility=function(){this.J.logVisibility(this.element,this.LD&&this.aj)};
g.S.show=function(){g.u.prototype.show.call(this);this.logVisibility()};
g.S.hide=function(){g.u.prototype.hide.call(this);this.logVisibility()};
g.S.a8=function(k){g.u.prototype.a8.call(this,k);this.logVisibility()};g.I(Tr,dh);Tr.prototype.hasSuggestions=function(){var k;return(k=this.K)==null?void 0:k.hasSuggestions()};
Tr.prototype.show=function(){if(this.player.getPlayerState()!==3){dh.prototype.show.call(this);var k=this.D;if(k){var a=this.K.hasSuggestions();g.iM(this.element,"ytp-shorts-branded-ui",a);a?k.show():k.hide()}var y;(y=g.nO(this.player))==null||y.qY(!0);this.player.logVisibility(this.element,!0);this.watchButton.a8(!0)}};
Tr.prototype.hide=function(){dh.prototype.hide.call(this);var k;(k=g.nO(this.player))==null||k.qY(!1);this.player.logVisibility(this.element,!1);this.watchButton.a8(!1)};g.I(g_X,g.pF);g.S=g_X.prototype;g.S.EF=function(){var k=this.player.getVideoData(),a=k.mutedAutoplay&&(k.limitedPlaybackDurationInSeconds>0||k.endSeconds>0||k.mutedAutoplayDurationMode!==2);if(this.player.isEmbedsShortsMode()&&!a)return!0;var y;var q=!!((k==null?0:g.tU(k))||(k==null?0:(y=k.suggestions)==null?0:y.length));q=!lYX(this.player)||q;k=k.ZE;y=this.player.zd();return q&&!k&&!y&&!a};
g.S.DA=function(){return this.endScreen.DA()};
g.S.by=function(){return this.DA()?this.endScreen.ZG():!1};
g.S.uj=function(){this.player.J_("endscreen");g.pF.prototype.uj.call(this)};
g.S.load=function(){var k=this.player.getVideoData();var a=k.transitionEndpointAtEndOfStream;if(a&&a.videoId){var y=this.player.ew().f7.get("heartbeat"),q=g.tU(k);!q||a.videoId!==q.videoId||k.Vs?(this.player.QQ(a.videoId,void 0,void 0,!0,!0,a),y&&y.Rw("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),k=!0):k=!1}else k=!1;k||(g.pF.prototype.load.call(this),this.endScreen.show())};
g.S.unload=function(){g.pF.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.S.onCueRangeEnter=function(k){this.EF()&&(this.endScreen.created||this.endScreen.create(),k.getId()==="load"&&this.load())};
g.S.onCueRangeExit=function(k){k.getId()==="load"&&this.loaded&&this.unload()};
g.S.onVideoDataChange=function(){iWr(this);this.j&&bWd(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.K?this.endScreen=new YW(this.player):this.endScreen=new zr(this.player),g.U(this,this.endScreen),g.ED(this.player,this.endScreen.element,4))};g.ht("endscreen",g_X);})(_yt_player);
